smithy-lang/smithy-typescript

README.md

N/A
Adds instructions to build depo

chore: add build instructions in README

---

README.md

Clarifies setup of dependency in README

clarify setup instructions

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/output-structure.smithy

Make output a MetadataBearer

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ApplicationProtocol.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependencies.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java

Centralize dependencies into a single file

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegatorTest.java

Add filename to writer callback

---

smithy-typescript-codegen/build.gradle.kts

bump smithy dependency to 0.9.5

bump smithy dependency to 0.9.5

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolDecoratorIntegration.java
smithy-typescript-codegen/src/test/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

Add support for SymbolProvider decoration

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java

Cleanup that moves structure generation into a class

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/EnumGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptUtils.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/EnumGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptUtilsTest.java

Add enum generator tests and improvements

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/UnionGeneratorTest.java

Add tests for structures and unions

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json

Remove tslib from dependencies of package.json

---

settings.gradle.kts
smithy-typescript-codegen-test/build.gradle.kts

Update Gradle plugin

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template

* use requestHandler instead of httpHandler
* remove protocol class
* add generic type arguments in Commands
* fix smithy-client dependency versiond

Codegen fixes

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java

Add access to dataSource on member visitors

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/NonModularServiceGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java

Example output:
```typescript
import { WeatherClient } from "./WeatherClient";
import {
GetCityCommand,
GetCityCommandInput,
GetCityCommandOutput,
} from "./commands/GetCityCommand";
import {
GetCityImageCommand,
GetCityImageCommandInput,
GetCityImageCommandOutput,
} from "./commands/GetCityImageCommand";
import {
GetCurrentTimeCommand,
GetCurrentTimeCommandInput,
GetCurrentTimeCommandOutput,
} from "./commands/GetCurrentTimeCommand";
import {
GetForecastCommand,
GetForecastCommandInput,
GetForecastCommandOutput,
} from "./commands/GetForecastCommand";
import {
ListCitiesCommand, …
```

Add non-modular client generation

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IndexGeneratorTest.java
smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/simple-service-with-operation.smithy

Generate index.ts with exports from Service and Commands.

Add index generator

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java

Update BigInteger/BigDecimal serde

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java

Add ability to write additional files

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

This commit includes various fixes for setting response members,
importing types, and documentation updates.

Protocol codegen fixes and cleanup

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

This commit fixes several issues related to typing for shapes
bound to http headers on input and output. It also fixes an issue
where payload shapes would not be properly redirected to their
respective serde function.

Fix several serde issues for http binding protocols

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ApplicationProtocol.java

Corresponding to this PR: https://github.com/aws/aws-sdk-js-v3/pull/489
/cc @srchase 

fix http application protocol options from HttpOptions to HttpHandlerOptions

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java

Add default header hooks to HTTP protocols

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json

fix unused imports and outdated code

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

This commit adds runtime validation of operation inputs that are bound
to HTTP path labels. Errors are thrown when a value is not set or set
to a value that resolves to an empty string.
Generates the following:
```ts
if (input.FooProperty !== undefined) {
const labelValue: any = input.FooProperty.toString();
if (labelValue.length <= 0) {
throw new Error('Empty value provided for input HTTP label: FooProperty.');
}
resolvedPath = resolvedPath.replace('{FooProperty}', labelValue);
} else {
throw new Error('No value provided for input HTTP label: FooProperty.');
}
```

Add validation for @httpLabel inputs

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

Command output must be a MetadataBearer if no member exists
/cc @kstich 

fix command output interface declaration when command has no output

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java

Add defaults to ServiceIOTypes

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json

Add dom ES lib for Blob support

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java

Use a delegate file writer for protocol gen

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

This commit updates path and query serialization to properly handle
serializing HTTP uri query literals. It also cleans up path serialization
and return types for request component methods.
It also includes a minor reordering of request parameter building
for ease of reading.

Fix query literal serialization

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java

Reverts awslabs/smithy-typescript#63 so it can receive additional review.

Revert "fix response payload and incorrectly parsing error response"

---

README.md

we are now using master branch
N/A
doc: remove step to switch to develop branch

doc: remove step to switch to develop branch

---

smithy-typescript-codegen/build.gradle.kts

Update smithy-codegen-core dep to 0.9.6

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

bump TS dependency version with alpha preid

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Fix not using greedy replacement label

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java

Members that are idempotency tokens should have their required state
relaxed so the token can be auto-filled for end users. [From docs:](https://awslabs.github.io/smithy/spec/core.html#idempotencytoken-trait)
>Client implementations MAY automatically provide a value for a request
>token member if and only if the member is not explicitly provided.

Relax idempotencyToken member required state

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java

Remove `__type` from exception shapes

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java

This commit adds a protected function that allows implementing
protocols to specify where inside the error response document that
information about the error resides. This is necessary for proper
deserialization of both modeled and unmodeled exceptions.
Required for aws/aws-sdk-js-v3#763

Add support for parsing wrapped error bodies

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.rn.ts.template

fix: #125 
Used the wrong commit last time. I take the blame.

fix wrong rn config template

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Fixes #130 and codegen for aws/aws-sdk-js-v3/pull/921
Original issue: aws/aws-sdk-js-v3/issues/866

Fix query list encoding

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Only apply error location adjustment for errors

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Applies modeled error members to error response

Apply modeled members on errors

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1031
Update jest to 25.1.0

Update jest to 25.1.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

bump all TS dependencies to beta versions

---

smithy-typescript-codegen-test/build.gradle.kts
smithy-typescript-codegen/build.gradle.kts

Update to Smithy 0.9.8

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java

fix request default endpoints from serde context being overwritten

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java

Missed in https://github.com/awslabs/smithy-typescript/pull/163
Update documentation for changing isa method to arrow function

Update documentation for changing isa method to arrow function

---

smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java

The test was not updated in https://github.com/awslabs/smithy-typescript/pull/163
Fix Structure Generator Tests

Update Structure Generator Tests

---

.gitignore

N/A
.gitignore VSCode just like other editor settings (Eclipse/IntelliJ) are ignored 

Add VSCode to .gitignore

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java

fix wrong url parser in RN

---

smithy-typescript-codegen-test/build.gradle.kts
smithy-typescript-codegen/build.gradle.kts

Fix versions to use a range >= 1.0.8 < 2.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Update over fix in #201
Add hostname after protocol

Add hostname after protocol

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ImportDeclarations.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ImportDeclarationsTest.java

Fixes: https://github.com/awslabs/smithy-typescript/issues/211
Disable star imports and add default imports

Disable star imports and add default imports

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1504
Default import package.json for spec compatibility

Default import package.json for spec compatibility

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1578
Switch dependencies to rc version

Switch dependencies to rc version

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java

Fixes CI failure in new clients generation https://github.com/aws/aws-sdk-js-v3/pull/1580#issuecomment-713802283
use optional chaining for pagination input/output

fix: use bang operator for pagination input/output

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1489
add clientName and commandName to HandlerExecutionContext

feat: add clientName and commandName to HandlerExecutionContext

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java

per internal discussion, we want to change pagination verbage to `paginateOperationName`

fix: change verbage to paginateOperationName

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json

This is a batch commit of a few changes in order to generate more readable API reference. 
This change is a follow up to https://github.com/aws/aws-sdk-js-v3/pull/1694
code-gen PR: https://github.com/aws/aws-sdk-js-v3/pull/1716

update docs for api reference

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/1735
Bump typescript to ~4.1.2

Bump typescript to ~4.1.2

---

smithy-typescript-codegen-test/build.gradle.kts
smithy-typescript-codegen/build.gradle.kts

Refs: https://github.com/awslabs/smithy-typescript/pull/243
This PR is required to update models with fixes for https://github.com/aws/aws-sdk-js-v3/issues/1714 and https://github.com/aws/aws-sdk-js-v3/issues/1712
The waiters generation is being tracked in https://github.com/awslabs/smithy-typescript/pull/243

Add waiters dependency for models to consume

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

remove useragent middleware dependency

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java

~~Note: This PR will be made ready for review once user agent PR is merged https://github.com/aws/aws-sdk-js-v3/pull/1775~~
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1491
Remove httpHeaders from metadata

Remove httpHeaders from metadata

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java

Refs: https://github.com/aws/aws-sdk-js-v3/issues/1521
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1522
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/1490
log requestId, extendedRequestId, cfId in $metadata

fix: log requestId, extendedRequestId, cfId in $metadata

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java

Change how paginator index is accessed. Remove deprecated function call.

fix: change paginator model access

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java

Update protocol test case generation

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java

This is the first cut of the higher-level SSDK interface generation.
It generates high level interfaces, including a service interface, which is implemented by the service developer to supply business logic, and a protocol-specific handler that bridges between serde and the supplied service implementation.

Server handler and interface generation

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2175
Moves types in dist folder

Move types in dist folder

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/jest.config.js
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/EnumGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IndexGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ServiceGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/UnionGeneratorTest.java

update ssdk with main

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

This adds support for deserializing maps with the `httpQueryParams` trait. It also fixes a bug in deserializing query params that are modeled as lists when there's only one entry.

Support deserializing query maps

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

N/A
PR to consume smithy [httpQueryParams](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html#httpqueryparams-trait) trait

Consume httpQueryParams trait

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json

chore(dep): bump typescript to 4.2.4

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

This will eliminate extra type alias link that users need to
click through when inspecting the operation input/output shape
in the API reference
See https://github.com/aws/aws-sdk-js-v3/pull/2274 for the change detail

user interface for command input output instead of type

---

smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/package.json

Set ssdk library versions to alpha

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java

This fixes an issue where artifactType would be accidentally reset
while loading integrations.

Fix issue where artifactType would get reset

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java

Validation doesn't work right now for mutually recursive structures, so this temporarily disables it to unblock an initial release.

Disable validation generation

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts

Refs: https://github.com/aws/aws-sdk-js-v3/issues/2362
Add HTML entity encoder/decoder

Add HTML entity encoder/decoder

---

build.gradle.kts

Update sonatype repo url to AWS specific url

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java

Reintroduce extra newline after protocol tests

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java

N/A
Pass additional parameters as a map in resolve function.

Pass additional parameters as a map in resolve function

---

build.gradle.kts

Version bump in preparation for a release.

Bump version to 0.4.0

---

smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-apigateway/src/lambda.ts

Add support for payload format 1.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/lerna.json
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/package.json

Bump server sdk lib versions

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

HttpRequest, as used by the SDK, does not contain encoded keys or values.
APIGateway's events also contain decoded query string keys and values. The
only thing that needs decoding is path segments, because the path is stored
un-split and thus it cannot be stored decoded (or / and %2F would be
indistinguishable).
This partially reverts 24f2eade7b1f13e3fd6eb5896f05152b5d3b0fef

Revert decoding of query parameters

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddChecksumRequiredDependency.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/2573
Fix link to Hash interface

Fix link to Hash interface

---

build.gradle.kts

related: https://github.com/aws/aws-sdk-js-v3/pull/2589

Bump code generators to 0.4.1

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template

Internal JS-2737
Support undefined client config

fix: support undefined client config

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java

fix(ssdk): import handler from src folder

---

.github/CODEOWNERS

Add missing file extension for codeowner

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/lerna.json
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

Bump ssdk lib version

---

CHANGELOG.md
build.gradle.kts

Bump code generators to 0.7.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

docs: fix the client config link message

---

build.gradle.kts

chore(deps): bump smithy to 1.14.x

---

CHANGELOG.md
build.gradle.kts

Bump code generators to 0.8.0

---

build.gradle.kts

Bump smithy to 1.15.x

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/jest.config.js

N/A
Do not recommend any specific test framework

chore(package.json): do not recommend any specific test framework

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/lerna.json
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

Bump ssdk lib version to 1.0.0-alpha.4

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.cjs.json
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/3185
Uses @tsconfig/recommended for tsconfig.json and adds tsconfig.cjs.json for build:cjs

Use @tsconfig/recommended and add tsconfig.cjs.json

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json

Refs: https://github.com/aws/aws-sdk-js-v3/pull/3192#issuecomment-1013519478
Add exclude for test folder in tsconfig.json

Add exclude for test folder in tsconfig.json

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json

Refs: https://github.com/aws/aws-sdk-js-v3/issues/3196
Runs builds concurrently for clients

Run builds concurrently

---

build.gradle.kts
smithy-typescript-codegen-test/build.gradle.kts

There will be a corresponding SDK update. Not bumping the generator version until the next SDK release is confirmed.

Update to Smithy-1.16.3

---

build.gradle.kts

Update to Smithy 1.17.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

Bump ssdk lib version to 1.0.0-alpha.5

---

README.md

Update to codegen 0.10.0 in README

---

build.gradle.kts

Update to Smithy 1.19.x

---

README.md

Do not merge until after the release of 0.11.0.

Update codegen to 0.11.0 in README

---

build.gradle.kts

Update to Smithy 1.21.x

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

Preparing for release to pick up updated dependencies.

Bump ssdk lib version to 1.0.0-alpha.6

---

smithy-typescript-codegen/build.gradle.kts
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsParamNameMap.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetSerializer.java

Add code generation for endpoints v2.

feat(endpoint): endpoints v2 codegen

---

CHANGELOG.md
build.gradle.kts

Bump version to 0.12.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java

refixes https://github.com/aws/aws-sdk-js-v3/issues/1521

include x-amz-request-id in request id deser

---

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json

Reverts awslabs/smithy-typescript#608

chore(dist-es): re-apply es2020 dist-es target

---

build.gradle.kts
gradle.properties
smithy-typescript-codegen-test/build.gradle.kts
smithy-typescript-codegen/build.gradle.kts

Move Smithy version settings to gradle properties

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Internal JS-3705
Imports fromUtf8 and toUtf8 from util-base64

Import fromBase64 and toBase64 from util-base64

---

README.md
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

Update links to point to smithy.io

---

.github/workflows/ci.yml

Refs: https://github.com/aws/aws-sdk-js-v3/pull/4200
Bumps actions/checkout to v3

Bump actions/checkout to v3

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

reapply https://github.com/awslabs/smithy-typescript/pull/646

Validate required input query params

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

make package conditional so as not to insert the dependency into every client

fix(codegen): make util retry conditional

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Upgrade the big.js dependency

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddChecksumRequiredDependency.java

Replace Hash with Checksum

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

import fromUtf8 and toUtf8 from util-utf8

Import fromUtf8 and toUtf8 from util-utf8

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

Preparing for release to pick up updated dependencies.

Bump ssdk lib version to 1.0.0-alpha.7

---

gradle.properties

Upgrade to Smithy 1.26.4

---

gradle.properties

Upgrade to Smithy 1.27.2

---

CHANGELOG.md
build.gradle.kts

Bump version to 0.13.0

---

README.md

N/A.
Update README.md to use 0.13.0.

Update README.md to use 0.13.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/yarn.lock

N/A.
Bump SSDK libs version to 1.0.0-alpha.8.

Bump SSDK libs version to 1.0.0-alpha.8

---

CHANGELOG.md
README.md
build.gradle.kts

Bump version to 0.14.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/4454
Bump fast-xml-parser to 4.1.2

Bump fast-xml-parser to 4.1.2

---

.github/dependabot.yml

Issue #220 
Description of changes:
Dependabot configuration for gradle

dependabot configuration (#220)

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-ssdk-libs/package.json
smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md
smithy-typescript-ssdk-libs/server-apigateway/package.json
smithy-typescript-ssdk-libs/server-common/CHANGELOG.md
smithy-typescript-ssdk-libs/server-common/package.json
smithy-typescript-ssdk-libs/server-node/CHANGELOG.md
smithy-typescript-ssdk-libs/server-node/package.json

Bump SSDK libs version to 1.0.0-alpha.10

---

CHANGELOG.md
README.md
build.gradle.kts

This reverts commit bff62855f099400828139b33bdf35fc316b92f1b.
Revert 0.15.0 version bump.

Revert "Bump version to 0.15.0 (#751)"

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Refs: https://github.com/aws/aws-sdk-js-v3/pull/4796
Bump fast-xml-parser to 4.2.4

Bump fast-xml-parser to 4.2.4

---

.changeset/empty-turkeys-flow.md
.changeset/silent-experts-dream.md
packages/protocol-http/CHANGELOG.md
packages/protocol-http/package.json
packages/types/CHANGELOG.md
packages/types/package.json

This PR applies the pending changesets to the protocol-http and types packages.

Bump types and protocol-http

---

.github/workflows/release-npm-packages.yml

Checkout main before committing and pushing on NPM release workflow.

Checkout main before push

---

packages/util-defaults-mode-browser/package.json
packages/util-defaults-mode-node/package.json

Adds package.json script entries to match other NPM packages.

Add missing package.json scripts

---

.github/workflows/release-npm-packages.yml

Fix workflow name to match file and actual use.

Fix release workflow name

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Bump fast-xml-parser to 4.2.5

---

packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts

copy of https://github.com/aws/aws-sdk-js-v3/pull/4880

fix(node-http-handler): rejoin on error in writeRequestBody

---

.changeset/curly-cows-give.md
packages/util-retry/src/ConfiguredRetryStrategy.spec.ts
packages/util-retry/src/StandardRetryStrategy.spec.ts
packages/util-retry/src/StandardRetryStrategy.ts

Applies the same fix from https://github.com/aws/aws-sdk-js-v3/pull/4891

Fix attempts count on StandardRetryStrategy

---

CHANGELOG.md
README.md
build.gradle.kts

Bump version to 0.16.0

---

gradle.properties

Upgrade to Smithy 1.33.0

---

CHANGELOG.md
README.md
build.gradle.kts

Bump version to 0.17.0

---

CHANGELOG.md
README.md
build.gradle.kts

Bump version to 0.17.1

---

.github/workflows/ci.yml

This PR updates CI to build the generated TypeScript client.
---

Build generated client on CI

---

.github/workflows/release-npm-packages.yml

Fix typo in GitHub action for publishing.
---

Fix GitHub action typo

---

smithy-typescript-codegen-test/model/main.smithy
smithy-typescript-codegen-test/model/more-nesting.smithy
smithy-typescript-codegen-test/model/nested.smithy

Upgrade to 2.0 and run `smithy format` on model directory.
---

Upgrade test model to 2.0 and format

---

.changeset/empty-eyes-remember.md

Update @smithy/types to patch in changeset markdown file

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ClientConfigurationGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/Dependency.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeExtensionsGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/ClientConfigurationInterface.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/DefaultClientConfigurationInterface.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/clientConfiguration.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/resolveRuntimeExtensions1.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/resolveRuntimeExtensions2.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeExtensions1.template
smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeExtensions2.template

Revert "Remove codegen to add extensions to client runtime config (#863)"
This reverts commit 65da3e5a9a659529ae28417582a88d39ad354add.
---

Revert "Remove codegen to add extensions to client runtime config"

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java

Update client runtime config extensions field to be nullable

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Bump `@smithy` packages codegen versions

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

N/A.
Update TypeScript codegen dependencies.
---

Update TypeScript codegen dependencies

---

.changeset/smart-months-compete.md
packages/protocol-http/src/httpHandler.ts

Add default generic type to HttpHandler

---

.changeset/afraid-spies-smash.md
packages/protocol-http/src/extensions/httpExtensionConfiguration.ts
packages/protocol-http/src/httpHandler.ts

Fix default HttpHandlerConfig type for HttpHandler

---

.changeset/friendly-owls-notice.md
packages/util-stream/src/util-stream.integ.spec.ts

N/A.
Add type to `requestHandler` implementation.
---

chore(util-stream): add type to `requestHandler`

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java

also accept lowercase param type names

allow lowercase string/boolean param type names

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java

N/A.
Make `writeDocs()` with `Runnable` public.
---

Make `writeDocs()` with `Runnable` public

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java

N/A.
Reorganize http auth module constants.
---

chore(experimentalIdentityAndAuth): reorganize http auth module constants

---

.changeset/sixty-seahorses-own.md
packages/experimental-identity-and-auth/src/HttpAuthSchemeProvider.ts

N/A.
Update `HttpAuthSchemeParametersProvider` to take in `input`.
---

feat(experimentalIdentityAndAuth): update `HttpAuthSchemeParametersProvider` to take in `input`

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/sections/SmithyContextCodeSection.java

N/A.
Add `SmithyContextCodeSection` to `CommandGenerator`.
---

Add `SmithyContextCodeSection` to `CommandGenerator`

---

.changeset/serious-fans-hear.md
packages/shared-ini-file-loader/src/parseIni.spec.ts
packages/shared-ini-file-loader/src/parseIni.ts

Refs: https://github.com/awslabs/smithy-typescript/issues/985#issuecomment-1749399264
Reads values from main settings when parsing INI files
---

Read values from main section when parsing INI files

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemeMiddleware.java

N/A.
Fix `resolveHttpAuthSchemeConfig` imports.
---

fix(experimentalIdentityAndAuth): fix `resolveHttpAuthSchemeConfig` imports

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java

N/A.
Fix `HttpAuthSchemeParameter`s codegen.
---

feat(experimentalIdentityAndAuth): fix `HttpAuthSchemeParameter`s codegen

---

.changeset/strange-tigers-hope.md
packages/experimental-identity-and-auth/jest.config.integ.js
packages/experimental-identity-and-auth/package.json
yarn.lock

N/A.
Scaffold integration tests.
---

feat(experimentalIdentityAndAuth): scaffold integration tests

---

.changeset/fluffy-bugs-grin.md
packages/experimental-identity-and-auth/src/HttpAuthSchemeProvider.ts
packages/experimental-identity-and-auth/src/endpointRuleSet.ts
packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/getHttpAuthSchemePlugin.ts
packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/httpAuthSchemeMiddleware.ts
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java

N/A.
Remove generic parameter defaults.
---

feat(experimentalIdentityAndAuth): remove generic parameter defaults

---

.changeset/clever-doors-joke.md
packages/experimental-identity-and-auth/jest.config.js
packages/experimental-identity-and-auth/package.json

N/A.
Fix test script to use `jest`.
---

fix(experimentalIdentityAndAuth): fix test script to use `jest`

---

scripts/build-generated-test-packages.js
smithy-typescript-codegen-test/smithy-build.json

N/A.
*Dependent on: https://github.com/awslabs/smithy-typescript/pull/1021*
Build `client-experimental-identity-and-auth` client.
---

feat(experimentalIdentityAndAuth): build `client-experimental-identity-and-auth` client

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Reverts awslabs/smithy-typescript#1030

Revert "update aws-crypto dependencies to 5.1.0"

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java
smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/PackageJsonGeneratorTest.java

N/A.
Update vitest test script pass with no tests.
---

Update vitest test script pass with no tests

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java

N/A.
Check effective auth schemes equality including order.
---

fix(experimentalIdentityAndAuth): check effective auth schemes equality including order

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthScheme.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java

N/A.
Fix typo in `getHttpAuthSchemeOptionParametersByType()`.
---

fix(experimentalIdentityAndAuth): fix typo in `getHttpAuthSchemeOptionParametersByType()`

---

.changeset/witty-pugs-love.md
packages/signature-v4/README.md

add readme content for signature-v4

docs: add readme content for signature-v4

---

.changeset/silent-pianos-cheer.md
packages/core/package.json
packages/core/src/index.ts
packages/core/src/protocols/requestBuilder.spec.ts
packages/core/src/protocols/requestBuilder.ts
turbo.json
yarn.lock

adds a requestBuilder helper class to be used in future serde code size reduction

feat: add requestBuilder

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java

add missing dependency declaration

fix: add dependency with import

---

packages/middleware-compression/package.json
scripts/check-dependencies.js
yarn.lock

fix the dependency checking script

fix: check-dependencies script

---

smithy-typescript-codegen-test/model/identity-and-auth/httpApiKeyAuth/HttpApiKeyAuthService.smithy
smithy-typescript-codegen-test/model/identity-and-auth/httpBearerAuth/HttpBearerAuthService.smithy
smithy-typescript-codegen-test/model/weather/main.smithy
smithy-typescript-codegen-test/model/weather/more-nesting.smithy
smithy-typescript-codegen-test/model/weather/nested.smithy

Resolve a number of Smithy warnings to reduce the build noise.
*Testing*
Ran `./gradlew clean build` and confirmed no Smithy WARNING events were emitted.
---

chore: resolve smithy warnings to reduce build noise

---

build.gradle.kts
config/spotbugs/filter.xml

Performs a bulk upgrade of java dependencies.
* spotbugs 5.1.3 -> 6.0.8
* jupiter deps 5.10.0 -> 5.10.2
---

chore: bulk upgrade of java dependencies

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java

Internal JS-5074
Adds deprecation message in shape docs
---

Add deprecation message in shape docs

---

gradle.properties
smithy-typescript-codegen-test/model/weather/main.smithy

Use Smithy 1.47.0.
I want to leave the formatting as it is in main.smithy until it fixes itself automatically. I want to avoid having to check this file on every build.

update smithyVersion to 1.47.0

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.20.1
---

Bump codegen version to 0.20.1

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.21.1

---

package.json
yarn.lock

chore: update changeset cli version

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddBuiltinPlugins.java
smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
smithy-typescript-ssdk-codegen-test-utils/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration

N/A
Add set of builtin plugins that previously were only in test utils.
---

feat(codegen): add set of builtin plugins

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java

Refs: https://github.com/aws/aws-sdk-js-v3/issues/6327
Bump fast-xml-parser to 4.4.1
---

Bump fast-xml-parser to 4.4.1

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.22.0

---

.changeset/lazy-grapes-drive.md
packages/types/src/endpoint.ts

Internal JS-5234
Adds string array to EndpointParameters
---

Add string array to EndpointParameters

---

CHANGELOG.md

Fix 0.22.0 release date

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.23

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

This improvement was in back of my mind while working on https://github.com/smithy-lang/smithy-typescript/pull/1379
Use spread operator for Command endpoint params when necessary
---

Use spread operator for Command endpoint params when necessary

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.24.0

---

.changeset/serious-goats-report.md
packages/util-stream/package.json

https://github.com/smithy-lang/smithy-typescript/issues/1435

fix(util-stream): add bundler metadata for the ChecksumStream file

---

.changeset/fast-cups-speak.md
packages/core/src/pagination/createPaginator.spec.ts
packages/core/src/pagination/createPaginator.ts
packages/types/src/pagination.ts

Issue #1479
Add command-level middleware support to the pagination implementation.
---

feat(pagination): add middleware support

---

.changeset/red-pumpkins-pretend.md
packages/util-stream/src/createBufferedReadable.spec.ts
packages/util-stream/src/createBufferedReadable.ts
packages/util-stream/src/createBufferedReadableStream.browser.spec.ts
packages/util-stream/src/createBufferedReadableStream.spec.ts
packages/util-stream/src/createBufferedReadableStream.ts
scripts/check-dependencies.js

handle empty upstreams in the buffered stream helper

fix(util-stream): handle empty upstreams

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/protocols/cbor/CborShapeSerVisitor.java

fix union member serialization error copied over from JSON shape-ser-visitor

fix(codegen): fix unknown union member serialization

---

gradle.properties

Internal JS-5752
Upgrades Smithy to 1.53.0
---

Upgrade smithyVersion=1.53.0

---

CHANGELOG.md
README.md
build.gradle.kts

Internal JS-5739
Bump codegen version to 0.27.0
---

Bump codegen version to 0.27.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/ResolveConfigFunction.java
smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java

allow the httpAuthScheme resolver to access the client instance

fix: allow authscheme resolver to access client ref

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java

made this part generic since AWS types do not belong here

fix: use generic type for client config

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java

Adds the following text to code examples with streaming blob payload outputs:
```js
const command = new GetObjectCommand(input);
const response = await client.send(command);
// consume or destroy the stream to free the socket.
const bytes = await response.Body.transformToByteArray();
// const str = await response.Body.transformToString();
// response.Body.destroy() // Node.js Readable only.
```

docs: add streaming blob addendum to applicable examples

---

gradle.properties

Internal - JS-5827
Upgrades Smithy to 1.55.0
---

Update smithyVersion to 1.55.0

---

gradle.properties

https://github.com/aws/aws-sdk-js-v3/pull/7049
Upgrades smithy to 1.57.1
---

chore(codegen): upgrade smithyVersion to 1.57.1

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.30.0

---

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaGenerator.java

scrub AWS reference from the synthetic base error namespace

rename synthetic error namespace to smithy

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to 0.31.0

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle version to 8.13
---

bump gradle version 8.13

---

.changeset/gentle-balloons-drum.md
packages/fetch-http-handler/src/fetch-http-handler.spec.ts
packages/fetch-http-handler/src/fetch-http-handler.ts
packages/node-http-handler/src/node-http-handler.spec.ts
packages/node-http-handler/src/node-http-handler.ts
packages/node-http-handler/src/node-http2-handler.spec.ts
packages/node-http-handler/src/node-http2-handler.ts

Internal JS-5992
Support per-request timeouts if provided, fallback to the timeout provided in handler config.
for xhr-http-handler: https://github.com/aws/aws-sdk-js-v3/pull/7159
*Testing*
`node-http-handler`
```console
RUN  v2.1.8 /local/home/sidddsri/workspace/smithy-typescript/packages/node-http-handler
✓ src/index.spec.ts (1)
✓ src/node-http-handler.mock-server.spec.ts (17)
✓ src/node-http-handler.spec.ts (18)
✓ src/node-http2-handler.spec.ts (84) 12883ms
✓ src/set-connection-timeout.spec.ts (7)
✓ src/set-socket-keep-alive.spec.ts (4)
✓ src/set-socket-timeout.spec.ts (5)
✓ src/write-request-body.spec.ts (3)
✓ src/stream-collector/collector.spec.ts (1)
✓ src/stream-collector/index.spec.ts (3)
Test Files  10 passed (10)
Tests  143 …
```

feat(http-handlers): add support for per-request/per-operation timeouts

---

.changeset/fifty-news-serve.md
packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.spec.ts
packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts

https://github.com/smithy-lang/smithy-typescript/issues/1645
https://github.com/aws/aws-sdk-js-v3/issues/7203
This PR is a fix for the reading of env/file configured endpoints.

fix(middleware-endpoint): fix for resolving file/env endpoint

---

gradle.properties

* Internal JS-6089
* https://github.com/smithy-lang/smithy/releases/tag/1.61.0
Upgrades smithy to 1.61.0
---

Upgrade smithy to 1.61.0

---

CHANGELOG.md
README.md
build.gradle.kts

Bump codegen version to v0.35.0

---

gradle.properties

https://github.com/smithy-lang/smithy/releases/tag/1.62.0
Upgrades smithy to 1.62.0
---

Upgrade smithy to 1.62.0
