smithy-lang/smithy-typescript

smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/shapeTypes.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ImportDeclarationsTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/error-test-empty.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/error-test-optional-message.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/error-test-required-message.smithy
1. Reserved words are now escaped in the symbol visitor to account for
escaping reserved words in symbol references (like a list of Record
becomes "Array<_Record>".
2. Error structures now normalize the "message" member regardless of the
model. This prevents typing issues with super.
3. "message" is no longer generated as a property of SmithyException
subtypes.
4. Fixed a bug in how relative module imports were handled and
simplified turning module names into file names. Now the module name
of shapes that are generated always contains "index" to fix
relativizing imports.
=> Add fixes for symbols and errors

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ImportDeclarations.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/smithy.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ImportDeclarationsTest.java
This updates the generator to use interfaces for structures. Since we
are now shading types across namespaces into a single namespace, we know
that we are operating in a "closed world", meaning we know at build-time
every type that can possibly be used by a client. Therefore, we can
generate methods that determine if a given type is an instance of
another type or a subtype of it by checking for an optional "__type"
property that contains a shape ID.
This has the advantage of reduced JavaScript artifacts and more
ergonomic code. It does have a minor drawback in that developers will
need to use custom "isa" functions and will need to include the "__type"
property when defining subtypes.
When generating (de)serializers, we can take into account the shape targeted
by members to fall back to a …
=> Move back to interfaces

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/smithy.ts
This refactors tagged unions so that they now support recursive union
shapes. Previously, the TaggedUnion type we used would create a shape
that used dependent types, which meant it didn't support the kinds of
recursive interfaces we were generating. We now generate all
permutations of a union where only the specific value is set to
something and every other value is set to "never".
This change also makes unions function exactly like structures so that
it's backward compatible to change a structure to a union after GA
(e.g., if a team forgets to do this or an automatic conversion doesn't
detect a union initially).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> Refactor tagged unions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
moves generated shapes from /types to /models
clears the way for typings to be hosted in /types per tsconfig changes in https://github.com/awslabs/smithy-typescript/pull/7
=> generate shapes in models dir

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ApplicationProtocol.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Updates the generator to use the `SerdeContext` instead of distinct utils.
=> Update to SerdeContext

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPluginTest.java
Runtime client plugins now refer to each part of the plugin using symbol
references rather than just naming conventions. This allows different
aspects of the plugins to span different packages and naming formats.
Methods are provided on the Builder class for a RuntimeClientPlugin to
generate symbol references based on recommended naming conventions
(e.g., "getFooPlugin", "resolveFooConfig", "FooInputConfig",
"FooResolvedConfig", "destroyFooConfig").
=> Make runtime client plugins more flexible

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
This commit adds support for many new complex serializations. This
includes support for HTTP payloads, the prefixHeaders trait, and
nested lists, sets, maps, unions, and structures as well as their
respective HTTP binding location modifications. It also generalizes
the method for generating serde function names across the language.
This commit relies upon the changes in awslabs/smithy#193 which have not been published yet. To use it, you'll need to run `publishToMavenLocal` on an updated version of Smithy.
=> Improve complex serialization support

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
*Add deserialization support to HTTP protocols*
This commit adds support for deserializing components of HTTP responses
for protocols. Handling of document contents is abstracted so specific
protocol implementations can utilize distinct traits and writers.
A new, private serde visitor has been created out of the anonymous one
used previously. It handles outsourcing the document content serde.
The generation of some components of the source of input/output data has
been moved to a parameter of the respective operations. This allows for
greater customization downstream (unions use value, collections use entry,
etc.)
Other various fixes are also included as discovered during development,
such as member sorting.
-----
*Add support for generating shared serde components*
Also adds generation …
=> Add deserialization support to HTTP protocols

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
Update "protocol" path to "protocols", matching path used in CommandGenerator.
=> fix protocol path in CodegenVisitor

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
* Use base64 encoder and decoder functions directly.
* update naming to ``getSerdePlugin``
=> Base64 and serde plugin function name update

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/smithy.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
This commit updates the __type property of generated structures to use
the shape ID name value rather than the entire shape ID. This makes it
easier to work with the value, doesn't expose the entire ID since we
don't need the entire ID in any AWS protocols, and we can always add
__namespace as a separate property later if we need it. Because __type
is now the same as what was previously $name, I've removed $name.
This change required some tweaks to smithy.ts, including removing $name
from SmithyException, updating the documentation of __type in
SmithyException. While I was already editing that file, I also removed
dates and binary values from DocumentType (they aren't necessary and
really they shouldn't be supported until we have a use case).
*Description of …
=> Use name instead of ID and clean up JS

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ServiceGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptSettingsTest.java
Inferring which service is being generated makes it easier to codegen as
part of an automated process where you might not know the service ID of
the service to generate in advance, but you know that the model has only
one service.
=> Add ability to infer a service shape ID

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGeneratorTest.java
This commit is a significant refactor of the previous iteration of
generating HTTP protocols. Most importantly, the process of building
out support for a protocol is more composible. It has been broken
down into 2 components.
1. The HttpBindingProtocolGenerator implementation, responsible for
handling or dispatching document serde and generating components for
that.
2. The DocumentShapeSerdeVisitor implementations, responsible for
generating serde functions specific to shapes contained within the
document body of a protocol. Implmenentations for serialization
and deserialization are provided.
HttpBindingProtocolGenerator implementations are responsible for
tracking which shapes need serde generated by the implementations
of DocumentShapeSerdeVisitors.
By submitting this pull request, I …
=> Refactor HTTP protocol generation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
This commit adds support for HTTP RPC protocols through the
`HttpRpcProtocolGenerator` abstract class. Its surface area
is similar to the `HttpBindingProtocolGenerator` but instead
generates POST-based RPC api calls.
Shared code between the two `ProtocolGenerator` implementations
has been moved to a utils class for reuse; implementations and
tests have been updated accordingly.
In the process of building this feature, several bugs and some
documentation issues were resolved.
=> Add HTTP RPC protocol support

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
command's deserializer is already async, this change makes serializer
async to avoid antipattern 
refer: https://github.com/aws/aws-sdk-js-v3/pull/474
/cc @kstich @srchase 
=> feat: make command's serializer asynchronous

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
This commit updates the abstact `ProtocolGenerator` implementations
to generate unique error response deserializers. This supports error
shapes that have HTTP bindings in the `HttpBindingProtocolGenerator`
as well as adding `$metadata` contents to errors.
This commit also includes minor updates to move from `let` to `const`.
-----
-----
=> Generate unique error response deserializers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/LanguageTarget.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
This commit updates runtime configuration to now have a SHARED
LanguageTarget. This language target allows for code generated
configuration values to be provided by the code generator (for example,
setting things like the protocol name and apiVersion). This change
renames the interfaces and exported consts used in clients so that they
are more general purpose than just runtime configuration.
Related to https://github.com/aws/aws-sdk-js-v3/pull/490/files
Generates the following for runtimeConfig.shared.ts:
```typescript
export const ClientSharedValues = {
protocol: "undefined",
apiVersion: "2006-03-01",
};
```
Generates the following for runtimeConfig.ts:
```typescript
import { Hash } from "@aws-sdk/hash-node";
import { NodeHttpHandler } …
```
=> Clean up runtime config and make it more generic

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ApplicationProtocol.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnresolvableProtocolException.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
This commit updates the generator to support a single protocol and
removes the protocol name from the runtime code. We can add support for
multiple protocols in the future if needed (for example, if a service
actually splits their operations across protocols), but for now, it's
safer to expose only a single protocol in both the generator and the
generated code. The location and format of the generated protocol code
all remains the same, however, the generator no longer supports multiple
protocols in the "protocols" option, there's no longer a code generated
"protocol" property available at runtime, and the method that used to
dispatch to different protocols now just supports calling a single
protocol.
By submitting this pull request, I …
=> Support a single protocol in the generator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/NonModularServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
These changes are included:
1. populate parseBody() for non streaming command reponse and errors:
When preparing reponse body for command deserializers or error
deserializers, we don't always collect response body binaries
in structured JS object. If the command ouput or error has a
streaming trait, we need to keep the response body intact and
return users the raw response stream.
2. Update non-modular client generator to reflect the [newest client interface](https://github.com/aws/aws-sdk-js-v3/blob/2066ae107aec7b5cf967536ff37a816216e4d264/packages/smithy-client/src/client.ts#L31-L61)
3. Fix typing issues in commands
This PR generates a buildable full-blood RDS-data client: https://github.com/aws/aws-sdk-js-v3/pull/496
/cc @kstich 
By submitting this pull request, I confirm that you can …
=> fix non modular client generation

smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/reserved-words.txt, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegatorTest.java
This commit includes updates to Http ProtocolGenerator components for
correctness and safety.
1. It fixes generation issues for the @httpPrefixHeaders trait in
the HttpBindingProtocolGenerator.
2. It updates SerdeContext to use an import alias for safety.
3. It only generates a local parsedOutput if it will be consumed.
4. It adds the Error type to the list of Typescript reserved words.
-----
Use Model instead of deprecated ShapeIndex. This commit will require using the latest version of Smithy published locally.
-----
Use better name for document body shape serde gen
=> Updates for HTTP serde correctness and safety

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
This commit includes updates to handling errors to allow for streaming
error body members. It also includes minor fixes for unused properties.
=> Update Error handling through async

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptWriterTest.java
=> Escape $ chars in doc strings

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
This change will point Node package's entry point to the right place. 
=> update client package entry point and types folder

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
In some circumstances(e.g. endpoints.ts), it's very hard to infer which variable won't be used in the codegen, so we loose the ts config requirement to make the build pass. 
Later on, we shoud introduce TS linter(like prettier) to remove ununsed variables in the codegen script.
=> loosen TS compiler config for noUnusedLocals

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
~Two~Three fixes:
1. Currently when response body is a payload member, the SDK either
keeps reponse intact if it has a `streaming` trait, or parse the body
to JS object.<br/>
Actually when response payload is not streaming, it is
**NOT** always parsable(not a valid JSON or XML string). Specificly,
when payload is scalar(Number, String, BigInteger, etc.), we shouldn't
parse it with XML or JSON parser; We should also treat `Blob` shape
differently as we should encode the binaries into string; Only when
shape is `Set`, `Map` or `Structure` can we assume payload is parsable
by JSON or XML parser.
2.  For some protocols, error type flag exists in error response body,
then we need to collect response stream to JS object and parse the
error type; For other protocols, error type flag doesn't …
=> fix response payload and incorrectly parsing error response

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
Adds runtime config for use in middleware that need to modify behavior depending on runtime environment.
=> adds runtime ClientDefault

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
Use toSymbol to escape reserved words on memberShape.
=> fix memberShape using reserved words

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Use existing output body on structures instead of using parseBody to collect the stream.
=> fix parsing non-readable stream

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptWriterTest.java
Fixes doc strings containing ```*/``` causing mult-line comments to be closed prematurely.
Fixes https://github.com/awslabs/smithy-typescript/issues/74
=> escape multi-line comment close tag

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/NonModularServiceGenerator.java
Use TreeSet to wrap getContainedOperations results, ensuring consistent order.
Fixes https://github.com/awslabs/smithy-typescript/issues/75
=> ensure consistent ordering

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Set default errorCode ahead of deser in protocol.  Protocol should overwrite with more specific errorCode if available.
=> set errorCode before deser

README.md
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/613
add publishToMavenLocal command if using smithy-typescript in different package
=> chore: add publishToMavenLocal command

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java
These accessors are necessary to allow extending implementations to
not need to store their own copies of this information in order to
perform their own work.
=> Add accessors on document member visitors

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Now SDK throws error like:
```
{Error: 1 validation error detected: Value null at 'certificateArn' failed to satisfy constraint: Member must not be null 
...
```
After the change, the thrown error looks like:
```
{ValidationException: 1 validation error detected: Value null at 'certificateArn' failed to satisfy constraint: Member must not be null 
...
```
=> add error name to error deser

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This commit adds support for implementing protocols to override the
serialization behavior of a member marked with @httpPayload. This is
useful for protocols that work with intermediate objects that need to
be altered at the service level. Adding a top level xmlns attribute,
for example.
This commit also fixes various bugs found in testing behavior developed
on top of the main change.
=> Allow payload serialization to be overridden

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
This change makes SDK parses more information when unmodeled exception comes in:
1. Always parse unknow error response body to structured data and mixin to JS Error
2. Always set `name` and `message` onto the JS Error
Parsing error response body is required because body stream will never be consumed 
otherwise. The stream will be around in memory for a whilre before they are flushed 
eventually, which would use a lot of resources.
fix: #86 
=> make best effort to infer unmodeled error message and name

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
=> Add a name property to error structures

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Refs https://github.com/aws/aws-sdk-js-v3/pull/740
update @aws-crypto/sha256-browser in codegen dependencies
=> chore: update @aws-crypto/sha256-browser

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
=> Use configurable operation path for RPC

smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/build.gradle.kts
Updates smithy-codegen-core dependency to 0.9.7 and uses new operation syntax to remove `Deprecated IDL syntax detected for operation definition` warnings
=> Bump smithy-codegen-core dep to 0.9.7

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/simple-service-with-condensible-shapes.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/simple-service-with-shape-conflict.smithy
When generating TypeScript shapes, attempt to first condense any matching shapes to eliminate duplicate generated shapes. Throws a CodegenException if shapes exist that cannot be condensed.
Fixes: #80
=> Remove duplicate shapes

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
This change fixes the returned type mismatch in newer TS version.
=> fix collectBody default return

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
Use LinkedHashMap to preserve existing order when generating models
=> Use LinkedHashMap to preserve order

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
Fixes: aws/aws-sdk-js-v3/issues/809
Convert whole seconds to milliseconds when creating Date from epoch timestamps
=> Fix whole seconds to milliseconds

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
This commit makes updates to align error deserialization with JS
conventions around the message and name properties. It also opens
the type signature to allow for additional properties on errors.
Partial of aws/aws-sdk-js-v3#763
=> Update to JS error standards

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
https://github.com/aws/aws-sdk-js-v3/issues/825
Current deserializer uses case-sensitive member local name for parser the headers. However, the header should be case-insensitive(low-cased) by default. 
Wrong(current):
```javascript
if (output.headers["ETag"] !== undefined) {
contents.ETag = output.headers["ETag"];
}
```
Right(fixed):
```javascript
if (output.headers["etag"] !== undefined) {
contents.ETag = output.headers["etag"];
}
```
This change fix the issue above.
=> fix: use lowercased header name in readHeaders

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
-----
From:
```ts
// Many of this:
return new __HttpRequest({
...context.endpoint,
protocol: "https",
method: "POST",
path: "/",
headers: headers,
body: body
});
```
To:
```ts
// Many of this:
return buildHttpRpcRequest(context, headers, "/", undefined, body);
// One of this:
const buildHttpRpcRequest = (
context: __SerdeContext,
headers: __HeaderBag,
path: string,
resolvedHostname: string | undefined,
body: any,
): __HttpRequest => {
const contents: any = {
...context.endpoint,
protocol: "https",
method: "POST",
path: path,
headers: headers,
};
if (resolvedHostname !== undefined) {
contents.hostname = resolvedHostname;
}
if (body !== undefined) { …
```
=> Update generated RPC code for DRYness

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Body should only be initialized, but not set to empty object.
Empty objects that do not get replaced with actual body content cause errors when sending requests.
Part of fix for https://github.com/aws/aws-sdk-js-v3/issues/838
=> Initialize body, but do not set to empty object

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/866
Add encode the labels before inserting them into the request path. 
Reference: [here](https://github.com/aws/aws-sdk-js-v3/blob/17e85a9a4021b4f26118853ae5a0c8d76f66e354/packages/protocol-rest/src/RestSerializer.ts#L188-L202)
=> URIencode label values

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IndexGeneratorTest.java
Resolves: aws/aws-sdk-js-v3/issues/847
Export all shapes from models/index.ts in root index.ts
=> Export models in index.ts

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
redo: https://github.com/awslabs/smithy-typescript/pull/121
=> fix uriencoding path with greedy label

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/LanguageTarget.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.rn.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
This PR is paired with https://github.com/aws/aws-sdk-js-v3/pull/895. 
=> Add ReactNative language target

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Bumps @aws-crypto to use alpha dependency
Part of fix for aws/aws-sdk-js-v3/issues/901
=> Bump @aws-crypto dependency

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenUtilsTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java
This commit adds support for serializing and deserializing String
shapes as the `LazyJsonString` when they are marked with the `@mediatype`
trait with the value of `"application/json"`.
=> Add serde support for application/json String

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
This allows RPC protocols, like `aws.query`, to set body contents as part of its requests when operations don't have input shapes:
```json
{
"com.a9.cloudsearch.config2013#ListDomainNames": {
"type": "operation",
"output": {
"target": "com.a9.cloudsearch.config2013#ListDomainNamesResponse"
},
"errors": [
{
"target": "com.a9.cloudsearch.config2013#BaseException"
}
],
"traits": {
"smithy.api#documentation": "<p>Lists all search domains owned by an account.</p>"
}
}
}
```
Generates:
```ts
const body = buildFormUrlencodedString({
Action: "ListDomainNames",
Version: "2013-01-01",
});
```
=> Allow RPC protocols to set the body without input

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Use extendedEncodeURI function added in aws/aws-sdk-js-v3/pull/915
=> Use extended URI encoding function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/851
* set errorCode to parsedBody.name in default case
* removes "UnknownError" assignment, as it's initialized on line 268
=> fix: set errorCode to parsedBody.code in default case

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Fixes aws/aws-sdk-js-v3/issues/918
Operations without document or payload bindings still need to have their bodies collected so that node process will exit promptly without waiting for the stream to close on its own.
=> Collect unused stream bodies

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
This commit updates the `SymbolVisitor`'s import strategy to use only
specific imports instead of a full package aliased import. It also
updates other instances that relied on the full import to specify
their own directly.
The import type for many has been updated to a `USE` style import to
support composed symbols for collection and map shapes.
-----
Codegen examples:
```ts
import {
LazyJsonString as __LazyJsonString,
SmithyException as __SmithyException,
isa as __isa,
} from "@aws-sdk/smithy-client";
export namespace AttributeValue {
export function isa(o: any): o is AttributeValue {
return __isa(o, "AttributeValue");
}
}
export interface ExpiredNextTokenException extends __SmithyException, $MetadataBearer {
name: "ExpiredNextTokenException";
$fault: "client";
Message?: string;
}
export …
```
=> Update smithy-client import strategy

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
This change adds codegen support for eventstream serde. If a member has event stream trait, it will generate specitial event serde functions on top of original ones. Specifically:
* Serializer: 
* event stream serializer:
```javascript
//TranscribeStreaming.serializeAws_restJson1_1StartStreamTranscriptionCommand
//...
if (input.AudioStream !== undefined) {
body =
context.eventStreamMarshaller.serialize(
input.AudioStream,
event => serializeAws_restJson1_1AudioStream_event(event, context)
);
}
//build request
```
* if a multi-event event stream, we generate a event dispatcher:
```javascript
const serializeAws_restJson1_1AudioStream_event = (
input: any,
context: __SerdeContext
): __Message => {
return AudioStream.visit(input, {
AudioEvent: value => …
```
=> support eventstream traits

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This PR reverts uri component encoding being handled during protocol serialization.  Instead, query encoding is performed in the individual handlers.
This change, with aws/aws-sdk-js-v3/pull/935, fixes https://github.com/aws/aws-sdk-js-v3/issues/930
=> Undo query encoding

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
* Fix the streaming member's shape from Uint8Array to Readable|ReadableStream|Blob
* For streaming members in command input, ease the restriction to allow
Uint8Array, Buffer and string
updated `PutObjectCommandInput`: 
```typescript
export type PutObjectCommandInput = Omit<PutObjectRequest, "Body"> & {
Body?: PutObjectRequest["Body"] | string | Uint8Array | Buffer;
};
```
Only command input that has streaming member is updated.
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/843
=> fix streaming members shape

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/output-structure.smithy
Contains the following fixes, each in their own commit for ease of review:
* Fix timestamp serde around TS string types
```ts
const labelValue: string = Math.round(input.memberEpochSeconds.getTime() / 1000).toString();
```
* Update parseFloat call to remove second param
```ts
contents.headerDouble = parseFloat(output.headers['x-double']);
```
* Add metadata to modeled error outputs
```ts
response = {
...await deserializeAws_restJson1_1ComplexErrorResponse(output, context),
$metadata: deserializeMetadata(output),
}
```
* Update output shapes being MetadataBearers 
This commit removes the MetadataBearer type for non-error output
shapes in the model. This makes them not require having a metadata
property when being reused as non-response shapes (batches, etc.)
Output shapes instead become …
=> Protocol codegen fixes via protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
* Fix a bug when streaming member shape is required:
before:
```typescript
export type UploadDocumentsCommandInput = Omit<UploadDocumentsRequest,"documents"> & {
documents?: UploadDocumentsRequest["documents"] | string | Uint8Array | Buffer;
};
```
now:
```typescript
export type UploadDocumentsCommandInput = Omit<UploadDocumentsRequest,"documents"> & {
documents: UploadDocumentsRequest["documents"] | string | Uint8Array | Buffer;
};
```
* Because command input and output shape is now possibly different to the ones exported from `models/index.ts`. So now SDK client uses the ones exported from commands to compose input/output type union, instead of those exported from `models/index.ts`. Although in most cases they should be the same types
Codegen: …
=> Fix streaming type types when they are required

README.md, smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen-test/smithy-build.json, smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-form-urlencoded-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-json-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-unknown-type-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts
This commit adds support for generating protocol tests based on the
`smithy.test#httpRequestTests` and `smithy.test#httpResponseTests`
traits. Any service that has these traits will have a file generated
in ./tests/functional named after the protocol that is being tested.
These generated tests use the `jest` library and its expect/fail
methods, along with custom mock handlers for testing the requests
and responses.
A custom node/shape visitor is needed to handle TS specific output
typing in the generated code. This handles properly generating Date
types, booleans, sets, and more.
Individual body comparators are included as stubs to be added when
the specific `bodyMediaType` they support are encountered. Some new
dependencies are added when handling query, form-urlencoded, or XML …
=> Add support for generating HTTP protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java
The current invalid dependency function throws error in client constructor. This will block RN users even they are not using event stream. After this fix, the invalid dependency function throws when event stream serde is called. 
=> fix eventstream dependency placeholder in reactnative

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.rn.ts.template
https://github.com/aws/aws-sdk-js-v3/issues/929
The `@aws-crypto/sha256-browser` package doesn't work properly in ReactNative. So we use replace it will pure JS hasher(`@aws-crypto/sha256-js`) instead. 
Codegen PR: https://github.com/aws/aws-sdk-js-v3/pull/998
=> Use @aws-crypto/sha256-js for hasher in RN

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1015
bump typescript to ~3.8.3
=> bump typescript to ~3.8.3

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/LanguageTarget.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/990
Rename .rn to .native
=> Rename .rn to .native

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/jest.config.js, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
The following is a collection of fixes, broken down to individual commits, to common protocol code generation discovered while running the AWS protocol tests.
* Add default jest config to packages
* Fix issue with reusing body stream
* Update compareParts methodology
* Update parseXmlBody for comparisons
* Resolve several timestamp serde issues
This commit fixes default formatting for timestamps in headers
and query strings, defaulting to the protocol's setting for label
serialization. It also fixes input serialization issues, most notably
around serializing HTTP_DATE formatted timestamps. These methods (and
therefore their class) are made public so that protocols interact
with the timestampFormat trait can use them.
* Fix naming issues in error deserialization
* Serialize deicmals with …
=> Update shared protocol/test codegen code

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
The following is a collection of fixes, broken down to individual commits, to protocol test code generation discovered while generating and running the AWS protocol tests.
* Update name and tests for cleanliness
* Fix typing issues via 'as any'
* Add idempotency autofilling
* Use new response param comparator
* Update response content validation methods
* Improve request body and payload testing
* Update response body validation handling
This commit adds a private CommandOutputNodeVisitor class to handle
writing target output bodies to match their TS specific types.
This handles properly generating Date types for numbers that are
Timestamp shapes, "undefined" for nulls, boolean values, Uint8Array
types for blobs, and error Message field standardization.
By submitting this pull request, I …
=> Update protocol test code generation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
The main commit in this PR provides request bodies for operations that have no request bindings whatsoever. An additional small commit has been added to enforce sorting of operations when generating tests.
=> Handle HTTP binding protocol requests with no HTTP bindings

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-binding-utils.ts
This commit updates the CommandOutputNodeVisitor to downcase any
keys in ObjectNode that represent HttpPrefixHeaders. It also fixes
an issue writing NullNode entries.
This commit fixes casing comparison issues related to fetch for HTTP
bindings of headers and prefix headers for both request and response.
It also includes a fix to more robustly validate headers before
serialization.
-----
=> Additional test and protocol codegen fixes

smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java
Also updates to use Smithy 0.9.9 packages.
=> Add setting to generate private packages

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
Previously, some default runtime config values are hard-coded into
templates. This change makes each one of the properties(e.g. requestHandler)
to be overridable by customizations from SDK side. If no customization
exists, the generator can still generate SDK with proper dependencies.
This change is added to support the customization of using WebSocket
requestHandler.
This change also brings in the capability that customization applied
later can override the runtime config values added in earlier
customization. This is necessary sometimes. For example, if customization
A adds runtime config: {x: X, y: Y}. x and y are deeply coupled that
they need to be in the same customization. If there's a single client
needs runtime config {x: X, y: Y-update}, we should be able to make
a new …
=> update runtime config customization to be fully overridable

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java
Because event stream signing is not a Smithy implementation. So make the doc clear about this.
=> Fix doc for event stream serde provider

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
Currently all the clientRuntimeCustomization can have a `destroy()` function. But the default configs in smithy client [doesn't have one](https://github.com/aws/aws-sdk-js-v3/blob/77386f6fac5fe2644f1b60a77050975c0327b6e0/packages/smithy-client/src/client.ts#L27). 
This change will make the service client call the `destroy()` from smithy client. By default the `SmithyClient.destroy()` is an empty function. But if the `requestHandler` in SmithyClient has a `destroy`, service client will call the function when callling the destroy on the service client. 
Related: https://github.com/aws/aws-sdk-js-v3/pull/1081
=> client destroy method will call SmithyClient destroy by default

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
Refs: https://github.com/awslabs/smithy-typescript/pull/25
The comment was updated for ErrorStructure in https://github.com/awslabs/smithy-typescript/pull/25, but got missed for NonErrorStructure
=> Update namespace comment for NonErrorStructure

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Replaces: #161 
Fixes: #158
CodeGen: https://github.com/aws/aws-sdk-js-v3/pull/1106
The SerDeContext contains endpoint config that used to be [a provider
function returning a promise of Endpoint](https://github.com/aws/aws-sdk-js-v3/blob/fde80bf7a538ebf8739c80254d5df529333d7093/packages/types/src/serde.ts#L9-L11),
and it is resolved in [serializer middleware](https://github.com/aws/aws-sdk-js-v3/blob/fde80bf7a538ebf8739c80254d5df529333d7093/packages/middleware-serde/src/serializerMiddleware.ts#L23-L26). It introduces mismatch
between SerDeContext type and the value, where the value contains
resolved endpoint but the type is a provider function returning Endpoint
promise. This change assumes the SerDeContext.endpoint is actually
a provider function and only resolve the promise when …
=> fix: resolve endpoint in command serializer

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
N/A
* Converts isa method to an arrow function
* Arrow functions are preferred over classic function expression because of their verbosity, and lexical binding
=> Convert isa method to an arrow function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGeneratorTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1126
Use Array shorthand - `Type[]` instead of `Array<Type>`
=> Use Array shorthand - Type[] instead of Array<Type>

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
This changle makes parseBody() function handles empty body. It is useful when testing or request hendler fakes response.
Related: https://github.com/aws/aws-sdk-js-v3/pull/1131
=> add default body value before collecting body stream

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/UnionGeneratorTest.java
Similar to https://github.com/awslabs/smithy-typescript/pull/163
* Converts visit method to an arrow function
* Arrow functions are preferred over classic function expression because of their verbosity, and lexical binding
=> Convert visit method to an arrow function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Refs: https://github.com/awslabs/smithy-typescript/pull/163
* Converts protocol functions method to an arrow function
* Arrow functions are preferred over classic function expression because of their verbosity, and lexical binding
=> Convert protocol functions to arrow functions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-binding-utils.ts
Similar to https://github.com/aws/aws-sdk-js-v3/pull/1145
Remove redundant return from collectBodyString and isSerializableHeaderValue
=> Remove redundant return from collectBodyString and isSerializableHeaderValue

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
We decided to use Array for SetShape in internal discussions for similar reasons to why Objects are used instead of Map:
* new Set needs to be created by calling `new Set()`, just like `new Map()`
* `setObj.has(value)` is similar to `objMap.get(key)`
Smithy specification for Set https://awslabs.github.io/smithy/spec/core.html#set
```console
Not all languages support set data structures with non-scalar values. Such languages SHOULD represent sets as a custom set data structure that can interpret value hash codes and equality. Alternatively, clients MAY store the values of a set data structure in a list and rely on the service to ensure uniqueness.
```
Use array for SetShape
By submitting this pull request, I confirm that you can use, …
=> Use array for SetShape

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Similar to https://github.com/awslabs/smithy-typescript/pull/175
Before
```javascript
const query: any = {
foo: "bar"
};
if (input.baz !== undefined) {
query["baz"] = input.baz;
}
if (input.maybeSet !== undefined) {
query["maybeSet"] = input.maybeSet;
}
```
After
```javascript
const query: any = {
foo: "bar",
...(input.baz !== undefined && { baz: input.baz }),
...(input.maybeSet !== undefined && { maybeSet: input.maybeSet })
};
```
=> Define query while declaring

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Solution encouraged from https://github.com/awslabs/smithy-typescript/pull/170
* Simple headers:
* Before:
```javascript
const headers: __HeaderBag = {};
headers["Content-Type"] = "application/x-amz-json-1.0";
headers["X-Amz-Target"] = "DynamoDB_20120810.DescribeEndpoints";
```
* After:
```javascript
const headers: __HeaderBag = {
"Content-Type": "application/x-amz-json-1.0",
"X-Amz-Target": "DynamoDB_20120810.DescribeEndpoints"
};
```
* headers with if statements:
* Before:
```javascript
const headers: any = {};
headers["Content-Type"] = "";
if (isSerializableHeaderValue(input.ACL)) {
headers["x-amz-acl"] = input.ACL!;
}
if (input.Metadata !== undefined) {
Object.keys(input.Metadata).forEach(suffix => {
headers["x-amz-meta-" + suffix] = …
```
=> Define headers while declaring

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Codegen PR: https://github.com/aws/aws-sdk-js-v3/pull/1175
It's from old preview client packages and will not be used. 
=> Remove smoke-test from package.json

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Related: https://github.com/aws/aws-sdk-js-v3/pull/1186
1. Merge `stream-collector-native` with `stream-collector-native`;
1. Move stream collectors into corresponding http handler;
1. Use the same `fetch-http-handler` for both RN and browsers.
See the linked PR's description for more context. 
=> refactor http request handlers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-list-with-sensitive-data.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-map-with-sensitive-data.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-list.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-map.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-member-pointing-to-list.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-member-pointing-to-map.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-member-pointing-to-structure.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-simple-shape.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-sensitive-structure.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-structure-with-sensitive-data.smithy
N/A
This PR covers all cases for filterSensitiveLogs
Testing done prior to code change on TypeScript playground:
* [Array](https://www.typescriptlang.org/play/?ssl=20&ssc=16&pln=20&pc=24#code/MYewdgzgLgBAygUQHJwJIBVUDUEH07oBKqSA4jALwwBEAVPXAKaQCWULAbo6mAGYgAnALYBDduHq1qAbgBQslmCiMBvEcEYxl0OFAEBXYFH0DNAb1kwY+iCoCCAgSICeALhgOnzgDwBVWwIAfHIAvvKKyqrqmv4qMBZWNipgIkKM7tACigDmclYADiIQEADuggAmGXo5ofIpaRCFGlqMOnqGxqbxljCMAB75grCgkLC8LAA2kUys7FwAMiDZlDAAFCAARgBW7tpQugZGJowAlJSBawlWMAB0d5tbADQ9iQGeLu4PN0kC7843onyq1iAhu4ymKhmEDYnEYi2yJx6IROtVk9VaTRiAW6Vn6gwEw3A0Bg4OmzGhczhSxW6227hBZwoF1WVysdxuD2e1xghWKZQElXgyDQmBw+CIJFISMRYVkI2JewOHWOAHk6S02odOpoqFcfn93ABtF447nWALo9zUH7ogCM1C5Zt5pQqVud-PK9sdVhC3tN3JtqXSNEDaQATA6TQUii6BW6Yx6I37fT0ALqyWXykATRg3CZLVaK9pH …
=> Add filterSensitiveLog method to Structure namespaces

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-insensitive-list.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-insensitive-map.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-insensitive-simple-shape.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-insensitive-structure.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-list-with-sensitive-member.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-map-with-sensitive-member.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-recursive-shapes.smithy
Follow-up to https://github.com/awslabs/smithy-typescript/pull/170
* Check for sensitive trait in Shape members
* CodeGen PR https://github.com/aws/aws-sdk-js-v3/pull/1213
=> Check for sensitive trait in Shape members

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java
As https://github.com/aws/aws-sdk-js-v3/pull/1216 lands, JS SDK has a eventstream serde package compatible with RN. So we need to remove the RN prohibition.
=> remove eventstream prohibition in reactnative

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/error-test-retryable-throttling.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/error-test-retryable.smithy
Follow-up to https://github.com/aws/aws-sdk-js-v3/pull/1222 to consume retryableTrait from model
* Add $retryable to Error is RetryableTrait is present
* Codegen PR at https://github.com/aws/aws-sdk-js-v3/pull/1237
=> Add $retryable to Error is RetryableTrait is present

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1409
Delete unnecessary commands remove-js and remove-map from package.json
=> Delete unnecessary commands remove-js and remove-map from package.json

README.md
N/A
Add Troubleshooting section in README with instructions to run `./gradlew --stop`
=> Add Troubleshooting section in README

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1410
Add build:cjs command to standardize scripts between clients and packages
=> Add build:cjs command

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDependencyTest.java
Codegen for fixing: https://github.com/aws/aws-sdk-js-v3/issues/1412
Add devDependency @aws-sdk/client-documentation-generator, which is required to be added as a devDependency to generate docs
=> Add devDependency @aws-sdk/client-documentation-generator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDependencyTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1416
tslib needs to be a dependency and not a devDependency https://www.npmjs.com/package/tslib
=> Remove devDependency tslib

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
N/A
Update dependencies to match that in aws-sdk-js-v3. This is required before updating clients with updated models.
In future, this needs to be updated every time a dependency is updated in aws-sdk-js-v3
Example client-accessanalyzer package.json for reference https://github.com/aws/aws-sdk-js-v3/blob/master/clients/client-accessanalyzer/package.json
=> Update dependencies to match that in aws-sdk-js-v3

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Internal issue JS-2014
Remove duplicate hostname when hasHostPrefix is true
=> Remove duplicate hostname when hasHostPrefix is true

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1456
Bump typescript to ~4.0.2
=> Bump typescript to ~4.0.2

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
The hostname prefix is not generated correctly. It results in serializer throwing when trying to add hostname prefix because  `(context.endpoint as any).hostname` returns `undefined`. The pull request fixes the bug
=> fix serializer throwing at adding host prefix

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
Internal JS-2036
Passes logger and filters to HandlerExecutionContext, which are going to be used by middleware-logger for logging
=> Pass logger and filters to HandlerExecutionContext

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/UnionGeneratorTest.java
Internal issue JS-1906
Removes __type and isa function.
As described in JS-1906, `__type` will only be added only for types that are or have subtypes or when inheritance is introduced.
=> Remove __type and isa function 

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
So that the protocol test can be run in environment without existing AWS configs
Related: https://github.com/aws/aws-sdk-js-v3/pull/1513
=> add required client configs to protocol test

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
https://github.com/aws/aws-sdk-js-v3/issues/1460
Related: https://github.com/aws/aws-sdk-js-v3/pull/1510
This change exports shapes in topological order, and chunk them into `models/models_0.ts`, `models/models_1.ts`, `models/models_2.ts`..., `models/models_x.ts`. A `models/index.ts` will re-export shapes from each chunks.
=> toposort models and chunk big model files

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
Per the SDK protocol requirement, members bound to host prefix must
be required. In JS SDK, required members are modeled as `string|undefined`.
It makes `resolvedHostname.replace(hostPrefix, input)` panic because
replace() doesn't allow `undefined`.
This change casts the type to `string` with `!`
=> cast host prefix member to be non-optional

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java
`TypescriptIntegration` supports `preprocessModel()` customization. However, it's never integrated with `CodegenVisitor`. This change fixes the issue.
=> Apply preprocessModel customization to the models

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
The serializer should throw when the member is not supplied, otherwise the constructed hostname is invalidate, and hard for users to figure out the root cause. Members bond to hostname prefix is always required, so it makes sense to throw when they are not provided.
=> Throw when host prefix input is not supplied

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/1560
Target ES2018 in TSConfig as we now support Node.js >=10.0.0
=> Target ES2018 in TSConfig

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Currently JS SDK treats 3XX response as successful but it isn't. JS SDK should
throw redirection responses as errors. Go SDK has the same behavior in [smithy-go](https://github.com/awslabs/smithy-go/blob/eef57dbcf0a0b771beb062916b8ace909ca7c9aa/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpBindingProtocolGenerator.java#L308).
https://github.com/aws/aws-sdk-js-v3/issues/1385
=> Deserialize 3XX response as exceptions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
Allow one level indexing of input tokens
```
"smithy.api#paginated": {
"inputToken": "EngineDefaults.Marker",
"outputToken": "EngineDefaults.Marker",
"items": "EngineDefaults.Parameters",
"pageSize": "MaxRecords"
}
```
=> fix: allow arbitrary path indexing on input, output tokens

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
Looks like not all services support the starting token being an empty string. Make it undefined.
=> fix: not all services support empty starting pagination token

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
v1.0.0 was released https://github.com/aws/aws-sdk-js-crypto-helpers/issues/175
Update @aws-crypto/* dependencies to 1.0.0
=> Update @aws-crypto/* dependencies to 1.0.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1489
log clientName and commandName in resolveMiddleware.
The clientName and commandName is passed in handlerExecutionContext to be used in middleware stack, if required.
<details>
<summary>Code</summary>
```js
const { DynamoDB } = require("/home/trivikr/workspace/aws-sdk-js-v3/clients/client-dynamodb");
(async () => {
const region = "us-west-2";
const logger = { info: console.log };
const client = new DynamoDB({ region, logger });
await client.listTables({ Limit: 1 });
})();
```
</details>
<details>
<summary>Output</summary>
```console
{ clientName: 'DynamoDBClient', commandName: 'ListTablesCommand' }
{ input: { Limit: 1 } }
{
output: {
LastEvaluatedTableName: 'CUSTOMER_LIST',
TableNames: …
```
=> feat: log clientName and commandName

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Similar to: https://github.com/aws/aws-sdk-js-v3/pull/1654
Based off: https://github.com/aws/aws-sdk-js-v3/issues/1649
Moves @aws-sdk/types into devDependencies of clients
=> fix(package.json): migrate @aws-sdk/types into devDependencies for codegen

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
https://github.com/aws/aws-sdk-js-v3/issues/1665
Args are incorrectly passed to the clientCommand constructor instead of the send operation. 
=> fix: pass args to send operation

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1695
make handlerOptions optional in RequestHandler
=> chore(protocol-tests): make handlerOptions optional

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1760
import SENSITIVE_STRING only when used
=> fix: import SENSITIVE_STRING only when used

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1782
use typeof inputTokenName as token type instead of string
=> fix: use typeof inputTokenName as token type instead of string

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
Current default user agent string is AWS specific. So the customization
is moved to AWS JS SDK.
=> remove AWS-specfic default user agent

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1785
Remove logging of clientName and commandName from Command. It's now logger in loggerMiddleware.
=> Remove logging of clientName and commandName from Command

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1683
use LinkedHashSet to retain structure members' iteration order.
=> chore: use LinkedHashSet for structure members

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1868
Document deprecation in comments for shapes
**Shape: Lambda invokeAsync**
<details>
<summary>without deprecated tag</summary>
</details>
<details>
<summary>with deprecated tag</summary>
</details>
**Shape: Lambda InvokeAsyncCommand**
<details>
<summary>without deprecated tag</summary>
</details>
<details>
<summary>with deprecated tag</summary>
</details>
**Member: WorkDocs DescribeUsersResponse TotalNumberOfUsers**
<details>
<summary>without deprecated tag</summary>
</details>
<details>
<summary>with deprecated tag</summary>
</details>
=> Document deprecation in comments for shapes and members

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/NonModularServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java
Follow-up to https://github.com/awslabs/smithy-typescript/pull/242
Regular expression used for search `model.getKnowledge\(([^\.]*).class\)` and replaced with `$1.of(model)`
=> Remove calls to deprecated model.getKnowledge

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java
When sending the same command multiple times, resolveMiddleware()
will be called many times. So adding serde middleware will throw
error because they are already added into stack. This change
prevents adding the serde middleware repeatedly.
Alternative is moving command middleware to the command constructor,
just like in client(that's why client doesn't have the problem). But
the command middleware also have depdency over client configs
supplied from resolveMiddleware(). So serde middleware and
customizations must live here.
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1864
=> fix: stop adding command middleware repeatedly

.github/workflows/ci.yml, CONTRIBUTING.md
This PR updates references to the branch so that `main` can be used the default branch on this repository.
=> Refer to main branch

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
https://github.com/aws/aws-sdk-js-v3/issues/1842
https://github.com/aws/aws-sdk-js-v3/pull/1902
Packages that depend on @aws-sdk/types should explicitly call out that dependency so that downstream consumers get type support out of the box and do not have to install their own version of @aws-sdk/types . This PR should do that for all packages that depend on @aws-sdk/types in AWS sdk v3.
=> fix: export @aws-sdk/types as an explicit dependency

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Update the TypeScript dependencies version to GA'd version 3.0.0
=> update ts dependencies

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1867, https://github.com/aws/aws-sdk-js-v3/issues/1900
Related: https://github.com/aws/aws-sdk-js-v3/issues/1903
Both `@aws-sdk/url-parser-node` and `@aws-sdk/url-parser-browser` use WHATWG `URL()`
to parse the url. In fact their code are identical. So they are deprecated and
replaced by `@aws-sdk/url-parser`.
However, `URL()` is not supported in React Native. So we need to use `parse()`
from "url" package. `@aws-sdk/url-parser-native` is used in React Native runtime.
=> merge url-parser-node and url-parser-browser; add url-parser-native

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java
This reverts commit c57cca31d2216849ef123d19b86ea0fab6eb12d4.
Solves: https://github.com/aws/aws-sdk-js-v3/issues/1935
Related to: https://github.com/aws/aws-sdk-js-v3/pull/1964
If a command instance is used by a different client instance, the
command still consumes the configuration of the previous client
interface. This issue is resolved by allowing adding middleware
to the stack without throwing error. So #259 is no longer needed.
=> Revert "fix: stop adding serde middleware repeatedly (#259)"

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-form-urlencoded-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-json-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-octet-stream-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-text-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts
This commit updates the request body comparison generation for
protocol tests to safely handle having multiple `bodyMediaType`
settings in the same suite of protocol tests. It also updates the
methodology for comparing blob bodies to not be a special case in
the generator, as they can have alternate media types.
=> Update protocol test request body comparison

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Fixes CI failures in aws-sdk-js-v3 which started with https://github.com/aws/aws-sdk-js-v3/actions/runs/590870041
Do not check for labels in empty input while writing hostPrefix.
Verified that gradle build is successful in aws-sdk-js-v3 after the change from this PR is published to local maven.
```console
$ pwd
/home/trivikr/workspace/smithy-typescript
$ ./gradlew clean publishToMavenLoca
...
...
BUILD SUCCESSFUL in 3s
12 actionable tasks: 11 executed, 1 up-to-date
```
```console
$ pwd
/home/trivikr/workspace/aws-sdk-js-v3/codegen
$ ./gradlew clean smithy-aws-typescript-codegen:build protocol-test-codegen:build -Plog-tests
...
...
BUILD SUCCESSFUL in 15s
13 actionable tasks: 13 executed
```
By submitting this pull request, I confirm that …
=> Do not check for labels in empty input while writing hostPrefix

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Update TS dependencies to current latest. Previously we use `3.0.0` as a place holder but some newer dependencies like `@aws-sdk/url-parser` doesn't have this version. Users building their generated client will see error that specified version doesn't exist. This is an one-off effort to update the dependencies. 
In longer term we need to implement GitHub Actions to make these versions always latest.
=> update TypeScript dependencies version

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
This adds test generation for ssdk request deserialization. For example:
```typescript
/**
* Mixes constant and variable query string parameters
*/
it("RestJsonConstantAndVariableQueryStringMissingOneValue:ServerRequest", async () => {
let testFunction = jest.fn();
testFunction.mockReturnValue({});
const testService: Partial<RestJsonService> = {
ConstantAndVariableQueryString: testFunction as __Operation<
ConstantAndVariableQueryStringCommandInput,
ConstantAndVariableQueryStringCommandOutput
>,
};
const handler = getRestJsonServiceHandler(testService as RestJsonService);
const request = new HttpRequest({
method: "GET",
hostname: "foo.example.com",
path: "/ConstantAndVariableQueryString",
query: {
foo: "bar",
baz: "bam",
},
headers: {},
body: Readable.from([""]), …
```
=> Generate ssdk request protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
N/A
The Set `parents` was added to avoid StackOverflow Error occurring due to circular dependencies in recursion in PR https://github.com/awslabs/smithy-typescript/pull/181
To check for recursions, the value needs to be populated only for Structure shapes.
=> Check for only structure shapes for circular dependency

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
refs: https://github.com/aws/aws-sdk-js-v3/pull/2102
Pinning fast-xml-parser to v3.17.4 as the project switched to modified MIT License in >=v3.17.5 in https://github.com/NaturalIntelligence/fast-xml-parser/commit/5d4e95188c4d3bf57ee1b2f5489c017ca3be627c
=> Pin fast-xml-parser to v3.17.4

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
Refactors the server codegen to use a server-specific symbol provider and its symbols where possible.
You can see an example of what the new codegen looks like (in server-only mode) [here](https://github.com/adamthom-amzn/smithy-typescript-ssdk-demo/commit/21f905dfae52aa39fe0a3d920bba2baa06ce50f2).
=> Introduce a server-specific symbol provider.

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
Instead of using a Record, just do it Java-style with a factory function that can spit out the correctly-typed OperationSerializer.
You can see what the diff for the generated code is here: https://github.com/adamthom-amzn/smithy-typescript-ssdk-demo/commit/c6efa24117dd7e0066bf70a336b859f82023e381
=> Get rid of needing to cast OperationSerializers.

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java
This updates the server protocol test gen to use the server symbol provider. It also splits up the server / client "command" generators because having them all in one was causing client code to be generated in the server files. Lastly, I changed the folder for the server operation types to "operation" since typescript special cases "types" and that was causing generation issues.
=> Use server symbol provider in protocol test gen

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2088
Add ts-jest as a devDependency
=> Add ts-jest as a devDependency

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
The fast-xml-parser was pinned to v3.17.4 as the project switched to modified MIT License in >=3.17.5 in https://github.com/NaturalIntelligence/fast-xml-parser/commit/5d4e95188c4d3bf57ee1b2f5489c017ca3be627c
The license is now updated to MIT in [3.19.0](https://github.com/NaturalIntelligence/fast-xml-parser/blob/bbfecf97821c62685555c21a09e4071690899fef/package.json#L70)
Pin fast-xml-parser dependency to 3.19.0
=> Pin fast-xml-parser dependency to 3.19.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-octet-stream-stub.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-unknown-type-stub.ts
This adds protocol test generation for server responses, excluding errors. At time of writing 5 protocol tests fail due to differences in how servers and clients are expected to serialize empty bodies.
As part of that, this updates the compare octet and compare unknown protocol test test helpers to specifically take an Encoder rather than a client config.
This depends on #284 , ~~the first two commits are from that PR.~~
=> Add ssdk response tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
This add exception handling to the SSDK. In doing so I've re-arranged a bunch of things to be a bit more split up. Notably the `getServiceHandler` function has been moved into the service's file and each `OperationSerializer` has been moved into that operation's file.
In addition to re-organizing, this depends on two new additions to the `OperationSerializer`, `isOperationError` and `serializeError`.
```typescript
export interface OperationSerializer<T, K extends keyof T, E extends SmithyException> {
serialize(input: OperationOutput<T[K]>, ctx: Omit<SerdeContext, 'endpoint'>): Promise<HttpResponse>
deserialize(input: HttpRequest, ctx: SerdeContext): Promise<OperationInput<T[K]>>
isOperationError(error: any): error is E
serializeError(error: E, ctx: Omit<SerdeContext, 'endpoint'>): …
```
=> ssdk modeled exception handling

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java
This updates the http protocol test generator to include error tests. A generated test looks like:
```typescript
it("RestJsonInvalidGreetingError:ServerErrorResponse", async () => {
class TestService implements Partial<RestJsonService> {
GreetingWithErrors(input: any, request: HttpRequest): GreetingWithErrorsServerOutput {
const response = {
Message: "Hi",
} as any;
const error: InvalidGreeting = {
...response,
name: "InvalidGreeting",
$fault: "client",
$metadata: {},
};
throw error;
}
}
const service: any = new TestService();
const testMux = new httpbinding.HttpBindingMux<"RestJson", keyof RestJsonService>([
new httpbinding.UriSpec<"RestJson", "GreetingWithErrors">("POST", [], [], {
service: "RestJson",
operation: "GreetingWithErrors",
}),
]);
class TestSerializer extends …
```
=> Generate ssdk error tests

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/jest.config.js
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1618
Creates jest.config.js for clients instead of extending global config
=> fix: create jest.config.js for clients

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/FrameworkErrorModel.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/framework-errors.smithy
The most controversial part of this, I expect, will be the hand-built static model for these that I use to reuse the code generators. I wonder if I should replace the context's `SymbolProvider` as well, in the event one of the error serialization implementations tries to do a symbol lookup. I didn't go to those lengths in this review because I'm unsure framework errors will ever be much more than a name, a status code and a message.
In the future, if we allow customization of the namespace of the framework exceptions for backwards compatibility with existing services, the static model will have to turn into a model factory of some sort.
You can take a look at the generation changes here: https://github.com/adamthom-amzn/smithy-typescript-ssdk-demo/commit/503b7ae1b …
=> Support for framework exceptions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/EnumGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IndexGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/ServiceGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/UnionGeneratorTest.java
Updates SymbolVisitor to use service renames added in Smithy 1.7.0: https://github.com/awslabs/smithy/pull/734
Removes shape condensing in CodegenVisitor.  Since services must rename conflicting shapes, it is no longer necessary to try to condense these shapes during codegen.
=> Use service renames

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
This updates the ssdk protocol test generation to use promises so they work with recent updates
=> Adjust ssdk protocol tests to use promises

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1893
Set trimValues=false while calling fast-xml-parser
=> Trim values in parsed xml only if result is empty

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
Resolves: https://github.com/aws/aws-sdk-js-v3/issues/2105
Since the `destroy` is inherited from the underlying Node.js API [agent.destroy()](https://nodejs.org/api/http.html#http_agent_destroy), and it doesn't actually destroy and disable the agent for the future use, we will keep the `destroy()` method name in V3 SDK. This change adds documentation to clarify the confusion.
=> docs: add documentation for destroy method

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This will unblock the LaxRunTimeV2's new bi-directional streaming `StartConversation()` operation.
=> fix bug when generating event stream events serializer

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerErrorGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
It's really annoying to throw objects that have a bunch of fixed values. This turns:
```
const e: NoSuchResource = {
name: "NoSuchResource",
$fault: "client",
resourceType: "Venue",
$metadata: {}
};
throw e;
```
into
```
throw new NoSuchResourceError({resourceType: "Venue"});
```
=> Add generated error types for convenience

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/issues/2217
Codegen code: https://github.com/aws/aws-sdk-js-v3/issues/2217
Runs downlevel-dts in prepublishOnly step
=> fix: run downlevel-dts in prepublishOnly step

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPluginTest.java
Currently the generated client uses resolve functions to convert input
symbol type to a resolved symbol type. It only take 1 input parameter which
is the resolved symbol type returned from previous resolve function. In
some cases, we need to supply more parameters to the resolve functions,
like service client constructor, or specific command constructors.
For example, to solve the circular dependency issue of STSClient ->
credential providers -> STSClient, we need to supply the constructor
of STSclient so the credential provider can work without circular
dependency.
As a result, we can generate this STS customization:
```javascript
let _config_4 = resolveHostHeaderConfig(_config_3);
let _config_5 = resolveStsAuthConfig(_config_4, STSClient);
let _config_6 = …
```
=> support additional resolve function parameters

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2229
Removes @aws-sdk/url-parser-native in favor of react-native-url-polyfill
=> Remove @aws-sdk/url-parser-native in favor of react-native-url-polyfill

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Follow-up to https://github.com/awslabs/smithy-typescript/pull/257
* Regular expression used for search: `context.getModel\(\)\.getKnowledge\(([^\.]*).class\)` replaced with `$1.of(context.getModel())`
* Verified that there are no more `getKnowledge` calls
=> Remove calls to deprecated context.getModel().getKnowledge

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
N/A
The `target instanceof StringShape` check is not required in `isNativeSimpleType` as it's already done in `getInputValue`.
The private method `isNativeSimpleType` can be removed as it's called only from `getInputValue` and checks for Boolean/Integer
=> Replace isNativeSimpleType with Boolean/Number check

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
This lets service developers choose between a single lambda function per
operation, or one lambda function that handles all operations, depending on
their preferences.
=> Generate per-operation ServiceHandlers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java
This improves usability of API reference because all available parameters are now shown on same page
See https://github.com/aws/aws-sdk-js-v3/pull/2270 for more details.
=> generate interface for client input and resolved config

smithy-typescript-ssdk-libs/server-common/src/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
These are basic, initial implementations of the constraints specified in the
Smithy documentation (minus required, which is going to be validated while
walking the members of a structure, and not on the values of a given member).
=> Add validator implementations

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptServerCodegenPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.build.SmithyBuildPlugin
This splits up the server code generation to be gated behind a separate plugin. This lets us generate separate packages for each while still being able to generate both a client and ssdk in a single projection.
=> Split server codegen out into a separate plugin

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java
Remove extra line of model exports. The removed export is duplicated with:
https://github.com/awslabs/smithy-typescript/blob/4bb9ffb9e4efd9ff9abba06155911c087ccfbb92/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java#L60-L61
=> remove extra model export line

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
=> Remove unnecessary writer param

.gitignore, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-integ-tests/codegen/build.gradle, smithy-typescript-integ-tests/codegen/model/validation.smithy, smithy-typescript-integ-tests/codegen/smithy-build.json, smithy-typescript-integ-tests/jest.config.js, smithy-typescript-integ-tests/package.json, smithy-typescript-integ-tests/src/length.spec.ts, smithy-typescript-integ-tests/src/nested.spec.ts, smithy-typescript-integ-tests/tsconfig.json, smithy-typescript-ssdk-libs/server-common/src/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts, smithy-typescript-ssdk-libs/tsconfig.json
This can be broken up if desired, of course.
This adds:
- TypeScript implementations of validators for each constraint trait
- Generation of low-level validation methods for every modeled type when the SSDK is enabled.
-- I still don't know how to generate paths to members of sets, so I've punted on the path stuff in the design for now.
- An integ test subpackage that generates TS code from a model and then runs tests against it. It works, but is not hooked up to the main build of smithy-typescript.
=> Validation generation for SSDK

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Related to https://github.com/aws/aws-sdk-js-v3/pull/2349
With the v3 change above, SDK will create a JS error wrapper for anything not an error thrown from the SDK. This change makes the [`RequestSerializationTestHandler`](https://github.com/awslabs/smithy-typescript/blob/5ec6906aa41fc4679793546608f0f5ad97774884/smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts#L18) to throw a JS error instead of an object. So the SDK won't apply the JS error wrapper to it.
/cc @trivikr 
=> fix(protocol-tests): ser test handler should throw error not object

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This updates the interfaces for rest services to differentiate when an operation's input vs output vs error is being serialized / deserialized. This is necessary because there can be subtly different rules in each case.
Right now this is pretty ugly so I put it up as a draft. The major alternative I am considering is to instead have explicit methods for each case, e.g:
```java
protected abstract void serializeInputDocumentBody(
GenerationContext context,
OperationShape operation,
List<HttpBinding> documentBindings
);
protected abstract void serializeOutputDocumentBody(
GenerationContext context,
OperationShape operation,
List<HttpBinding> documentBindings
);
protected abstract void serializeErrorDocumentBody(
GenerationContext context,
OperationShape operation,
StructureShape error, …
```
=> Update serde interfaces to differentiate in/out

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Update TypeScriptDependency versions to 3.15.0
=> Update TypeScriptDependency versions to 3.15.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
This change annotates the config entries that only required by internal implementation as `@internal`. The generated API reference will strip them too. This is to inform the users not to set some values in the clients that could potentially break the SDK.
=> strip internal API, endpoint and test files from API reference

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-integ-tests/codegen/model/validation.smithy
This builds on #334 so for now only look at the last commit. This is in draft mode because I don't have a solution just yet.
Basically the problem is that recursive structures fail to validate at runtime. You get an error like this:
```
FAIL  src/nested.spec.ts
● Test suite failed to run
TypeError: Cannot read property 'validate' of undefined
274 |     member: new __CompositeStructureValidator<RecursiveStructureTwo>(
275 |       new __NoOpValidator(),
> 276 |       RecursiveStructureTwo.validate,
|                             ^
277 |     ),
278 |   };
279 |   export const validate = (obj: RecursiveStructureOne): __ValidationFailure[] => {
at codegen/build/smithyprojections/codegen/ts-server/typescript-ssdk-codegen/models/models_0.ts:276:29
at Object.<anonymous> …
```
=> Fix recursive structure validation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPluginTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/2211
Similar to: https://github.com/awslabs/smithy-typescript/pull/302
Currently the generated command calls additional runtime plugins, but
it only takes 1 parameter. To support endpoint discovery, we have to
pass more parameters which are specific to commands as follows:
```js
this.middlewareStack.use(
getEndpointDiscoveryOptionalPlugin(configuration, {
clientStack,
options,
})
);
```
In the above example, the clientStack and options passed to the plugin
are used for calling endpoint discovery command.
=> Support additional plugin function parameters

build.gradle.kts, smithy-typescript-integ-tests/codegen/build.gradle
This updates the java group name to `software.amazon.smithy.typescript` so that publishing can be isolated from base smithy.
=> Update java group name

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2436
bump typescript to ~4.3.2
=> chore(deps-dev): bump typescript to ~4.3.2

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java
This is a kinda-ugly middle ground, where we don't have the clean code
of instantiating a validator every time we need it, and we don't have the ideal
performance of instantiating them when the namespace is defined.
Here's what the recursive validators look like now:
```typescript
export interface RecursiveStructureOne {
member?: RecursiveStructureTwo;
}
export namespace RecursiveStructureOne {
/**
* @internal
*/
export const filterSensitiveLog = (obj: RecursiveStructureOne): any => ({
...obj,
})
const memberValidators : {
member?: __CompositeStructureValidator<RecursiveStructureTwo>,
} = {};
export const validate = (obj: RecursiveStructureOne): __ValidationFailure[] => {
function getMemberValidator<T extends keyof typeof memberValidators>(member: T): …
```
=> Don't recreate validators every time

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-integ-tests/.eslintrc.js, smithy-typescript-integ-tests/codegen/build.gradle, smithy-typescript-integ-tests/codegen/custom_validation/custom_validation.smithy, smithy-typescript-integ-tests/codegen/smithy-build.json, smithy-typescript-integ-tests/codegen/validation/validation.smithy, smithy-typescript-integ-tests/package.json, smithy-typescript-integ-tests/prettier.config.js, smithy-typescript-integ-tests/src/custom_validation.spec.ts, smithy-typescript-integ-tests/src/default_validation.spec.ts, smithy-typescript-integ-tests/src/enum.spec.ts, smithy-typescript-integ-tests/src/length.spec.ts, smithy-typescript-integ-tests/src/nested.spec.ts, smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
This adds input validation to the SSDKs, meaning that constraints specified in the model will be applied to inputs after deserialization.
Unlike some other frameworks of note, validation is opt-out, and not opt-in. The service developer, in order to ignore invalid input, will need to supply code that does so explicitly.
To use default validation, service authors must add `smithy.framework#ValidationException` to every operation. It will return these exceptions automatically when inputs fall outside of bounds.  An example output:
```json
{
"fieldList": [
{
"message": "Value Canopy Club@ at '/name' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[\\p{L}\\p{N}][\\p{L}\\p{N} ]+[\\p{L}\\p{N}]$",
"path": "/name"
},
{
"message": "Value -750 at '/capacity' failed to …
```
=> Input validation in SSDKs

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Resolves https://github.com/aws/aws-sdk-js-v3/issues/2021
When status code trait and the payload trait exists at the same time, the codegen of status code trait was omitted because the `return` statement. This change fixes the bug.
=> fix: parse status code bindings when payload binding exists

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-integ-tests/codegen/validation/validation.smithy, smithy-typescript-integ-tests/src/default_validation.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
Unfortunately StructuredMemberWriter was in a pretty bad place so I did a bigger refactor than I otherwise would for a change like this.
Essentially, it makes people nervous if they type a password or something else sensitive into a field and they see the value for that field echoed back to them in the message.
I originally thought about pushing the concept of sensitivity into every validator, but that was a big, messy change and it required each validator to check the sensitive trait. I settled on a second approach: wrap each sensitive member validator in a decorating validator that will set the failure value to null, and make our message generation treat null failure values as values that should be omitted. Null seems like a safe sentinel value to use here as …
=> Sensitive member validation

smithy-typescript-ssdk-libs/server-common/src/validation/index.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts
This sets an upper bound on how large of a validation error message we will
generate. It also adds some tests for message generation and fixes some minor
formatting bugs.
=> Do not generate very large validation errors

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-integ-tests/src/custom_validation.spec.ts, smithy-typescript-integ-tests/src/default_validation.spec.ts, smithy-typescript-ssdk-libs/server-common/src/index.ts
Service authors will want to pass metadata from the originating event through to their business logic. This will likely come from APIGateway metadata, especially metadata related to authentication and authorization. In particular, the calling user, or metadata attached by the custom Lambda authorizer are frequently referenced in service implementations.
Instead of coming up with some idea of context, or potentially coupling ourselves to the way APIGateway thinks about context, this just lets service authors define their own context type and pass it through the system.
=> Custom contexts for SSDK handlers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
This adds the ability to filter certain test cases. Reasons for doing this might include wanting to skip tests for a feature not yet implemented or wanting to skip a test whose asserted http request is only one of several valid options.
smithy-go has [something similar](https://github.com/aws/smithy-go/blob/main/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/integration/HttpProtocolUnitTestGenerator.java#L761), but rather than having a functional interface they have a locked down builder where you must be very explicit on what you want to skip. My motivation for going with the functional interface instead was to address complexity around generating for input/output/error and to allow for more easily skipping based on things in the settings (such as client vs …
=> Add ability to filter tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
This updates the protocol test generator to properly handle generating non-numeric float values. It doesn't actually update any of the protocol support.
See: https://github.com/awslabs/smithy/pull/828
=> Generate non-numeric floats in protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddChecksumRequiredDependency.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
SDK will apply middleware to inject content-md5 header for operations with `httpChecksumRequired` trait. Streaming payload is supported only if the stream is a file-system stream.
=> feat: support httpChecksumRequired trait

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
Streaming blob member inputs and design-time media types need special consideration during code generation, and the protocol tests were not accounting for the need for a validation customizer. Also, we weren't correctly generating `validate` for empty structures.
This does not impact SDK generation. Output of `git status` after `yarn generate-clients`:
```
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
(use "git push" to publish your local commits)
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   protocol_tests/aws-query/tests/functional/awsquery.spec.ts
```
And that diff has the expected content
```
diff --git …
```
=> [SSDK] Fix validation generation and protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This updates boolean parsing to be more strict. See https://github.com/aws/aws-sdk-js-v3/pull/2514 for the other half of this.
=> Strictly parse booleans in http bindings

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPluginTest.java
Fixes: https://github.com/awslabs/smithy-typescript/issues/352
This is a requirement for advanced use cases of Endpoint Discovery logic.
Currently, only Symbols and strings are generated for parameters. In future,
boolean and Map<String, String> support would be added.
=> Enable passing dynamic parameters to RuntimeClientPlugin functions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java
Follow-up to https://github.com/awslabs/smithy-typescript/pull/353
Accept boolean parameters in FunctionParametersList
This change allows passing `isDiscoveryEndpointRequired` boolean to function parameters.
=> Accept boolean parameters in FunctionParameterList

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java
This adds expectations for the default member deserialization so that an error will be thrown if the type being deserialized isn't correct.
See https://github.com/aws/aws-sdk-js-v3/pull/2515 for the other half of this.
=> Add expectations for default member deser

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2537
Rename prepublishOnly to downlevel-dts
=> Rename prepublishOnly to downlevel-dts

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This decodes potentially-encoded values as early as possible within the
deserialization process so that no downstream deserializer needs to reckon with
encoding.
It also enforces that we don't accept multiple values for query strings that are modeled as single values.
=> Fix deserialization of paths and query params for servers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Endpoints can have paths (notable example: API Gateway REST APIs without a
custom domain name), and serialization of REST-JSON requests was ignoring
these paths even though it's available from the endpoint provider.
Tested this locally against a APIGateway REST API with SigV4 that was broken without it.
This will also impact JS client generation for every REST-JSON service. We have a couple such changes out right now, was going to submit a regeneration PR when all of those land.
=> Fix serialization of REST-JSON requests when the endpoint has a path

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-ssdk-libs/server-apigateway/package.json, smithy-typescript-ssdk-libs/server-common/package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2580
Prefix `dist/` for typesVersions TS<4
=> Prefix `dist/` for typesVersions TS<4

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/reserved-words-members.txt
This prevents a member from being called `__proto__` in an effort to avoid issues with prototype pollution. One would hope that things would break long before it got to that point, but we should still be extra cautious.
Basically the concern is that we'd generate a type like:
```typescript
interface Example {
__proto__: SmithyDocument
}
```
And then when we get to deserialization we'd do something like:
```typescript
contents.__proto__ = {'pwned': true}
```
There is no associated PR to aws-sdk-js-v3 because no AWS service has a member called `__proto__`. 
=> Avoid messing with prototypes

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This updates SSDK generation so that content-length is properly calculated. The existing functionality for clients couldn't be re-used because it is designed to function as a middleware that runs just before the request is sent. That makes sense for the client, because a middleware could be modifying the body. But since the SSDK doesn't have middleware, we just embed it directly.
Related PR that makes associated tests run once more (though they'll fail until this is merged): https://github.com/aws/aws-sdk-js-v3/pull/2599
=> Calculate content-length for SSDKs

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Related to https://github.com/aws/aws-sdk-js-v3/pull/2601.
Update the tslib version
=> chore: bump tslib to 2.3.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
smithy-aws-typescript-codegen bundles a properties file that has the version of
every client and library that the JS SDK vends. This essentially ties that set
of versions to the published version of the smithy-aws-typescript-codegen
package. Instead of hardcoding specific versions of AWS clients and libraries,
this change parses that file if smithy-aws-typescript-codegen is also on the
classpath, so that we can use compatible versions of these packages when we
generate package.json. If smithy-aws-typescript-codegen is not on the classpath
we fall back to "latest" for these packages.
I tested this by generating a white-label client locally with this change and the latest version of smithy-aws-typescript-codegen. My package.json file had the correct version of …
=> Fix dependency versioning of AWS-vended packages

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddChecksumRequiredDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
Related to https://github.com/aws/aws-sdk-js-v3/pull/2574
See: https://github.com/aws/aws-sdk-js-v3/pull/2574
This change makes runtime default configs as a function instead of constant. As a result, different client instance won't share the same runtime config (e.g. HTTP handlers). This change also uses inline nullish coalescing in replace of fully loaded default configuration. This change makes sure the SDK won't load default value/provider at all when corresponding custom config is supplied.
=> change runtime config from constant to provider functions

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2619
Call emitWarningIfUnsupportedVersion from getRuntimeConfig
=> Call emitWarningIfUnsupportedVersion from getRuntimeConfig

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/malformed-request-test-regex-json-stub.ts
@httpMalformedRequestTests allow server implementations to generate tests
that exercise how the implementation deals with requests that are rejected
before they reach the customer's business logic. See
https://github.com/awslabs/smithy/pull/871 for more information.
This will not succeed build checks until https://github.com/awslabs/smithy/pull/871 is committed and released.
=> Add a generator for @httpMalformedRequestTests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/framework-errors.smithy, smithy-typescript-ssdk-libs/server-common/src/errors.ts
This updates the SSDK to check the content-type and accept headers.
Both accept and content-type headers may be omitted in any case.
If content-type is set and the operation has a modeled content-type,
the content-type sent is validated against what is modeled. If the
operation doesn't have a modeled content-type, any value is rejected.
If the content-type is rejected, a 415 will be returned.
Accept validation works in a similar way, though it looks at the
modeled output type and a 406 will be returned in the case of a
rejection.
Opening as a draft because I'd like to wait for the malformed request headers prs to land so I can do some of those.
=> Handle content-type and accept in ssdk

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java
This updates number parsing to be more strict. It also updates the expectation methods used for numbers to be more specific.
This relies on: https://github.com/aws/aws-sdk-js-v3/pull/2662
=> Update float/int parsing and expectations

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This updates any usage of an operation name to go through the symbol provider. This avoids issues where the operation name's casing differs from that of the symbol.
Note: this has no impact on client generation, which already exclusively uses the symbol provider name.
=> Use operation symbol name consistently

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.native.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.shared.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
This is an alternate solution to https://github.com/awslabs/smithy-typescript/pull/391 that works for generic clients too.
Using default value of `{}` assumed that client configs have no
required properties, which may not be true for generic non-AWS clients
where endpoint may be required.
Using `?.` operator for cases where `config` may be null/undefined.
=> fix: use optional chaining while processing runtime config

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java
This updates codegen to used sized number parsing to assert that numbers are in the range we expect.
This is associated with: https://github.com/aws/aws-sdk-js-v3/pull/2710
=> Use sized number parsing in codegen

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
If a restJson1 protocol request or response is a structure (as opposed to being
a bound payload), it must be a non-null JSON object. If it's a payload bound to
a union or structure, it must be a JSON object. Previously, body parsing would
take any output from JSON.parse and attempt to pull members off of the result
by name, even if JSON.parse returned a non-object type.
This depends on https://github.com/aws/aws-sdk-js-v3/pull/2713 - client changes are demo'd on my fork here: https://github.com/adamthom-amzn/aws-sdk-js-v3/pull/22 and protocol tests pass.
=> Parse request and response payloads strictly

smithy-typescript-integ-tests/package.json, smithy-typescript-ssdk-libs/package.json, smithy-typescript-ssdk-libs/yarn.lock
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2731
Bump eslint deps in SSDK libs.
=> chore: bump eslint deps in SSDK libs

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2733
Bump typescript to ~4.4.2
=> chore: bump typescript to ~4.4.2

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/validation/LongValidator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/validation/LongValidatorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/validation/long-validation.smithy
This adds a warning when generating SSDK longs, because JS numbers can't accurately represent them.
=> Add warnings when generating for SSDK longs

CHANGELOG.md, build.gradle.kts
Related: https://github.com/aws/aws-sdk-js-v3/pull/2743
=> Bump code generators to 0.6.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
Timestamp formats are modeled, and instead of relying on the JavaScript Date
constructor's undefined behavior to support all three styles of timestamp,
we use a specific strict parsing method based on the modeled type to ensure
that we are only accepting timestamps in the correct format.
`DocumentMemberDeserVisitor` did not have a reference to the member being
deserialized, so it could not discover traits that were applied to the member
(such as `@timestampFormat`). It also needed to know whether epoch
timestamps are allowed to be strings, which is protocol-specific.
This relies on https://github.com/aws/aws-sdk-js-v3/pull/2737 and there will be a follow-up PR for SDK-specific generation changes.
By submitting this pull request, I confirm that you can use, …
=> Parse timestamps strictly

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
This reverts commit 885fec0c14387f627e01c18dd511b4a6949b1409.
Temporary revert to unblock https://github.com/aws/aws-sdk-js-v3/pull/2759
=> Revert "Parse timestamps strictly"

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
This reverts commit def6db8293df0e7c7cdd644f865fcf78cf5b746b.
This restores https://github.com/awslabs/smithy-typescript/commit/885fec0c14387f627e01c18dd511b4a6949b1409
Push this when https://github.com/aws/aws-sdk-js-v3/pull/2760 is ready to be shipped.
=> Revert "Revert "Parse timestamps strictly""

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
While the server-common package is in an alpha state, every bump can mean a breaking change. So this updates the resolved dependency to only pick a specific version.
=> Use a very specific version of server-common

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java
Unions must be objects with exactly one key set.
Relies on https://github.com/aws/aws-sdk-js-v3/pull/2746 and tested with protocol tests
=> Parse unions strictly

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
This updates the http binding generator to use the context's http encoder / decoder for base64 rather than relying on Buffer's implementation. We do still use Buffer for converting between utf8 and Uint8Array though.
Codegen pr: https://github.com/aws/aws-sdk-js-v3/pull/2786
=> Use base64 en/decoder from context in bindings

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2782
Downgrade typescript to ~4.3.5
=> chore: downgrade typescript to ~4.3.5

.github/workflows/git-sync.yml
Similar to https://github.com/aws/aws-sdk-js-v3/pull/1965
use git-sync action to sync with private mirror
*Testing:*
Testing done with the following packages:
* source: [`trivikr/git-sync-test`](https://github.com/trivikr/git-sync-test)
* destination: [`trivikr/private-git-sync-test`](https://github.com/trivikr/private-git-sync-test)
Config tested: https://github.com/trivikr/git-sync-test/blob/302d7d5cf429594757c9a32ead5e0816715f9b95/.github/workflows/git-sync.yml
Example GitHub Action run: https://github.com/trivikr/git-sync-test/runs/1778705960?check_suite_focus=true
Verified that secrets are not shown in the GitHub Action log
<details>
<summary>GitHub Action log</summary>
```
Cloning into '/root/source'... …
```
=> feat: use git-sync action to sync with private mirror

.gitignore
Refs: https://github.com/awslabs/smithy-typescript/issues/425
gitignore `smithy-typescript-codegen/bin/`
=> chore: gitignore smithy-typescript-codegen/bin/

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.types.json
Refs: https://github.com/aws/aws-sdk-js-v3/issues/2797
Experimental PR in https://github.com/trivikr/temp-client-s3/pull/9
Removes comments from transpiled JS files as follows:
* Sets `removeComments: true` for CJS and ES TSConfigs, and removes config to emit declaration files.
* Creates new `tsconfig.types.json` for emitting declaration files.
* Adds `build:types` script for generating types, and calls it from `build`.
=> feat: remove comments from transpiled JS files

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2820
Remove redundant dot slash from typedocOptions
=> chore: remove redundant dot slash from typedocOptions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-ssdk-libs/server-common/src/accept.spec.ts, smithy-typescript-ssdk-libs/server-common/src/accept.ts, smithy-typescript-ssdk-libs/server-common/src/index.ts
Currently, we do an exact-match of the Accept header (if present) against the document media type for the protocol. Accept headers can be [much more complicated](https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.2) than a single media type, so we must parse it to be sure that the client cannot handle our preferred response type before sending a 406 response.
I tested this by regenerating and re-running the server protocol tests against the tip of the SDK's main. They pass.
=> Better handling of Accept headers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/LanguageTarget.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/WaiterGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.types.json, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IndexGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegatorTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1306
Experimental PR was posted at https://github.com/awslabs/smithy-typescript/pull/432
Moves source files to "src" folder
=> feat: move source files to "src" folder

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts
Previously the protocol test won't throw if the xml payload's outmost node name is different. For example, it succeeded if payload is `<Hola><name>Phreddy</name></Hola>` but expected `<Hello><name>Phreddy</name></Hello>`. This change fixes it.
=> fix(protocol-test): compare xml payload with outmost node

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerSymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Fixes server protocol tests.
Example failure: https://github.com/aws/aws-sdk-js-v3/runs/3747465220
Move SSDK source code to 'src' folder
*Testing:*
Verified that source files are generated in `"src"` folder and build is successful.
The tests fails with the following error, but it's unrelated to moving source code to 'src' folder in `protocol_tests/aws-restjson-server`
```console
lerna ERR! yarn run build exited 2 in '@aws-sdk/aws-restjson-server'
lerna ERR! yarn run build stdout:
$ yarn build:cjs && yarn build:es && yarn build:types
$ tsc -p tsconfig.json
src/protocols/Aws_restJson1.ts(38,3): error TS2305: Module '"@aws-smithy/server-common"' has no exported member 'acceptMatches'.
info Visit https://yarnpkg.com/en/docs/cli/run for …
```
=> fix: move SSDK source code to 'src' folder

smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/yarn.lock
There are incompatibilities between 3.34.0 and the types we bring in via this
package. The next release of the generators will be generating (at least)
3.34.0.
Without this, an SSDK trying to use this package and the latest SDK (via generation and its own dependencies) will get impossible-to-decipher type mismatch errors from the type checker.
=> Update SDK dependencies in @aws-smithy/server-common

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/2867
Removes sourceMap configuration from root tsconfig, which reduces npm tarball size
=> feat(tsconfig): remove sourceMap

smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Even though smithy-ts technically would move automatically to Smithy 1.12.0,
this bumps up the minimum version in order to ensure the new getErrors method
on OperationIndex will be available at compile time. Discovery of operation
errors globally uses OperationIndex.getErrors(Operation, Service) in order
to support service-bound errors, which were introduced in 1.12.0.
Tested this by regenerating the JS SDK v3 and running protocol tests locally. PR for that repo to fast follow.
=> Update to Smithy 1.12.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Query parameters in protocol tests were being generated in a way that did not match how our APIGateway integration code would present them to our generated code. Query parameters are actually broken right now, but protocol tests do not detect this. These commits align our protocol test generation to how APIGateway treats query parameter values, and fixes code generation to handle them appropriately.
=> Fix query parameters in SSDK

smithy-typescript-ssdk-libs/server-common/src/httpbinding/mux.spec.ts, smithy-typescript-ssdk-libs/server-common/src/httpbinding/mux.ts
The existing code doesn't account for the fact that all query parameter values
can be multi-valued, even when there's only one value in the input URL. Also,
a query string literal can be satisfied by any of the values in the input URL,
whereas the existing code would insist that there exist no other value for the
key in the literal.
=> Fix query matching against list query values

build.gradle.kts, smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen/build.gradle.kts
Use a specific version of smithy-cli, and restrict Smithy versions to the
bugfix version range of 1.12, instead of any minor version of 1, so that we
don't introduce mismatches in the Smithy version downstream.
=> Be more specific about Smithy versions

smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts, smithy-typescript-ssdk-libs/yarn.lock
re2 uses a native module that has a normal dependency on node-gyp, which
bloats the installed size of a service and requires special care when
packaging.
re2-wasm has no dependencies, and while it is not officially supported, it is
used by grpc-node's grpc-js-xds package.
=> Switch to re2-wasm

smithy-typescript-ssdk-libs/server-common/src/httpbinding/mux.spec.ts, smithy-typescript-ssdk-libs/server-common/src/httpbinding/mux.ts
https://github.com/awslabs/smithy-typescript/issues/464
=> Fix greedy label matching

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
We announced [the end of support for Node.js 10.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-10-x-in-the-aws-sdk-for-javascript-v3/) starting January 1, 2022 back in July.
Bump engines to node >=12.0.0
=> chore(package.json): bump engines to node >=12.0.0

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
No longer needed, as we've ending support for Node.js 10.x in https://github.com/awslabs/smithy-typescript/pull/481
Removes call to unsupported version deprecation warning in runtimeConfig
=> chore: remove unsupported version deprecation warning

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/typedoc.json
Part of using root tsconfig for all clients in aws-sdk-js-v3
Refs: https://github.com/aws/aws-sdk-js-v3/issues/1307
Moves typedocOptions to typedoc.json
=> chore: move typedocOptions to typedoc.json

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/3138#issuecomment-1005861884
The `build:docs` command now calls typedoc directly, so that it can be used in internal release automation.
Reasons for removing clean:docs call:
* The build:docs command should do work only what it's asked to do. Cleaning docs is an additional work.
* The docs may not have been generated in the default docs folder. We'll decide later if `clean:docs` script should be removed altogether.
* The typedoc dependency is being moved to root package.json in https://github.com/aws/aws-sdk-js-v3/pull/3138, so typedoc will not be available in node_modules for each client and they need to use `build:docs` command.
By submitting this pull request, I confirm that you can use, …
=> chore: do not clean docs during build

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Internal discussion on Slack
Renames npm script `downlevel-dts` to `build:types:downlevel`
=> chore: rename downlevel-dts to build:types:downlevel

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Internal discussions on Slack.
Reasons for update:
* We don't use `clean:docs` command in clients in aws-sdk-js-v3 repo.
* We do not have any clean commands in non-clients.
* The docs may have been created in a different folder.
Ideally, the typedoc script should clean the folder used for docs be default, or provide an option or plugin to perform that function (like webpack does). Follow-up feature request created at https://github.com/aws/aws-sdk-js-v3/issues/3167
Use clean to remove dist-* folders
=> chore: use clean to remove dist-* folders

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
We use regex to extract labeled path values, and literal path segments can
contain unescaped regex literals that can both blow up deserialization and
present ReDoS risks. While it's unlikely we will see these paths in practice,
we should still escape special regex characters.
See https://github.com/awslabs/smithy/pull/1018 for an example of a test that is fixed with this change.
=> fix(codegen): escape regex literals in path segments

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/3090
Removes emission for filterSensitiveLog for service exceptions
=> chore: remove filterSensitiveLog for service exceptions

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
Internal JS-2681
Similar to https://github.com/aws/smithy-go/pull/304
Supports delegation of determining errors for an operation, needed to support [awsQueryError](https://awslabs.github.io/smithy/1.0/spec/aws/aws-query-protocol.html#aws-protocols-awsqueryerror-trait) trait
=> chore: support delegation of determining errors for an operation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
Improvement noticed while investigating https://github.com/aws/aws-sdk-js-v3/pull/3174
Check for ErrorName to be thrown in protocol tests, thus removing unused imports
=> chore: check for ErrorName to be thrown in protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddDefaultsModeDependency.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.browser.ts.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeConfig.ts.template
=> feat: load different sdk defaults value from defaults mode

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
Internal JS-3027
This code change surfaced a bug in our error deserializer, where the error message is modeled to be in key `message` but the actual message is response payload with key `Message`.
This reverts commit a56d3525d6617a5a205a4fca04872cafbfb7eaff added in https://github.com/awslabs/smithy-typescript/pull/489.
=> Revert support delegation of determining errors for an operation

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/reserved-words.txt
This extends the reserved words list to include the words included in the "contextual keywords" list of the TypeScript grammar. It does not change generation of any of the existing AWS SDKs.
=> Add contextual keywords to the reserved words list

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Doing a clean build in prepack works for both package managers and makes a
simple process of codegen && (npm|yarn) publish work out of the box. Also
adds an "omitPrepack" configuration option to allow the SDK to disable this
script for backwards compatibility.
=> feat(codegen): add a default prepack script

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.spec.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPluginTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth-trait-all-optional.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth-trait-no-scheme.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth-trait-on-operation.smithy, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth-trait.smithy
*Issue #, if available:* Fixes #453.
*Description of changes:* This adds codegen support for services and operations that use the `@httpApiKeyAuth` trait.
The generated client will have a new `apiKey` config attribute. This value will be injected into the header/query parameter that's specified in the trait by new middleware that's included in the codegen client.
⚠️ I've done my best to base this on existing patterns but I'm sure that there will be comments and things that need to change. Please let me know and I'll happily make adjustments.
=> feat: support @httpApiKeyAuth trait

CHANGELOG.md, build.gradle.kts
=> Bump version to 0.9.0.

smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
*Issue #, if available:* https://github.com/awslabs/smithy-typescript/issues/509
The Smithy spec specifies that string length is defined as the number of code
points. JavaScript's String.length returns the number of code units, leading to
inaccurate validation when a string contains characters that use multiple code
units to represent one code point.
=> Fix the implementation of length validation for strings

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
https://github.com/awslabs/smithy/pull/1097 adds a protocol test for sets of
documents and without this change the generated tests are invalid, as they
are missing the separating commas that other types receive.
=> Fix the generation of collections of documents in protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java
Internal JS-2725
Adds support for writing List<String> in function parameters list.
Required for passing `responseAlgorithms` in [httpChecksum](https://awslabs.github.io/smithy/1.0/spec/aws/aws-core.html#aws-protocols-httpchecksum-trait) trait.
Testing was done in https://github.com/awslabs/private-smithy-typescript/pull/10
=> Support List<String> in function parameters list

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Currently, for `npm` the concurrently syntax was `concurrently 'npm run-script:build:cjs'` which is wrong and didn't work. `npm:build:cjs` (similar to `yarn:build:cjs`) is good syntax for concurrently.
Extracting run-script out of PackageManager.getCommand and specifying `run` directly in package.json scripts (prepack). `run` is equivalent alias to `run-script` in npm.
=> Fix scripts for npm by extracting `run` command out 

CHANGELOG.md, build.gradle.kts
=> Bump code generators to 0.10.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
Noticed while updating BodyLengthCalculator type in https://github.com/aws/aws-sdk-js-v3/pull/3404
Set bodyLengthChecker type to BodyLengthCalculator
=> Set bodyLengthChecker type to BodyLengthCalculator

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Refs: https://github.com/aws/aws-sdk-js-v3/pull/3448
Bumps TypeScript to ~4.6.2
=> Bump TypeScript to ~4.6.2

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java
Metadata on output type on client SDK makes sense, but on the server
SDK does not.
Tested by building this change locally and updating our demo service.
=> Remove MetadataBearer from output type

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
https://github.com/aws/aws-sdk-js-v3/issues/3490
Add check for optional pagination halt condition of prevToken equalling nextToken.
In test output:
```js
const prevToken = token;
token = page.nextToken;
hasNext = !!(token && (!config.stopOnSameToken || token !== prevToken));
```
This depends on https://github.com/aws/aws-sdk-js-v3/pull/3524
=> check for pagination stopOnSameToken option

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java
This is to simplify the existing code in preparation for using [SmithyIntegration](https://github.com/awslabs/smithy/blob/b7b48cf78a745af27a5d9889080cfa4743ba732f/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyIntegration.java#L109) interface as part of [DirectedCodgen](https://github.com/awslabs/smithy/blob/main/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java).
Currently CodegenVisitor recreated TypeScriptSettings object after each preprocessModel. The only thing that could change in TypeScriptSettings based on the model would be the [service ShapeId](https://github.com/awslabs/smithy-typescript/blob/5405242969e11b5d81ec936fb0ea078875e9ef3e/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typesc …
=> Change `preprocessModel` to take `Model` instead of `PluginContext`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddBaseServiceExceptionClass.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolDecoratorIntegration.java
This is in preparation for using [SmithyIntegration](https://github.com/awslabs/smithy/blob/ee4af1095cbb4900533da6298bbd28221c446b6c/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyIntegration.java#L129) interface as part of [DirectedCodgen](https://github.com/awslabs/smithy/blob/main/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java).
Corresponding change in aws-sdk-js-v3/codegen: https://github.com/aws/aws-sdk-js-v3/pull/3607
=> Refactor decorateSymbolProvider to match SmithyIntegration

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
This is causing unnecessary imports in generated clients like https://github.com/aws/aws-sdk-js-v3/blob/6d232d050605a9a335771562ca6d08e31ccbcdaf/clients/client-accessanalyzer/src/models/models_0.ts#L3
Corresponding update to generated AWS clients https://github.com/aws/aws-sdk-js-v3/pull/3621
=> Error shapes do not explicitly need to reference MetadataBearer

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java
The javadoc was missed copying over when the logic was extracted into StructureGenerator class in https://github.com/awslabs/smithy-typescript/commit/4399ea0c97f43700c3b6066bfbcc518d07cbd10b
=> Move javadoc to StructureGenerator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
The Walker does not traverse relationships create by traits anyways.
Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` in aws-sdk-js-v3 with this change to confirm there is no change to clients. Though there is some rearrangement of code within a file in protocol tests. Here's the diff https://github.com/aws/aws-sdk-js-v3/pull/3633
=> Do not use getModelWithoutTraitShapes

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CodegenVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDelegatorTest.java
The SymbolProvider(SymbolVisitor) also includes the src folder, so this is
unnecessary. Conceptually it also makes sense that the filename is responsibility of the Symbol Provider, not the Delegator.
Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` locally with and there is no change to generated clients.
This is in preparation to use WriterDelegator (as part of DirectedCodegen) so that [WriterDelegator.useShapeWriter](https://github.com/awslabs/smithy/blob/df456a514f72f4e35f0fb07c7e26006ff03b2071/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/WriterDelegator.java#L198) can be used directly without needing to override in TypeScriptDelegator.
By submitting this pull request, I confirm that you can use, …
=> Remove unnecessary src folder prepend in useShapeWriter

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Internal JS-3299
Use Record<string, any> in event stream deserializer
=> Use Record type in event stream deserializer

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-form-urlencoded-stub.ts
Internal JS-3299
Use Record type instead Object type.
Searched for regular expression `\{ \[key: string\]: ([^ ]*) \}` and replacing it with `Record<string, $1>`
=> Use Record type in place of Object

smithy-typescript-ssdk-libs/server-apigateway/src/lambda.ts, smithy-typescript-ssdk-libs/server-common/src/unique.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
Internal JS-3299
Use Record type instead Object type.
Searched for regular expression `\{ \[key: string\]: ([^ ]*) \}` and replacing it with `Record<string, $1>`
=> Use Record type in place of Object in SSDK libs

smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGeneratorTest.java
`getOrder` was added in https://github.com/awslabs/smithy-typescript/commit/edca7f62ab935c9acdaac1e87aaf6f37ac643d12 from https://github.com/awslabs/smithy-typescript/pull/153, but it is unnecessary. `RuntimeConfigGenerator` itself does not do sorting/rely on getOrder. It expects the `integrations` passed in to already be sorted. So in the `expandsRuntimeConfigFile` test, the 2nd integration's `writer.write("syn: 'ack1',");` is used and that's what is asserted in the test, which is independent of whether getOrder would return `1`, `-1`, `0` or any value.
Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` locally with and there is no change to generated clients.
By submitting this pull request, I confirm that you can use, modify, …
=> Remove unnecessary getOrder in a test

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Internal JS-3299
Uses Record type in place of Object in HttpBindingProtocolGenerator. This was missed in https://github.com/awslabs/smithy-typescript/pull/557, as the regular expression didn't search for space after square bracket ends.
This PR searches for regular expression `\{ \[key: string\] : ([^ ]*) \}` and replacing it with `Record<string, $1>`
It also searched for regular expressions `string[ ?]*\]`, and verified there are none in Java code
=> Use Record type in place of Object in HttpBindingProtocolGenerator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
The Lex-runtime-v2 service cannot serialzie the event correctly because the events without `eventHeader` or `eventPayload` trait are not serialized, but returned as plain JavaScript object. 
For example:
1. The `TextEvent` is modeled as structure and serialized into a JavaScript Object([link](https://github.com/aws/aws-sdk-js-v3/blob/567a5304232fcc1f9db3fd3df545054de8336b4b/clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts#L1719-L1726)). 
1. The JavaScript Object was directly passed to the event body([link](https://github.com/aws/aws-sdk-js-v3/blob/567a5304232fcc1f9db3fd3df545054de8336b4b/clients/client-lex-runtime-v2/src/protocols/Aws_restJson1.ts#L1107)) without serializing. 
1. This results in the event marshaller fails to the allocate correct …
=> generate protocol-specific event payload

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java
There are 2 changes:
1. Remove unused integrations from ProtocolGenerator.GenerationContext
Didn't look into history, but is unused.
2. Remove unused ProtocolGenerator.GenerationContext.withSymbolProvider
This method was introduced in https://github.com/awslabs/smithy-typescript/commit/6e8f0902a20a432125f9b64a39f27d709f68f4c7#diff-29f426bcf693083ef5343733b2f9813bd61186bf026c2dd81e6795824027ce0eR328 but become unnecessary with https://github.com/awslabs/smithy-typescript/commit/91c6b12e9615ca59cf48d544bd06d1c1ef3610b5#diff-29f426bcf693083ef5343733b2f9813bd61186bf026c2dd81e6795824027ce0eR337.
Ran `yarn generate-clients && yarn test:protocols && yarn generate-clients -s && yarn test:server-protocols` locally and there is no change to generated clients.
By submitting this pull request, I …
=> Remove usused code from ProtocolGenerator.GenerationContext

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Ref: P66766800
Populate the `:content-type` header for all the event messages. It was missed previously. When the payload shape is `blob`, the value is `application/octet-stream`; When the payload shape is `string`, the value is `text/plain`, When the payload shape is `Union` or `Structure`, the value is the protocol's content type.
=> fix: populate content-type header for all events

README.md
When there is a new version of Smithy that is not compatible with
the version of Smithy specified in normal dependencies, the
example given in the README can break. This locks the smithy-cli
version to the same version that is specified in the build.
See https://github.com/aws-samples/smithy-server-generator-typescript-sample/issues/3
=> Update README example to lock smithy-cli version

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Associated with https://github.com/aws/aws-sdk-js-v3/pull/3805
Move all the event stream related utilities to the `EventStreamGenerator` class from the bloat `HttpBindingProtocolGenerator`. Make it ready to be used in the RPC protocol generators.
=> refactor eventstream generation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Blocked by https://github.com/awslabs/smithy-typescript/pull/572
Confirmed it works for eventstream for JSON rpc protocol(kinesis) for event stream input & output.
=> support event stream for RPC protocols

.gitignore, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
Problem: model namespaces containing *only* a filterSensitiveLog function are generated alongside most model interfaces. This is distracting to readers of the model file, and worse, creates an interruption when users use VSCode’s go-to-definition functionality on model interfaces that have an identical name with these namespaces. 
Solution: remove these namespaces and generate the filter functions with unique names.
=> feat(codegen): remove namespaces that only contain logfilters

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Object field names are often repeated multiple times per line in code that is only transferring fields from one object to another (mapping), with repetitive checks.
Request headers
```typescript
const headers = {
"content-type": "application/xml",
...(isSerializableHeaderValue(input.ChecksumCRC32) && { "x-amz-checksum-crc32": input.ChecksumCRC32 }),
...(isSerializableHeaderValue(input.ChecksumCRC32C) && { "x-amz-checksum-crc32c": input.ChecksumCRC32C }),
...(isSerializableHeaderValue(input.ChecksumSHA1) && { "x-amz-checksum-sha1": input.ChecksumSHA1 }),
...(isSerializableHeaderValue(input.ChecksumSHA256) && { "x-amz-checksum-sha256": input.ChecksumSHA256 }),
...(isSerializableHeaderValue(input.RequestPayer) && { "x-amz-request-payer": input.RequestPayer }), …
```
=> feat(codegen): general data mapping function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Fix for aws-sdk-js-v3 `yarn generate-clients -s && yarn test:server-protocols`
=> fix(server-protocol-tests): fix codegen for server-protocol-tests

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
*Issue #, if available:* #560
We will add the proper sub-dependencies overrides for both NPM and Yarn. This way we will not need to install with force resolution enabled.
=> fix: override typescript version for typedoc

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/PackageJsonGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptSettingsTest.java
Update default `package.json` description based on artifact type
For example if the package name is `ExamplePackage`, the following package description can be:
* Client -> `ExamplePackage client`
* SSDK -> `ExamplePackage server`
=> Update default package description based on artifact type

build.gradle.kts
Internal P71712427
Bumps smithy to 1.25.x to attempt to remediate preview build failures.
=> Update to smithy 1.25.x

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
This exposes the static instructions object for each command so that it can be used by other internal packages like s3 presigner and lib-upload that need to resolve the v2 endpoint of e.g. `PutObjectCommand` without necessarily `send`ing an instance of that command.
before:
```js
public resolveMiddleware() {
this.middlewareStack.use(getEndpointPlugin(configuration, { /* instructions literal object */ })  
}
```
after:
```js
public static instructions(): EndpointParameterInstructions {
return { /* instructions literal object */ };
}
public resolveMiddleware() {
this.middlewareStack.use(getEndpointPlugin(configuration, Command.instructions())  
}
```
Since the instructions are not tied to individual Command instances, the function can be static.
=> feat(endpoint): expose static endpoint param instructions provider

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
- codegen fixes for endpoints 2.0
=> fix(endpoint): fixes to endpoints codegen from user testing

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java
Internal JS-3034
Calls parseErrorBody when parsing error structures
=> Call parseErrorBody when parsing error structures

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java
- write out more params in the generated interface instead of only client context params
- add param defaults to the generated E2.0 config resolver step
=> fix(endpoint): misc fixes for endpoints 2.0 based on service unit test cases

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json
Internal JS-3616
Blog post: [Announcing the end of support for Internet Explorer 11 in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-internet-explorer-11-in-the-aws-sdk-for-javascript-v3/)
This PR will be rebased and made ready after v3.182.0 release on Sep 30th.
Bumps tsconfig.es.json target to ES2020
=> Bump tsconfig.es.json target to ES2020

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json
requested by Amplify
temporarily reverts https://github.com/awslabs/smithy-typescript/pull/603 and https://github.com/aws/aws-sdk-js-v3/pull/4006
=> temporary: publish one more es5 version

gradle.properties, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IntEnumGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/EnumGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/IntEnumGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
PR adds support for `intEnum` shapes added with Smithy IDLv2. It relies DirectedCodegen changes added in Smithy 1.26.0 and updates to use 1.26.x.
Given this Smithy model:
```
structure MyStruct {
myIntEnum: MyIntEnum
}
intEnum MyIntEnum {
BAR = 3
FOO = 1
BAZ = 2
}
```
The following types will be generated:
```
export enum MyIntEnum {
FOO = 1,
BAZ = 2,
BAR = 3,
}
export interface MyStruct {
myIntEnum?: MyIntEnum | number;
}
```
This PR also adds and updates tests and documentation for `enum` shape generation, including the `| string` behavior in the `SymbolVisitor`, and ordering applied to members in `EnumGenerator`.
=> Add intEnum support, tests for enum generation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsParamNameMap.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetSerializer.java
- takes the endpoints-2.0 branch for all service models in aws-models repo and tests codegen + compilation
- fixes resulting TS compilation errors
=> fix(endpoints): move AWS name map to JSv3, additional fixes for all-service endpoint compilation

smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
add default signing name for endpoints 2.0 based on the sigv4 trait or the service arn namespace, because it will not have the region info provider and not all endpoints resolve with an authScheme containing a signing service name.
This PR is for: https://github.com/aws/aws-sdk-js-v3/pull/4044
=> fix(endpoint): add default signing name

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsParamNameMap.java
- fix: dedupe clientContextParams with builtInParams with the same name
- fix for JS conventions: default local param name to `camelCase` if it is `TitleCase`
=> fix(endpoint): deduplicate client context and built-in params with the same name

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
don't rename context params like `Bucket` to `bucket`.
=> fix(endpoint): do not modify context param names

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetSerializer.java
Wrap quotes on object keys in the ruleset object.
ruleset might have a key like `"x-amz-account-id":`
=> fix(endpoint): quote-wrap keys in generated ruleset ts file

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/4053
Uses FileWriter from TypeScript Delegator to write EndpointV2 files, and add `@aws-sdk/util-endpoints` dependency in return.
=> Use FileWriter from TypeScript Delegator to write EndpointV2 files 

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java
override the type of `endpoint` in endpoint params to `string|Endpoint|EndpointV2` instead of only `string`
=> fix(types): expand custom endpoint type

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
We announced [the end of support for Node.js 12.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/) starting November 1, 2022 back in May.
Bump engines to node >=14.0.0
=> chore(package.json): bump engines to node >= 14.0.0

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.cjs.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
Internal JS-3680
Uses @tsconfig/node14 as base
=> feat: use @tsconfig/node14 as base

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
internal V750691458
restricts the context param Bucket and uri segment Bucket deduplication to only S3.
=> fix(codegen): limit the Bucket param dedupe to S3 service

settings.gradle.kts
Internal JS-3822
CI build are failing with:
```console
A problem occurred configuring project ':smithy-typescript-codegen-test'.
> Could not resolve all artifacts for configuration ':smithy-typescript-codegen-test:classpath'.
> Could not resolve software.amazon.smithy:smithy-cli:[1.26.0,1.27.0[.
Required by:
project :smithy-typescript-codegen-test
> Failed to list versions for software.amazon.smithy:smithy-cli.
> Unable to load Maven meta-data from https://plugins.gradle.org/m2/software/amazon/smithy/smithy-cli/maven-metadata.xml.
> Could not get resource 'https://plugins.gradle.org/m2/software/amazon/smithy/smithy-cli/maven-metadata.xml'.
> Could not GET 'https://jcenter.bintray.com/software/amazon/smithy/smithy-cli/maven-metadata.xml'. …
```
=> Add mavenCentral as plugin repository

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Node.js 12 has reached EOL. This updates the usage of types to 14 and higher.
=> chore(types): set @types/node version to 14

gradle.properties
Internal JS-3822
Pin smithy-cli version to 1.26.1 to temporally handle issues with gradle dependencies.
Previous attempt in https://github.com/awslabs/smithy-typescript/pull/629
<details>
<summary>Before</summary>
```console
$ rm -rf ~/.gradle/*                 
zsh: sure you want to delete all 6 files in /home/trivikr/.gradle [yn]? y
$ ./gradlew clean publishToMavenLocal
...
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':smithy-typescript-codegen-test'.
> Could not resolve all artifacts for configuration ':smithy-typescript-codegen-test:classpath'.
> Could not resolve software.amazon.smithy:smithy-cli:[1.26.0,1.27.0[.
Required by:
project :smithy-typescript-codegen-test
> Failed to …
```
=> Pin smithy-cli version to 1.26.1

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java
Internal JS-3705
Use util-base64 in ServerGenerator.
In AWS SDK for JavaScript (v3) clients, the change was done in https://github.com/aws/aws-sdk-js-v3/pull/4140
*Testing:*
Verified that tests pass for server artifacts:
```console
$ aws-sdk-js-v3> yarn generate-clients --server-artifacts
$ aws-sdk-js-v3> yarn test:server-protocols
...
lerna success run Ran npm script 'test' in 2 packages in 15.2s:
lerna success - @aws-sdk/aws-restjson-server
lerna success - @aws-sdk/aws-restjson-validation-server
Done in 49.06s.
```
=> Use util-base64 in ServerGenerator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.spec.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.ts
*Issue #, if available:* N/A
In order to defer resolving the API Key configuration to when we actually make the API call, we need to allow a function to be passed in the `apiKey` property. Now that we are importing the library `@aws-sdk/util-middleware` as part of the API Key middleware, we included it explicitly as a dependency to our generated project.
=> feat(smithy-typescript-codegen): allow deferred resolution for api key config

README.md
=> Update versions in README example

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
The util additions of dependencies util-base64-node and util-base64-browser were manually replaced to that of util-base64 in https://github.com/aws/aws-sdk-js-v3/pull/4140
However, they were re-added by codegen while updating clients endpoints from 2022-11-04 in https://github.com/aws/aws-sdk-js-v3/commit/7471107c0881b5d9e474447a660dd3354a50b195
Remove unconditional adding of util-base64 node and browser modules
=> Remove unconditional adding of util-base64 node and browser modules

.github/workflows/ci.yml
Refs: https://github.com/aws/aws-sdk-js-v3/pull/4203
We're switching to `corretto` distribution as it's used internally at Amazon
Bumps actions/setup-java to v3
=> Bump actions/setup-java to v3

.github/workflows/ci.yml
Bumps default runtime to node16 https://github.com/actions/setup-node/pull/414
Removed deprecation notice printed under https://github.com/awslabs/smithy-typescript/actions/runs/3491161866
Bump actions/setup-node to v3
=> Bump actions/setup-node to v3

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
internal JS-3645
`expectNonNull` is a throwing assertion function from smithy-client. 
This PR adds this assertion to input shape members that have the `required` trait.
Example:
```js
s3.abortMultiPartUpload({ /* missing uploadid */ });
// TypeError: Expected a non-null value for UploadId
```
=> validate required input query params

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
This PR adds the `util-retry` added in https://github.com/aws/aws-sdk-js-v3/pull/4224 as a dependency so that it can be used by updated clients in a forthcoming PR.
=> Add util-retry dependency

smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
internal JS-3641
pair with https://github.com/aws/aws-sdk-js-v3/pull/4259
make defaultSigningName configurable externally. AWS codegen will set this value instead of Smithy-TS.
=> chore: remove aws trait dependency

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
`intEnum` shapes aren't handled correctly when generating output value provider. This one-line change fixes this issue.
N/A
When running protocol test generation, `intEnum` shapes aren't handled correctly in the output-value provider generation step of `HttpBindingProtocolGenerator`. This change address the following error:
```
Projection aws-protocoltests-restjson failed: software.amazon.smithy.codegen.core.CodegenException: Unexpected number shape `intEnum`
```
=> Fix the handling `intEnum` shapes when generating output value

smithy-typescript-codegen/build.gradle.kts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
internal P75309097
Currently we provide a default idempotency token (uuid v4) if a request structure member has the smithy trait.
We do not provide one if the member is a query parameter. 
- This PR adds the idempotency default token (`uuid.v4()`) for query parameters. 
from https://smithy.io/1.0/spec/core/behavior-traits.html#idempotencytoken-trait
> A unique identifier (typically a [UUID](https://tools.ietf.org/html/rfc4122)) SHOULD be used by the client when providing the value for the request token member. When the request token is present, the service MUST ensure that the request is not replayed within a service-defined period of time. This allows the client to safely retry operation invocations, including operations that are not read-only, that fail due to networking issues or …
=> fix: add idempotencyToken generation if member is queryParam

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Jest versions >= 27 replace jest-jasmine2 with jest-circus, which does not have an implementation for the `fail()` method, but still has the method stub defined in the Jest type-defs. This change implements the `fail()` method in protocol test suites, and adjusts the thrown message to actually state the error, instead of just `err`.
For more information, see [DefinitelyTyped maintainer discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55803)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the 
terms of your choice.
*Testing*
Run the protocol test suite after making changes and running the codegen
Before changes:
```ts
● Ec2QueryDateTimeWithNegativeOffset:Response …
```
=> Fix broken reference to `fail()` after jest-upgrade

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Fixes an issue brought in through https://github.com/awslabs/smithy-typescript/pull/645
*Testing*
- built smithy-typescript and published to local maven
- ran client-generation in JS SDK, verified no build errors
- ran protocol-test generation and ran tests, verified no build errors
- verified code-gen:
```ts
let r: any;
try {
r = await client.send(command);
} catch (err) {
fail("Expected a valid response to be returned, got " + err);
return;
}
```
- verified test output for a forced-to-fail test:
```
● Ec2QueryDateTimeWithPositiveOffset:Response
Expected a valid response to be returned, got TypeError: Invalid RFC-3339 date-time value
```
(NOTE: I intentionally made this test fail)
By submitting this pull request, I confirm that you can …
=> Fix Error printout for protocol-response tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java
Internal JS-3916
Reads staticContextParams from operation, and not from operationInput
=> Read staticContextParams from operation

.github/workflows/ci.yml
Add Gradle Wrapper Validation Action, based on https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action.
This PR is a replacement for https://github.com/awslabs/smithy-typescript/pull/255.
=> Add Gradle Wrapper Validation Action

.github/workflows/ci.yml, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ImportDeclarations.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
https://github.com/awslabs/smithy-typescript/issues/568
The use of `Paths.get` when creating an import/export path, ie. `import { Foo } from ./path`, caused tests to fail on Windows because the tests expect unix-like paths. For portability and consistency, the places where import/export paths are created in `SymbolVisitor` and `ImportDeclarations` were refactored to always create unix-like path separators regardless of OS.
Additionally, CI was added for Windows (and MacOS since it wasn't there already).
*Testing details:*
- Ran `./gradlew clean build` successfully on Windows and Mac
=> Fix codegen windows

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
Currently, protocol tests generated and run against Smithy 1.26.3 or later result in the following error:
```
src/protocols/Aws_restXml.ts(2199,27): error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```
This is due to the protocol test addition in https://github.com/awslabs/smithy/pull/1440.
This PR updates the DocumentMememberSerVisitor to append `.toString()` so that generated input parameter serializers are converted to strings where necessary for restXml protocols.
To test, these smithy-typescript changes were published locally with `./gradlew clean build pTML` before Smithy dependencies were updated in https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/gradle.properties#L1 to `1.26.4` and the following was successfully run: `yarn …
=> Fix restXml protocol test for timestampFormat targets

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
This reverts commit f42c5d0f171e9b6ebb2f1c9092c6a59f74b48c30.
This PR reverts the changes to timestampFormat targets.
The changes to the serialization caused an issue with serializing milliseconds since epoch for EventStream: https://github.com/aws/aws-sdk-js-v3/issues/4343
=> Revert "Fix restXml protocol test for timestampFormat targets"

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddDefaultsModeDependency.java
*Issue #, if available:* N/A
Ensure import type aliases are consistent to avoid the same import appearing twice (for example as [here](https://github.com/aws/aws-sdk-js-v3/blob/3844108f9adcd8282f66189427bad8cb309d2746/clients/client-accessanalyzer/src/AccessAnalyzerClient.ts#L45-L46)).
=> chore: be consistent with type aliases

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddDefaultsModeDependency.java
Missed in https://github.com/awslabs/smithy-typescript/pull/670
Fix missing underscore prefix in DefaultsMode Provider
=> Fix missing underscore prefix in DefaultsMode Provider

.github/CODEOWNERS
N/A
Makes Smithy codeowners on the entire repo, rather than just the ssdk stuff. 
=> Add smithy as codeowners for the whole repo

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetSerializer.java
#633 
This will generate a valid TypeScript file for `src/endpoint/ruleset.ts`.
=> fix: trailing comma not allowed in ruleset

smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2GeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/endpointsV2/endpoints.smithy
*Issue #, if available:* N/A
Continuation of #634 so that we can have some unit tests for the endpoints v2 generator.
=> chore: add unit tests for endpoints v2 generator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java
This updates server and protocol tests to import `fromUtf8` and `toUtf8` from `@aws-sdk/util-utf8`.
See https://github.com/awslabs/smithy-typescript/pull/672 for equivalent client changes.
=> Import from util-utf8 on server and tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
https://github.com/aws/aws-sdk-js-v3/pull/4379 adds a new datetime parsing function, parseRfc3339DateTimeWithOffset.
This PR updates clients to use the added parsing function to gracefully handle offsets, normalizing them to zero offset.
Servers will continue to use the existing `parseRfc3339DateTime` function.
This PR should not be merged until https://github.com/aws/aws-sdk-js-v3/pull/4379 has been reviewed and merged.
=> Clients parse datetime offsets

smithy-typescript-ssdk-libs/server-common/src/validation/validators.ts
Pulling change from PR #667 where we use the `test` method instead of `match` from re2-wasm library.  Since we only care about the success/failure of the match, `test` is enough, potentially faster, and matches Javascript native's RegExp
interface. Also, that will be useful for consumers that want to swap the regular expression implementation (e.g. with NPM overrides).
=> feat: use re2 test method instead of match

smithy-typescript-ssdk-libs/tsconfig.json
`lib` declarations targeting standards newer than the `target` are useful when one polyfills missing features.
`lib` declarations targeting _older_ standards are constraining in a strange way: we emit code relying on newer features, but types prevent us from using them
Since were are already emitting `es2018` code, we can target that standard for the types as well.
This is a spin-off of @eduardomourar's awslabs/smithy-typescript#667
Co-authored-by: Eduardo Rodrigues <eduardomourar@users.noreply.github.com>
=> chore(codegen): match lib and target declarations

smithy-typescript-codegen-test/smithy-build.json, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/test-required-member.smithy
*Issue #, if available:* #503
A continuation of PR #537, but we will allow to remove `| undefined` by setting an input configuration called `requiredMemberMode` with the following possible values:
- **nullable**: this is the current behavior and it will be the default. When set, it allows a member that has the `@required` trait applied to be `undefined`. By doing so it can still be considered a backwards compatible change for Smithy services even when the required constraint is dropped from a member .
- **strict**: this will remove `| undefined` from the generated code.
=> feat: allow non backward compatible required member

smithy-typescript-codegen-test/smithy-build.json
https://github.com/awslabs/smithy-typescript/pull/566 introduced the `requiredMemberMode` codegen option.
This PR removes this setting from being set in smithy-typescript-codegen-test, resulting in the default `nullable` mode being used. It is being removed to avoid confusion as the `strict` mode should only be used under special cases and in lieu of other documentation, the smithy-typescript-codegen-test may serve as an example for other codegen implementations. 
The `strict` mode deserves better testing and documentation. A future PR will add additional testing and documentation.
=> Use requiredMemberMode default on codegen-test

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
Currently, generic clients fail to compile. Running the following commands:
```
./gradlew :smithy-typescript-codegen:build
cd smithy-typescript-codegen-test/build/smithyprojections/smithy-typescript-codegen-test/source/typescript-codegen
yarn install
yarn build
``` 
Results in compilation errors such as `[build:es] src/commands/GetCityAnnouncementsCommand.ts(55,13): error TS2339: Property 'logger' does not exist on type 'WeatherClientResolvedConfig'.`.
This PR adds AddClientRuntimeConfig which generates client configuration that is currently added to AWS clients via [AddAwsRuntimeConfig](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddAwsRuntimeConfig.java).
Co-authored-by: Jaykumar Gosar …
=> Add AddClientRuntimeConfig for generic clients

smithy-typescript-ssdk-libs/server-common/src/validation/index.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts
This PR updates the `generateValidationMessage` to not return the input value in the validation message.
This change will be paired with updated protocol tests: https://github.com/awslabs/smithy/pull/1622
=> Remove reflected values from validation message

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
This adds a jsdoc comment linking to the original operation ("command") from the types of its input and output. 
This turns into useful back-links in the generated HTML API documentation in AWS SDK JSv3.
=> chore: add command links to its input and output interfaces

smithy-typescript-ssdk-libs/server-common/src/validation/index.spec.ts, smithy-typescript-ssdk-libs/server-common/src/validation/index.ts
This updates the validation message for uniqueItems to match the protocol test change from https://github.com/awslabs/smithy/pull/1639.
=> Update uniqueItems validation message

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
Issue: https://github.com/awslabs/smithy-typescript/issues/700
Change big.js import from "@types/big.js" to just "big.js" to avoid a TypeScript compilation error:
```
error TS6137: Cannot import type declaration files. Consider importing 'big.js' instead of '@types/big.js'.
```
=> Fix generated imports for BigDecimal support

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
for https://github.com/aws/aws-sdk-js-v3/issues/3093
Current paginators use a method based request if the client that is provided by the user is the aggregated client type. 
This is not necessary because the aggregated client extends the barebones client and can still make Command-based requests with `.send()`. 
Inclusion of the aggregated client is detrimental because it imports all commands (and thus protocols/models) in a given service, increasing bundle size.
=> pagination: omit aggregated client in paginators

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Updates the TS protocol test stub to construct HttpResponse objects using the class constructor, instead of with object syntax. The constructor has optional parameters, so when updating the HttpResponse implementation we can continue to pass old properties. Without using the constructor, we have to change the HttpResponse interface and protocol test codegen simulataneously to avoid breaking changes.
Tested via js v3 sdk.
=> Use HttpResponse constructor in protocol tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java
In an edge case, the only model assigned to the last bucket may be `smithy.api#Unit`. 
This causes the code generator to think that `models_N` exists, but in fact only `models_(N-1)` exists because `Unit` does not generate anything. This causes a compilation error in the generated models index.
```ts
// smithy-typescript generated code
export * from "./models_0";
export * from "./models_1"; // file doesn't exist
```
This proposed fix is to ignore `smithy.api#Unit` when incrementing the bucketing counter.
tested code generation against the edge case unreleased feature
=> model bucketing: special case for smithy.api#Unit

smithy-typescript-ssdk-libs/server-node/src/index.spec.ts, smithy-typescript-ssdk-libs/server-node/src/node.ts
*Description of changes:* Adding tests for `convertRequest` method for `server-node` runtime.
=> Add tests for convertRequest (NodeJS sSDK runtime).

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
This adds the modeled errors of each operation to the JSDoc block of the corresponding command.
This will generate useful links in API documentation. The `@throws` entries appear directly after the existing links to the command input, output, and client config. 
The current documentation makes it impossible to find which exceptions are modeled with an operation without consulting the Smithy model declaration file. This will help API documentation readers or source code readers write their error handling switch cases.
Example:
```js
/**
* <p>Returns the content of the specified pronunciation lexicon stored
*       in an Amazon Web Services Region. For more information, see <a href="https://docs.aws.amazon.com/polly/latest/dg/managing-lexicons.html">Managing Lexicons</a>.</p>
* @example
* …
```
=> docs: add thrown exceptions to command documentation

.github/CODEOWNERS
Add the CF team focused on TypeScript server. Similar to https://github.com/awslabs/smithy-typescript/blob/6366593165b8e51a80d84414ceac41dfacae5ce4/.github/CODEOWNERS but with the new team.
=> Add smithy-rs-typescript-server as codeowners for SSDK

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-ssdk-libs/package.json, smithy-typescript-ssdk-libs/server-apigateway/CHANGELOG.md, smithy-typescript-ssdk-libs/server-apigateway/package.json, smithy-typescript-ssdk-libs/server-common/CHANGELOG.md, smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/server-node/CHANGELOG.md, smithy-typescript-ssdk-libs/server-node/package.json
=> Bump SSDK libs version to 1.0.0-alpha.9

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
Bumping TypeScript is unblocked as typedoc is updated https://github.com/awslabs/smithy-typescript/pull/699
Bump typescript to ~4.9.5
=> Bump typescript to ~4.9.5

config/checkstyle/checkstyle.xml, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/validation/SensitiveDataFinder.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/validation/SensitiveDataFinderTest.java
Adds a recursive check for sensitive fields before generating a sensitive data filter function. 
Currently all input/output have their own function even if it does nothing. This removes the no-op functions to reduce the code size.
For diff in JSv3 as an example, see https://github.com/aws/aws-sdk-js-v3/pull/4544 
(first commit contains a single client for easier viewing).
- for AWS EC2, generation took 4s to 5s both before and after this change.
=> Skip code generation of data filter functions for shapes that do not contain sensitive fields (recursive)

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DefaultReadmeGenerator.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/default_readme_client.md.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/default_readme_server.md.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/DefaultDefaultReadmeGeneratorTest.java
(See previous closed PR https://github.com/awslabs/smithy-typescript/pull/584, opening a new PR from fork repo)
* Added DefaultReadmeGenerator
* Added `createDefaultReadme` in TypeScriptSettings (defaults to `false`)
* This generates a default README.md if `createDefaultReadme` is set  to true in `smithy-build.json`.
* Validated README.md is created in both SDK and SSDK (via `smithy-typescript-ssdk-demo`)
See client and server `README` examples below:
---
SDK for JavaScript Weather Client for Node.js, Browser and React Native.
Provides weather forecasts.
To install the this package, simply type add or install weather
using your favorite package manager:
- `npm install weather`
- `yarn add weather`
- `pnpm add weather`
To send a request, you only need to import …
=> Add DefaultReadmeGenerator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGeneratorTest.java
Generate a structural hint instead of only 
```js
const command = new StartQueryExecutionCommand(input);
```
for commands.
Example:
```js
/**
* const client = new AthenaClient(config);
* const input = {
*   QueryString: "STRING_VALUE", // required
*   ClientRequestToken: "STRING_VALUE",
*   QueryExecutionContext: {
*     Database: "STRING_VALUE",
*     Catalog: "STRING_VALUE",
*   },
*   ResultConfiguration: {
*     OutputLocation: "STRING_VALUE",
*     EncryptionConfiguration: {
*       EncryptionOption: "SSE_S3" || "SSE_KMS" || "CSE_KMS", // required
*       KmsKey: "STRING_VALUE",
*     },
*     ExpectedBucketOwner: "STRING_VALUE",
*     AclConfiguration: {
*       S3AclOption: "BUCKET_OWNER_FULL_CONTROL", // required
*     },
*   },
*   WorkGroup: "STRING_VALUE",
* …
```
=> add structural hint to command examples

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGeneratorTest.java
You can see that some shapes get quite long, CLI example: https://docs.aws.amazon.com/cli/latest/reference/quicksight/update-template.html
JSv3 API example: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-quicksight/classes/updatetemplatecommand.html
----
This PR aims to improve the recently implemented structural hint doc generation.
- more aggressive truncation for repeated shapes
- truncated item shows the target shape name instead of its entire structure
- the name appears earlier in the shape hint
example, original shape appearance with name tag and then subsequent repeated shape truncation
```
{
myShape: { // MyShape
field1: "STRING_VALUE",
field2: "STRING_VALUE"
},
myShape2: "<MyShape>"
}
```
JSv3 diff in https://github.com/aws/aws-sdk-js-v3/pull/4585/files
=> improve documentation truncation behavior

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentShapeSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/ProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java
Shorten generated serde function names. Source code contains a comment with the original long name, distribution uses shorter names.
The premise is that serde function names do not need to contain the protocol -- it's repetitive when the protocol file containing the functions is named after the protocol already. 
JSv3 codegen paired PR https://github.com/aws/aws-sdk-js-v3/pull/4611
Benefits:
reduced code size
Potential Downsides:
- breaking change for anyone is using these internal functions directly (though no one should be). 
- no benefit to anyone who was applying mangling already (most browser applications, some server applications).
Example
```js
/**
* deserializeAws_restJson1PrefetchConsumption
*/
const de_PrefetchConsumption = ...
```
=> shorten internal serde fn names

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
`dist-*` doesn't work with `npm@9` and nothing is packed.
This commit fixes `files` to a proper glob pattern so that `npm pack`
can include all files with `npm@9`.
```
vscode ➜ .../smithyprojections/smithy/source/typescript-codegen (main) $ npm pack
npm notice 
npm notice 📦  smithy@0.0.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE     
npm notice 3.1kB  package.json
...
npm notice total files:   2                                       
```
```
vscode ➜ .../smithyprojections/smithy/source/typescript-codegen (main) $ npm pack
npm notice 
npm notice 📦  smithy@0.0.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE                                      
npm notice 172B   dist-cjs/commands/index.js                   
npm notice 1.6kB …
```
=> Use updated dist glob pattern in package.json

smithy-typescript-ssdk-libs/server-common/CHANGELOG.md, smithy-typescript-ssdk-libs/server-common/src/unique.spec.ts, smithy-typescript-ssdk-libs/server-common/src/unique.ts, smithy-typescript-ssdk-libs/server-common/src/validation/validators.spec.ts
*Description of changes:* I'm explicitly adding handling and test cases for scenarios where `undefined` and `null` values are passed.
I also added a new validation test for restJson1:
```
● RestJsonMalformedUniqueItemsStructureMissingKeyList:MalformedRequest
expect(received).toBe(expected) // Object.is equality
Expected: 400
Received: 500
4818 |
4819 |   expect(testFunction.mock.calls.length).toBe(0);
> 4820 |   expect(r.statusCode).toBe(400);
|                        ^
4821 |   expect(r.headers["x-amzn-errortype"]).toBeDefined();
4822 |   expect(r.headers["x-amzn-errortype"]).toBe("ValidationException");
4823 |
at Object.<anonymous> (test/functional/restjson1.spec.ts:4820:24)
```
Locally, after `yarn link`ing the new changes, the error is gone which indicated that the regression has been …
=> Fix the `uniqueItems` implementation to accomodate undefined values nested inside lists of objects

.changeset/config.json, .github/workflows/ci.yml, .github/workflows/release-npm-packages.yml, .github/workflows/release-npm-ssdk-libs.yml
This PR moves the existing `release.yml` to be an SSDK-libs-specific workflow and adds a new release workflow that will publish changes to NPM packages that will be added to the `/packages` directory. Changes to packages in this directory can be released in an automated fashion, since the workflow will run `yarn changeset version` which will update the version numbers and add changelogs according to the changeset entries defined. See: https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#version
Additionally, it updates the CI workflow to check that each PR has the proper changeset entry defined and included in the PR's commits. By running `yarn changeset status --since=origin/main`, the `ensure-typescript-packages-have-changeset` step will check that when any …
=> Add NPM packages release workflow

.github/workflows/release-npm-packages.yml, .github/workflows/release-npm-ssdk-libs.yml
Fixes the NPM token name used in the NPM package release workflows.
=> Fix release workflows

.changeset/config.json
Sets NPM publish access to `public`.  See: https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#access-restricted--public
=> Fix npm publish access

.gitignore, package.json, packages/protocol-http/package.json, packages/types/package.json, smithy-typescript-ssdk-libs/server-apigateway/package.json, smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/server-node/package.json, turbo.json
This PR adds a `stage-release` script which is run as part of the `release` script.
Before `yarn changeset publish` can be invoked by the release script, yarn needs to handle converting the `workspace:^` entries in each package's package.json into a real version number. The `stage-release` script invokes `yarn pack` which performs this conversion while packing the contents into a `package.tgz` file. The contents of the packed package are then unpacked into a `.release` directory, which is used for publishing. Turbo will assure that `yarn build` is successfully run before attempting to stage the release contents to `.release`.
=> yarn pack before releasing

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
This PR updates the enum validator to not remove an enum shape member from the validation message if it has been tagged as "internal". Instead, only enum shape members with the `@internal` trait will be suppressed from the validation message.
See https://github.com/awslabs/smithy/pull/1746.
=> Do not suppress on tagged internal enum shape member

CHANGELOG.md, README.md, build.gradle.kts
Bump code generator version to 0.15.0.
=> Bump version to 0.15.0

.gitignore, CONTRIBUTING.md, settings.gradle.kts
Add gradle composite build
Validate local dependency changes are included automatically when `local.properties` exists
=> Add gradle composite build

CHANGELOG.md, README.md, build.gradle.kts
This reverts commit 7a522f31ae32d27678e1242680225e00414f514e.
Re-applies version bump to `0.15.0` with updated CHANGELOG.
=> Revert "Revert "Bump version to 0.15.0 (#751)" (#758)"

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
This reverts commit 4f16c8bba722d61635b0ce51acb84be8728376ac.
This commit temporarily reverts the change from https://github.com/awslabs/smithy-typescript/pull/741.
That change is only compatible with the protocol test changes in Smithy 1.31.0. This change specifically: https://github.com/awslabs/smithy/pull/1746
This change should be re-introduced when upgrading to Smithy 1.31.0.
=> Revert "Do not suppress on tagged internal enum shape member"

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptWriterTest.java
This PR adds a new `addImport` method to TypeScriptWriter, and deprecates the existing `addImport` method.
Currently, `addImport` is used like this:
```
writer.addImport("Foo", "__Foo", "@aws-sdk/foo");
```
Or like this:
```
writer.addImport("Foo", "__Foo", TypeScriptDependency.AWS_SDK_FOO.packageName);
```
The new method will allow for this simplified usage:
```
writer.addImport("Foo", "__Foo", TypeScriptDependency.AWS_SDK_FOO);
```
=> Add updated addImport method

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptWriterTest.java
Additional change to go with https://github.com/awslabs/smithy-typescript/pull/767.
This adds a separate, `addRelativeImport`, method which should be used exclusively to import relative paths.
Between this method, `addRelativeImport`, and the `addImport` method added in https://github.com/awslabs/smithy-typescript/pull/767, any instances of `writer.addImport("Foo", "__Foo", "@aws-sdk/foo");` can be updated.
=> Add addRelativeImport method

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ApplicationProtocol.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddDefaultsModeDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
This PR updates the generated code to use the `@smithy` scoped `types` and `protocol-http` packages that were added to the `/packages` directory. For now, generated clients will continue to depend on `@aws-sdk/types` package, but `@aws-sdk/protocol-http` is completely replaced by the package migrated to `@smithy/protocol-https`.
=> Use @smithy scoped packages

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java
Fix for https://github.com/awslabs/smithy-typescript/pull/766.
Changes SerdeContext import on EventStreamGenereator.
=> Update EventStream SerdeContext import

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
Previously, server request deserializers would trim leading and trailing whitespace of output query parameter values. This PR stops that, so the whitespace is preserved as part of the query value.
Tested using JS SDK. All protocol tests continue to pass, there is a codegen diff.
This PR is required for https://github.com/awslabs/smithy/pull/1759
=> Do not trim collection query param output values

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddBaseServiceExceptionClass.java
1. Add packageDocumentation trait with service documentation
2. Export types used in inheritance chain to allow documentation to follow the entire chain
1.  export imported types to allow them to be inherited
2. export default types to allow them to be inherited
=> Add packageDocumentation and improve interface inheritance

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
if a static context param is already using a name, avoid writing it for subsequent lower priority params.
This was already in place for context, client, and built-ins, just missed for static context to context.
For context, no current AWS SDK models have this collision, it was noticed in a feature under development.
=> fix endpoint parameter name conflict

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java
Currently all endpoint param types encountered by JSv3 (AWS) are capitalized, however a new feature introduced a lowercase param type "string". Checking the internal specification, this appears to be something that should be accepted.
Also added a throw on the default branch since the only specified types are string and boolean.
=> Handle case insensitive endpoint param types

.github/workflows/release-npm-packages.yml
Adds a token to the checkout action so that the working repo is setup with the correct token and can perform authenticated git actions, including pushing a commit.
=> Use token for push permissions

.github/workflows/release-npm-packages.yml
Moves using push token to commit step on NPM release workflow.
=> Use push token on commit step

.github/workflows/release-npm-packages.yml
This reverts commit 9100ab1d433bcd71a94416b5343234118f3b409a.
Workflow is already on main. Do not need to checkout main again.
=> Revert "Checkout main before push (#785)"

.github/workflows/release-npm-packages.yml
Use token on checkout for setting up authenticated git permissions.
=> Use token on checkout

.github/workflows/release-npm-packages.yml, .github/workflows/release-npm-ssdk-libs.yml, package.json
This PR updates the GitHub workflows to limit concurrency when staging the NPM packages for release.
`turbo run stage-release` and `turbo run build` will both be invoked with concurrency limited to `1` to avoid overwhelming the GitHub Action runner.
=> Limit concurrency when staging release

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddSdkStreamMixinDependency.java
Updates dependencies to use util-stream package instead of util-stream-node and util-stream-browser, deprecating the two.
This PR is required for ~https://github.com/aws/aws-sdk-js-v3/pull/4787~ https://github.com/aws/aws-sdk-js-v3/pull/4861, which contains more info about testing.
=> Use util-stream package

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
There's a typo in `disableHostPrefix` docstring that found its way to many ([8.9k according to Github](https://github.com/search?q=%22Disable+dyanamically%22&type=code)) lines of code, including https://github.com/aws/aws-sdk-js-v3. This PR fixes the typo.
=> fix: fix a typo in disableHostPrefix docstring

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CodegenUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-xml-stub.ts
https://github.com/aws/aws-sdk-js-v3/issues/4786
https://github.com/aws/aws-sdk-js-v3/issues/4265
Blob types enhancements
- on the client input side, operation input members with type blob and trait HttpPayload have been widened from `Uint8Array` to `BlobTypes`, which contains common and runtime specific types.
```ts
export type BlobTypes = string | ArrayBuffer | ArrayBufferView | Uint8Array | RuntimeBlobTypes;
// example Node.js runtime additions
export type RuntimeBlobTypes = Readable | Buffer;
// browser additions
export type RuntimeBlobTypes = Blob | ReadableStream;
```
- on the client output side, operation output members with type blob and trait HttpPayload have been wrapped in `Uint8ArrayBlobAdapter`, which extends the `Uint8Array` native class and adds a convenient …
=> widen blob payload input types, add blob payload output converter

.github/workflows/ci.yml
Fixes CI to check for changesets on PRs.
This PR includes a dummy commit to verify that the missing changeset causes CI to fail at the right spot.
=> Fix changesets CI

.changeset/famous-walls-explain.md
Bumps versions on node-http-handler and related packages following change in https://github.com/awslabs/smithy-typescript/pull/794
=> Bump node-http-handler

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceAggregatedClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/WaiterGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParametersVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddChecksumRequiredDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddSdkStreamMixinDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java
Updates codegen to use `addImport` method added in https://github.com/awslabs/smithy-typescript/pull/767 and `addRelativeImport` method added in https://github.com/awslabs/smithy-typescript/pull/768.
Some `addImport` usages were also updated to set the `as` parameter to null.
For example:
`.addImport("fromBase64", "fromBase64", TypeScriptDependency.AWS_SDK_UTIL_BASE64);`
was changed to
`.addImport("fromBase64", null, TypeScriptDependency.AWS_SDK_UTIL_BASE64);`
This makes it more clear that an alias is not needed for this import.
For testing, the js-v3 clients were re-generated and there were no code differences for the generated clients, confirming that this change did not change generated code as expected.
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Standardizes usage of addImport method

.changeset/curvy-roses-walk.md, packages/service-error-classification/src/constants.ts
Fixes: [#4871](https://github.com/aws/aws-sdk-js-v3/issues/4871)
Fixes: [#4872 ](https://github.com/aws/aws-sdk-js-v3/issues/4872)
AbortError is defined as a transient error, which defeats the purposes of aborting mid execution. This causes the retry middleware, to retry even after abort singal was sent. 
This does not affect sending the request itself, as the signal is evaluated by the request handler at invocation time.
Existing Implementation without the change demonstrating retries happening, finally the handler throws abortError.
```js
import { Lambda } from "@aws-sdk/client-lambda";
import { StandardRetryStrategy } from "@aws-sdk/util-retry";
const abortSignal = AbortSignal.timeout(1_000);
const lambdaClient = new Lambda({
region: 'us-west-2',
retryStrategy: new …
```
=> Remove AbortError from the list of transient error codes

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
This PR updates codegen to use the NPM version updates from https://github.com/awslabs/smithy-typescript/commit/82f8e0ac8010ac80a38c496137e67b59bdb14c45
=> Update NPM deps on codegen

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
*Issue #, if available:* N/A
Replace non-existent version with `1.0.0-alpha.10` for `@aws-smithy/server-common` package.
=> fix(codegen): replace mismatch version for server-common

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java
This reverts commit cbe312126a55bc993d96640a7a33feb734fbc930.
This PR re-introduces the change that was temporarily reverted in https://github.com/awslabs/smithy-typescript/pull/765.
This will allow https://github.com/aws/aws-sdk-js-v3 to upgrade to the latest version of smithy (currently 1.33.0).
=> Revert "Revert "Do not suppress on tagged internal enum shape member""

.changeset/red-rocks-judge.md, packages/hash-blob-browser/package.json, yarn.lock
https://github.com/aws/aws-sdk-js-v3/issues/4631
Adds back the chunked-blob-reader-native dependency. It was removed in https://github.com/aws/aws-sdk-js-v3/pull/4571 because it wasn't being used in the TS code anywhere, but it is depended on in the package.json [here](https://github.com/aws/aws-sdk-js-v3/blob/797001ffd8bd81595049c6271167891e01b419c1/packages/hash-blob-browser/package.json#L38)
=> Add back missing dependency

.github/PULL_REQUEST_TEMPLATE.md
Adds note to PR template on using `yarn changeset add` when modifying any of the NPM packages in the `/packages` directory.
=> Add changeset instructions to PR template

CONTRIBUTING.md
Update `CONTRIBUTING.md` to include instructions on using `yarn changeset add` when modifying the NPM packages within the `/packages` directory.
=> Add changeset directions for NPM packages

.changeset/shaggy-avocados-serve.md, packages/property-provider/src/CredentialsProviderError.ts, packages/property-provider/src/ProviderError.ts, packages/property-provider/src/TokenProviderError.ts
https://github.com/aws/aws-sdk-js-v3/issues/4907
https://github.com/aws/aws-sdk-js-v3/issues/4918
Currently, if an error occurs within a provider and it throws an exception that is marked "internal", customers might not have a clear and stable way to identify and handle these exceptions. This can lead to challenges in ensuring that their applications behave correctly when encountering errors during the credential providing process.
Because of this, provider errors should be moved out of the "internal" state, and offered as part of our public API.
---
=> exposing provider errors, since they should be a part of our public API

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.spec.ts
Without this fix, building the generated SSDK fails:
```
$ concurrently 'yarn:build:cjs' 'yarn:build:es' 'yarn:build:types'
$ tsc -p tsconfig.es.json
$ tsc -p tsconfig.types.json
$ tsc -p tsconfig.cjs.json
[build:types] src/middleware/HttpApiKeyAuth/index.spec.ts(4,29): error TS2307: Cannot find module 'smithy/protocol-http' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[build:types] yarn run build:types exited with code 2
[build:es] src/middleware/HttpApiKeyAuth/index.spec.ts(4,29): error TS2307: Cannot find module 'smithy/protocol-http' or its corresponding type declarations.
error Command failed with exit code 2.
info …
```
=> Fix @smithy/protocol-http import in HttpApiKeyAuth spec

.changeset/beige-moons-glow.md, package.json, packages/fetch-http-handler/package.json, packages/hash-blob-browser/package.json, packages/util-stream/package.json, yarn.lock
Bump webpack to 5.76.0.
See https://github.com/awslabs/smithy-typescript/pull/779.
---
=> Bump webpack to 5.76.0

.github/workflows/ci.yml, package.json
This PR adds a build script to package.json which runs the test client codegen and attempts to build the generated TypeScript client. 
`yarn build-test-client` will run codegen and build the resulting generated client.
---
=> Add build script for generated client

build.gradle.kts, settings.gradle.kts, smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen-test/smithy-build.json, smithy-typescript-ssdk-codegen-test-utils/build.gradle.kts, smithy-typescript-ssdk-codegen-test-utils/src/main/java/software/amazon/smithy/typescript/ssdk/codegen/test/utils/AddProtocols.java, smithy-typescript-ssdk-codegen-test-utils/src/main/java/software/amazon/smithy/typescript/ssdk/codegen/test/utils/TestProtocolGenerator.java, smithy-typescript-ssdk-codegen-test-utils/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
This PR adds testing of the `typescript-ssdk-codegen` plugin.
It adds the non-published `software.amazon.smithy.typescript.ssdk.codegen.test.utils` package, which includes an empty `FakeProtocolGenerator` which enables SSDK codegen to succeed since a protocol is required for an SSDK.
Currently, SSDK validation for `@streaming` union shapes is not supported, so the `GetCityAnnouncements` is removed from the generated SSDK since it uses the `@streaming` union `Announcements` shape in its output. Once support for this is added, the operation can be added back to the model.
---
=> Add SSDK codegen test

.changeset/kind-moles-lie.md, packages/property-provider/src/CredentialsProviderError.ts, packages/property-provider/src/ProviderError.ts, packages/property-provider/src/TokenProviderError.ts
Fixes https://github.com/awslabs/smithy-typescript/pull/815
adding back `@public` annotation after removing `@internal` to expose errors
=> fix(property-provider): adding back @public annotation to expose errors

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
Fixes codegen to use @smithy/types instead of @aws-sdk/types.
---
=> Fix types import

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/integration/http-api-key-auth.spec.ts, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/vite.config.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/PackageJsonGeneratorTest.java
This PR updates codegen to write a `test` script and vite.config.ts file when a spec has been generated.
For example, the `AddHttpApiKeyAuthPlugin` writes a generated spec file, and now adds a dependency on `vitest`. A test script and vite.config.ts are now added when this plugin is used so that the spec can easily be run with `yarn test` within the generated SSDK package.
It also converts the spec generated to use vitest, replacing jest.
---
=> Add test script when specs are generated

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/vite.config.js
Move vitest.config.ts to vitest.config.js to avoid this file getting built and included in the `dist-*` outputs.
---
=> Move vitest config to js

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageContainer.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
This PR adds a `PackageContainer` interface and updates TypeScriptWriter's `addImport` method to use it.
This will allow downstream Dependency classes to implement `PackageContainer` for better `addImport` usage without passing just strings.
---
=> Add PackageContainer interface

.changeset/clean-waves-sort.md, .gitignore, api-extractor.json, api-extractor.packages.json, package.json, packages/types/api-extractor.json, packages/types/package.json, scripts/set-api-extractor.js, turbo.json, yarn.lock
enables running `yarn extract:docs` in the root for `/packages`. 
Outputs to non-versioned `api-extractor-packages` folder. Will be used to explore options for adding smithy packages to the JSv3 api docs pages.
(many packages already had api-extractor configs leftover from JSv3 but they did nothing without the devDep available)
=> enable api-extractor

build.gradle.kts
Updates build.gradle.kts to include resource files in source jars.
See same change in https://github.com/smithy-lang/smithy/pull/1877.
---
=> Include resource files in source jars

.changeset/quiet-adults-deny.md, packages/types/package.json
set all packages back onto the types@1.x line, and create another version of types in the 1.x line
=> fix: advance types@1.x line

.changeset/shiny-starfishes-sparkle.md, packages/types/package.json, packages/types/scripts/downlevel.js, packages/types/src/downlevel-ts3.4/transform/type-transform.ts, packages/types/src/transform/type-transform.spec.ts
=> fix: custom ts3.4 downlevel for transform/type-transform

.changeset/ten-frogs-help.md, packages/config-resolver/api-extractor.json, packages/config-resolver/package.json, packages/config-resolver/src/endpointsConfig/resolveCustomEndpointsConfig.ts, packages/config-resolver/src/endpointsConfig/resolveEndpointsConfig.ts, packages/config-resolver/src/regionConfig/resolveRegionConfig.ts, packages/eventstream-serde-config-resolver/api-extractor.json, packages/eventstream-serde-config-resolver/package.json, packages/eventstream-serde-config-resolver/src/EventStreamSerdeConfig.ts, packages/middleware-apply-body-checksum/src/md5Configuration.ts, packages/middleware-endpoint/api-extractor.json, packages/middleware-endpoint/package.json, packages/middleware-endpoint/src/index.ts, packages/middleware-endpoint/src/resolveEndpointConfig.ts, packages/middleware-retry/src/configurations.ts, packages/smithy-client/src/client.ts, packages/smithy-client/src/defaults-mode.ts, packages/types/src/client.ts, packages/types/src/response.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/IndexGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
for types that comprise the client initialization api, set the release tag to `@public` so that the api doc pages for JSv3 include them.
merge with: https://github.com/aws/aws-sdk-js-v3/pull/5018
=> docs: set public release tags on client config interface components

.changeset/clever-spies-change.md, packages/signature-v4/src/getCanonicalQuery.spec.ts, packages/signature-v4/src/getCanonicalQuery.ts
This solves the issue #848.
As stated in the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request) on signing API requests (emphasis in mine),
> `CanonicalQueryString` – The URL-encoded query string parameters, separated by ampersands (&). Percent-encode reserved characters, including the space character. Encode names and values separately. If there are empty parameters, append the equals sign to the parameter name before encoding. **After encoding, sort the parameters alphabetically** by key name. If there is no query string, use an empty string ("").
- sort the parameter values after encoding in `getCanonicalQuery`,
- test the associated edge case.
---
By submitting this pull request, I confirm …
=> fix: sort query parameter values after encoding

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java
The return value of `writeReleaseTag(member, docs);` was being ignored in one instance.
I changed the (private) method name to something other than "write", so as not to imply it calls the writer itself.
=> docs: fix missing release tag on shape members

.changeset/curvy-pumas-return.md, packages/types/src/client.ts, packages/types/src/util.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/3415
Adds type to check optional Client Configuration.
Testing done in generated code in https://github.com/aws/aws-sdk-js-v3/pull/5060
---
=> Add type to check optional Client Configuration

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
Refs: https://github.com/aws/aws-sdk-js-v3/issues/3415
Adds check for Optional Configuration in client constructor
---
=> Check for Optional Configuration in client constructor

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPlugin.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/RuntimeClientPluginTest.java
N/A.
Enable `RuntimeClientPlugin`s to be filtered based on settings, and filter at the top-level of `DirectedTypeScriptCodegen`.
See previously closed PR: awslabs/smithy-typescript#684
*Testing:*
1. smithy-typescript: `./gradlew clean build check` builds successfully
2. aws-sdk-js-v3: `yarn generate-clients` builds successfully and produces no codegen diff.
---
=> Add `matchSettings()` to `RuntimeClientPlugin`s

CONTRIBUTING.md, smithy-typescript-codegen-test/smithy-build.json, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java
N/A.
Dependent on #856.
Add the experimental feature flag for identity and auth `experimentalIdentityAndAuth` in `TypeScriptSettings`.
- For `AddHttpApiKeyAuthPlugin`, make the current behavior the control branch for `experimentalIdentityAndAuth`.
- Add a test projection in `smithy-typescript-codegen-test` for `experimentalIdentityAndAuth`.
Also, add a section in `CONTRIBUTING.md` about experimental features in `smithy-typescript`.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Add `experimentalIdentityAndAuth` flag

.changeset/gold-nails-end.md, packages/types/src/extensions/checksum.ts, packages/types/src/extensions/defaultClientConfiguration.ts, packages/types/src/extensions/index.ts, packages/types/src/index.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ClientConfigurationGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/Dependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeExtensionsGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/ClientConfigurationInterface.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/DefaultClientConfigurationInterface.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/clientConfiguration.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeExtensions1.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeExtensions2.template
This PR adds `extensions: RuntimeExtension[]` to client runtime config.
```
interface S3ClientConfiguration extends DefaultClientConfiguration,  AwsClientConfiguration, ... {
}
interface RuntimeExtension {
configureClient(clientConfiguration: S3ClientConfiguration): void;
}
```
The service client can be configured by implementing the `RuntimeExtension` interface. `*ClientConfiguration` is an interface that includes settings that can be modified on the service client. Because services have different configuration, each service has a code-generated ClientConfiguration interface implementation. Service owner can compose multiple client configurations by implementing `TypeScriptIntegration.getClientConfigurationInterfaces`
Using S3 as an example:
``` 
export class …
```
=> Add extensions to client runtime config

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
Version bump to consume changes in https://github.com/awslabs/smithy-typescript/pull/852
```console
$ node scripts/update-codegen-package-versions.js
```
Bump @smithy packages to use Extensions
---
=> Bump @smithy packages to use Extensions

.changeset/empty-eyes-remember.md, packages/types/src/extensions/checksum.ts
Address issue https://github.com/awslabs/smithy-typescript/issues/865 
---
=> Remove symbol as an index from ChecksumConfiguration interface in @smithy/types

package.json, scripts/build-generated-test-packages.js, scripts/utils/spawn-process.js
This PR removes the generated test client and SSDK packages from the yarn workspace.
Previously, these packages were added to the workspace so that they could be built using yarn commands, e.g. `yarn build --filter=weather`.
This had the side-effect of different yarn.lock files, depending on whether or not the test client and SSDK packages had been generated with `./gradlew clean build`.
By removing them from the workspace, they will not influence the yarn.lock file. In order for the generated client and SSDK packages to be used in integration tests, a script is added to build, pack and copy the generated packages into node_modules.
---
=> Remove generated packages from workspace

.github/workflows/ci.yml
This PR updates CI to run integration tests.
The separate `build-generated-client-and-ssdk` job is removed. That job exercised `yarn build-test-packages`, which is now run before integration tests since those those tests rely on the generated package.
---
=> Run integration tests on CI

smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java
N/A.
Add more auth traits to generic client tests.
Note that the `smithy-aws-traits` dependency is added for including
`@aws.auth#sigv4`, which will have generic client support. This should
not affect packaging of `smithy-typescript-codegen` since these tests
are in `smithy-typescript-codegen-test`.
Also, simplify `AddHttpApiKeyAuthPlugin` control path for computing whether `@httpApiKeyAuth` is supported on a service and operation.
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> feat(experimentalIdentityAndAuth): add more auth traits to generic client tests

.changeset/long-apricots-end.md, packages/smithy-client/src/extensions/checksum.ts, packages/smithy-client/src/extensions/defaultClientConfiguration.ts, packages/smithy-client/src/extensions/index.ts, packages/types/src/extensions/defaultClientConfiguration.ts, packages/types/src/extensions/index.ts, turbo.json
- moves the runtime portions of the extensions feature to `smithy-client`, out of `types`.
- exports extensions-related types from `types` pkg to be used in `smithy-client`.
=> move extensions runtime code to smithy-client

.changeset/eighty-rivers-rush.md, packages/util-body-length-node/src/calculateBodyLength.spec.ts, packages/util-body-length-node/src/calculateBodyLength.ts
supercedes https://github.com/aws/aws-sdk-js-v3/pull/2637
=> fix(util-body-length-node): calculateBodyLength for Readable stream with range

.changeset/eight-pandas-worry.md, packages/property-provider/src/chain.spec.ts, packages/property-provider/src/chain.ts
Fixes https://github.com/awslabs/smithy-typescript/issues/896.
This issue was originally reported in https://github.com/aws/aws-sdk-js-v3/issues/2263 and fixed in https://github.com/aws/aws-sdk-js-v3/pull/4843. This PR copies that fix to the @smithy/property-provider package.
---
=> Fix generating default rejected promise when chaining

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/TypeScriptIntegration.java
N/A.
Filter `TypeScriptIntegration`s based on `TypeScriptSettings`.
This allows for integrations to be enabled or disabled based on settings
in `smithy-build.json`.
Note that this is annotated as a Smithy Internal API, and may be removed
at any point.
---
=> Add `matchSettings()` to `TypeScriptIntegration` and `TypeScriptCodegenPlugin`

CONTRIBUTING.md
Refs: https://github.com/aws/aws-sdk-js-v3/pull/5146
Add instructions to generate AWS SDK clients in CONTRIBUTING.md
---
=> Add instructions to generate AWS SDK clients in CONTRIBUTING.md

.changeset/unlucky-tigers-raise.md, packages/shared-ini-file-loader/src/getHomeDir.spec.ts, packages/shared-ini-file-loader/src/getHomeDir.ts
Refs: https://github.com/aws/aws-sdk-js-v3/issues/4345
Caches value returned by `os.homedir()` to attempt fixing EMFILE errors with `uv_os_homedir`
---
=> fix(shared-ini-file-loader): cache value returned by os.homedir()

.changeset/thirty-ants-wash.md, packages/experimental-identity-and-auth/package.json, packages/experimental-identity-and-auth/src/apiKeyIdentity.ts, packages/experimental-identity-and-auth/src/httpApiKeyAuth.ts, packages/experimental-identity-and-auth/src/index.ts, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, yarn.lock
N/A.
**NOTE: All of these are under the `experimentalIdentityAndAuth` feature flag**
**NOTE: Dependent on https://github.com/awslabs/smithy-typescript/pull/881**
- Adding config properties `apiKey`:
```typescript
/**
* The API key to use when making requests.
*/
apiKey?: ApiKeyIdentity | ApiKeyIdentityProvider;
```
- `@smithy/experimental-identity-and-auth` package: add the `ApiKeyIdentity` interface and `ApiKeyIdentityProvider` type, `HttpApiKeyAuthLocation` enum, and default `HttpApiKeyAuthSigner` implementation.
- Add back operations that support `@httpApiKeyAuth` in the generic client test
*Testing:*
- `@httpApiKeyAuth` client codegen diff given the following model changes: https://gist.github.com/syall/a595c7738c380176a528ff29016f1c2c …
=> feat(experimentalIdentityAndAuth): Add generic `@httpApiKeyAuth` support

.changeset/wild-years-leave.md, packages/experimental-identity-and-auth/src/httpBearerAuth.ts, packages/experimental-identity-and-auth/src/index.ts, packages/experimental-identity-and-auth/src/tokenIdentity.ts, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpBearerAuthPlugin.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
N/A.
**NOTE: All of these are under the `experimentalIdentityAndAuth` feature flag**
**NOTE: Dependent on https://github.com/awslabs/smithy-typescript/pull/881**
- Adding config properties `token`:
```typescript
/**
* The token used to authenticate requests.
*/
token?: TokenIdentity | TokenIdentityProvider;
```
- `@smithy/experimental-identity-and-auth` package: add the `TokenIdentity` interface and `TokenIdentityProvider` type (these are still only in `@aws-sdk/types` currently), and default `HttpBearerAuthSigner` implementation.
- Add back operations that support `@httpBearerAuth` in the generic client test
*Testing:*
- `@httpBearerAuth` client codegen diff given the following model changes: …
=> feat(experimentalIdentityAndAuth): Add generic `@httpBearerAuth` support

.changeset/chilled-lies-care.md, packages/smithy-client/src/extensions/checksum.ts, packages/smithy-client/src/extensions/defaultExtensionConfiguration.ts, packages/smithy-client/src/extensions/retry.ts, packages/types/src/extensions/defaultExtensionConfiguration.ts, packages/types/src/extensions/index.ts, packages/types/src/extensions/retry.ts
This PR adds retry component to the runtime extensions. 
Using S3 as an example:
```
export class CustomRetryExtension implements RuntimeExtension {
configure(extensionConfiguration: S3ExtensionConfiguration): void {
extensionConfiguration.setRetryStrategy(...);
}
}
// extensions can be passed via the client constructor object
S3Client({
...
extensions: [CustomRetryExtension()]
})
```
---
=> Add retry to runtime extension

.changeset/shy-kids-call.md, package.json, packages/fetch-http-handler/src/fetch-http-handler.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.ts, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.spec.ts, packages/node-http-handler/src/node-http2-handler.ts, packages/protocol-http/src/extensions/httpExtensionConfiguration.ts, packages/protocol-http/src/extensions/index.ts, packages/protocol-http/src/httpHandler.ts, packages/protocol-http/src/index.ts, packages/util-stream/src/util-stream.integ.spec.ts, private/util-test/src/test-http-handler.ts
This PR adds http client component to the runtime extensions. 
Using S3 as an example:
```
export class CustomHttpExtension implements RuntimeExtension {
configure(extensionConfiguration: S3ExtensionConfiguration): void {
extensionConfiguration.setHttpHandler(...);
extensionConfiguration.updateHttpClientConfig("requestTimeout", requestTimeout);
}
}
// extensions can be passed via the client constructor object
S3Client({
...
extensions: [CustomHttpExtension()]
})
```
---
=> Add http client component to runtime extension

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java
N/A.
Currently, extension configuration code is being generated for SSDK even though it only affects clients.
This change changes it so it only generates for clients.
---
=> Update `ExtensionConfiguration`s to generate for clients only

.changeset/many-plums-agree.md, packages/shared-ini-file-loader/src/getHomeDir.ts
Windows doesn't have `geteuid` so import statement will fail running in ESM. We can assume that targets that have `geteuid` also have process in global scope.
---
=> Explicitly check for process.geteuid from global scope

.changeset/forty-shrimps-act.md, packages/config-resolver/package.json, packages/middleware-retry/package.json
Refs: https://github.com/aws/aws-sdk-js-v3/issues/3109
Move packages with type imports to deps.
It's already done in:
* https://github.com/awslabs/smithy-typescript/blob/b0392a75e6328aef7802239d81a233455623bf43/packages/util-defaults-mode-node/package.json#L27
* https://github.com/awslabs/smithy-typescript/blob/b0392a75e6328aef7802239d81a233455623bf43/packages/credential-provider-imds/package.json#L29
---
=> fix(packages): move @smithy/node-config-provider to deps

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/ExtensionConfigurationInterface.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/extensions/HttpHandlerExtensionConfigurationInterface.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddClientRuntimeConfig.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/resolveRuntimeExtensions1.template
=> Add codegen for http component in runtime extension

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ConfigField.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpBearerAuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddSigV4AuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthExtensionConfigurationInterface.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthRuntimeExtensionIntegration.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration
N/A.
Add code-generation for `HttpAuthExtensionConfiguration`, which allows
configuring:
- `httpAuthSchemes`
- `httpAuthSchemeProvider`
- Any `ConfigField` registered by `HttpAuthScheme`s
Also, add relative import dependencies for:
- `httpAuthSchemeProvider`
- `httpAuthExtensionConfiguration`
Dependent on: https://github.com/awslabs/smithy-typescript/pull/907
*Testing:*
Everything is gated by `experimentalIdentityAndAuth`.
Codegen diff in `smithy-typescript-codegen-test`: https://gist.github.com/syall/34efebcfb7ffa41dcebd0a40fdd30cf7#file-pr-910-diff
The `HttpAuthExtensionConfiguration` specific for a service looks like this:
```diff
diff --color -Nur smithy-typescript-codegen-test/build/smithyprojections/smithy-typescript-codegen-test/con …
```
=> feat(experimentalIdentityAndAuth): add codegen for `HttpAuthExtensionConfiguration`

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
N/A.
Update protocol test stub to implement `HttpHandler`.
---
=> fix(protocol-tests): fix protocol test `HttpHandler`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
N/A.
Update `TypeScriptDependency` codegen versions.
```shell
node ./scripts/update-codegen-package-versions.js
```
*Testing*
1. checkout `aws-sdk-js-v3`
2. Run: `yarn generate-clients && yarn`
3. Corresponding js-v3 CodeBuild CI passes: https://us-west-2.codebuild.aws.amazon.com/project/eyJlbmNyeXB0ZWREYXRhIjoiYkthUUxndUkzQ2FreVlQVlFaUmM2RWU4SXFrd3VwbStjcGZ5NXhORjFlQ1BnTlU5RmFJcmdwU2FnSGRhdmo0dVhudlM2Tm1rTG02U1NMaGkydU5LZUFiQlNPSTh6cXVxN1Zta2pMdkhINTduIiwiaXZQYXJhbWV0ZXJTcGVjIjoiblFJTmhOdFkzZ2FEZXZSaCIsIm1hdGVyaWFsU2V0U2VyaWFsIjoxf …
=> Update TypeScript codegen dependencies

.changeset/lazy-days-jam.md, packages/types/src/pagination.ts
fixes https://github.com/aws/aws-sdk-js-v3/issues/2610
the paginators generate with an undefined return type, not `T`.
supercedes https://github.com/aws/aws-sdk-js-v3/pull/2611
supercedes https://github.com/awslabs/smithy-typescript/pull/389
=> fix: pagination return type

.changeset/old-fans-thank.md, packages/middleware-retry/README.md
This PR updates the README of middleware-retry to link to retry documentation on the util-retry package.
---
=> Link to util-retry for docs

.changeset/eleven-kids-decide.md, .changeset/green-goats-stare.md, packages/types/package.json, packages/types/src/extensions/checksum.ts
This PR fixes the following 2 issues:
* Before TS 4.4, TS does not allow the index signature as union type. Consuming library with this interface will cause error.  This issue was fixed in TS 4.4: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#symbol-and-template-string-pattern-index-signatures. Fixing this issue so it won't break users with TSC < 4.4
```
"TS1337: An index signature parameter type cannot be a union type. Consider using a mapped object type instead. 
[other: string | number]: any;". 
```
* The referred type `ConditionalRecursiveTransformExact<T, FromType, ToType>` uses
conditional generic type that is only supported in TS>=4.1. However the typesVersions
directs consumers' TSC 4.0 to the types with this definition, hence consumers will see …
=> fix: broken ChecksumConfiguration  and ConditionalRecursiveTransformExact interface in TS < 4.4

.changeset/light-goats-compare.md, .changeset/modern-vans-jam.md, packages/types/src/middleware.ts, packages/util-middleware/src/getSmithyContext.ts, packages/util-middleware/src/index.ts
N/A.
- Add Smithy context to `HandlerExecutionContext`
- Add `getSmithyContext()` helper function
---
=> Add Smithy context to `HandlerExecutionContext`

.changeset/gorgeous-rabbits-collect.md, packages/experimental-identity-and-auth/src/HttpAuthScheme.ts, packages/experimental-identity-and-auth/src/HttpAuthSchemeProvider.ts, packages/experimental-identity-and-auth/src/index.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java
N/A.
- Add additional `HttpAuthScheme` interfaces for auth scheme resolution
- Update `HttpAuthSchemeProviderGenerator` to use new interfaces
*Testing:*
Expected diff in the codegen changes in `smithy-typescript-codegen-test`:
```diff
diff --color -Nur smithy-typescript-codegen-test/build_old/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/auth/httpAuthSchemeProvider.ts smithy-typescript-codegen-test/build/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/auth/httpAuthSchemeProvider.ts
--- smithy-typescript-codegen-test/build_old/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/type …
```
=> Add `HttpAuthScheme` interfaces for auth scheme resolution

.changeset/calm-cows-fix.md, packages/types/src/middleware.ts
N/A.
Add `clientName` and `commandName` to `HandlerExecutionContext`.
---
=> Add `clientName` and `commandName` to `HandlerExecutionContext`

.changeset/happy-badgers-travel.md, packages/util-stream/README.md, packages/util-stream/api-extractor.json, packages/util-stream/package.json
closes https://github.com/aws/aws-sdk-js-v3/issues/5069
- adds doc extraction to util-stream because it has public components
=> docs: add api extractor to util-stream

.changeset/heavy-donuts-repair.md, packages/middleware-stack/package.json, packages/service-error-classification/package.json, packages/util-defaults-mode-browser/package.json, packages/util-defaults-mode-node/package.json, packages/util-middleware/package.json, packages/util-retry/package.json, scripts/check-dev-dependencies.js, scripts/utils/walk.js
moves devDeps starting with `@smithy` into deps. Even if imported for types, they should not be in devDeps since they are imported in the runtime code.
=> move runtime packages into deps from devDeps

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java
Resolves https://github.com/awslabs/smithy-typescript/issues/933
Add service and operation names to `HandlerExecutionContext`
Dependent on: https://github.com/awslabs/smithy-typescript/pull/927
*Testing:*
`smithy-typescript-codegen-test`: for the `Weather` service's `CreateCity` command, the following codegen diff is produced:
```diff
diff --color -Nur smithy-typescript-codegen-test/build_old/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/commands/CreateCityCommand.ts smithy-typescript-codegen-test/build/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/commands/CreateCityCommand.ts
--- …
```
=> Add service and operation names to `HandlerExecutionContext`

.changeset/thin-hornets-ring.md, packages/experimental-identity-and-auth/package.json, packages/experimental-identity-and-auth/src/index.ts, packages/experimental-identity-and-auth/src/middleware-http-signing/getHttpSigningMiddleware.ts, packages/experimental-identity-and-auth/src/middleware-http-signing/httpSigningMiddleware.ts, packages/experimental-identity-and-auth/src/middleware-http-signing/index.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpSigningMiddleware.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, yarn.lock
N/A.
Add `httpSigningMiddleware` to authorize and sign requests.
Dependent on: https://github.com/awslabs/smithy-typescript/pull/927, https://github.com/awslabs/smithy-typescript/pull/928
---
=> Add `httpSigningMiddleware` to authorize and sign requests

.changeset/light-foxes-repair.md, packages/middleware-stack/src/MiddlewareStack.ts, packages/types/src/middleware.ts
adds a method `identifyOnResolve(boolean): boolean` to `MiddlewareStack`.
This is useful when needing to see what order the middlewareStack resolves to. This information is not known entirely until the resolve function on the stack is called during an operation.
It can only be logged and not returned because the reference to the cloned stack used to resolve the request is inaccessible.
Example:
```js
import "@aws-sdk/signature-v4-crt";
import { S3, PutObjectCommand } from "@aws-sdk/client-s3";
const client = new S3({
region: "us-west-2",
});
const command = new PutObjectCommand({
Bucket: "arn:aws:s3::....:accesspoint/.....mrap",
Key: "1",
Body: "abcd",
});
command.middlewareStack.identifyOnResolve(true);
try {
const response = await client.send(command);
console.log(response);
} catch …
```
=> add logging to middleware stack

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ConfigField.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthOptionProperty.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeParameter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpApiKeyAuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpBearerAuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddSigV4AuthPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthRuntimeExtensionIntegration.java
N/A.
Refactor `HttpAuthScheme` properties to builders:
- `ConfigField`
- `HttpAuthOptionProperty`
- `HttpAuthSchemeParameter`
---
=> chore(experimentalIdentityAndAuth): refactor `HttpAuthScheme` properties to builders

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java
N/A.
Rename to `generateDefaultHttpAuthSchemeProviderFunction()` from `generateHttpAuthSchemeProviderDefaultFunction()`.
---
=> chore(experimentalIdentityAndAuth): rename to `generateDefaultHttpAuthSchemeProviderFunction()`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthScheme.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java
N/A.
Add `traitId` to `HttpAuthScheme`, which defaults to `schemeId`.
---
=> feat(experimentalIdentityAndAuth): add `traitId` to `HttpAuthScheme`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/SupportedHttpAuthSchemesIndex.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthTypeScriptIntegration.java
N/A.
Add customizing default `httpAuthSchemeProvider` and `httpAuthSchemeParametersProvider`.
---
=> feat(experimentalIdentityAndAuth): add customizing default `httpAuthSchemeProvider` and `httpAuthSchemeParametersProvider`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java
N/A.
Add partial support for `aws.auth#sigv4a`.
If `@aws.auth#sigv4` is effective, and `aws.auth#sigv4a` has a registered supported `HttpAuthScheme`, then add the `aws.auth#sigv4a` auth scheme.
---
=> feat(experimentalIdentityAndAuth): add partial support for `aws.auth#sigv4a`

settings.gradle.kts, smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen-test/example-weather-customizations/build.gradle.kts, smithy-typescript-codegen-test/example-weather-customizations/src/main/java/example/weather/GenericTestAddCustomEndpointsRuntimeConfig.java, smithy-typescript-codegen-test/example-weather-customizations/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, smithy-typescript-codegen-test/model/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
N/A.
Changes to improve and fix codegen for `@smithy.rules#endpointRuleSet`
- add `endpointRuleSet` trait to generic client test
- fix(endpoints): add input / resolved / resolveConfig imports
---
=> Update `@smithy.rules#endpointRuleSet` codegen

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthRuntimeExtensionIntegration.java
N/A.
Add `collect*()` methods to dedupe `ConfigField`s and `HttpAuthSchemeParameter`.
This behavior could have better deduping logic, but that can be addressed in later PRs.
---
=> feat(experimentalIdentityAndAuth): add `collect*()` methods to dedupe `ConfigField`s and `HttpAuthSchemeParameter`

.changeset/witty-planes-reply.md, packages/experimental-identity-and-auth/src/createEndpointRuleSetHttpAuthSchemeProvider.ts, packages/experimental-identity-and-auth/src/index.ts
N/A.
Add `createEndpointRuleSetHttpAuthSchemeProvider()` to generically create `HttpAuthSchemeProvider`s for `@smithy.rules#endpointRuleSet`.
---
=> feat(experimentalIdentityAndAuth): add `createEndpointRuleSetHttpAuthSchemeProvider()` for `@smithy.rules#endpointRuleSet`

.changeset/giant-games-speak.md, .changeset/moody-actors-bake.md, .changeset/slow-pillows-matter.md, packages/experimental-identity-and-auth/package.json, packages/experimental-identity-and-auth/src/IdentityProviderConfig.ts, packages/experimental-identity-and-auth/src/index.ts, packages/experimental-identity-and-auth/src/memoizeIdentityProvider.ts, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/getHttpAuthSchemePlugin.ts, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/httpAuthSchemeMiddleware.ts, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/index.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemeMiddleware.java, smithy-typescript-codegen/src/main/resources/META-INF/services/software.amazon.smithy.typescript.codegen.integration.TypeScriptIntegration, yarn.lock
N/A.
Dependent on: https://github.com/awslabs/smithy-typescript/pull/948, https://github.com/awslabs/smithy-typescript/pull/949
This PR has changes to codegen `httpAuthSchemeMiddleware`.
- Add `memoizeIdentityProvider()` for normalizing and memoizing config identity properties
- Allow `DefaultIdentityProviderConfig` to accept `undefined` properties
- Add the `httpAuthSchemeMiddleware` implementation to select an auth scheme
- Codegen service-specific interface for `HttpAuthSchemeParametersProvider`
- Codegen `httpAuthSchemeMiddleware` and refactor `ConfigField` codegen
- Codegen `httpAuthSchemeMiddleware`, and also generate `resolveHttpAuthSchemeConfig` and input / resolved config interfaces.
- `resolveHttpAuthSchemeConfig` normalizes …
=> Add `httpAuthSchemeMiddleware` to select an auth scheme

.changeset/few-crews-brake.md, packages/middleware-stack/src/MiddlewareStack.spec.ts, packages/middleware-stack/src/MiddlewareStack.ts
in case of multiple versions of middlewareStack existing, external versions may be older and not have the latest method `identifyOnResolve`. 
This should be fixed by installing a consistent and recent version of SDK clients, or specifically `@smithy/middleware-stack`, but if needed, this check can be put in place.
=> Check method before calling external middlewareStack instance

.changeset/strange-shrimps-turn.md, packages/experimental-identity-and-auth/src/endpointRuleSet.ts, packages/experimental-identity-and-auth/src/index.ts
N/A.
Add `createEndpointRuleSetHttpAuthSchemeParametersProvider()` to generically create `HttpAuthSchemeParametersProvider`s for `@smithy.rules#endpointRuleSet`.
---
=> feat(experimentalIdentityAndAuth): add `createEndpointRuleSetHttpAuthSchemeParametersProvider()` for `@smithy.rules#endpointRuleSet`

.changeset/dull-doors-camp.md, .gitignore, packages/fetch-http-handler/src/fetch-http-handler.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.ts
add keepalive option for fetch http handler
supercedes https://github.com/aws/aws-sdk-js-v3/pull/3422
=> feat: keepalive for fetch (browser)

.changeset/tricky-parrots-join.md, packages/types/src/blob/blob-payload-input-types.ts, packages/types/src/externals-check/browser-externals-check.ts, packages/types/src/streaming-payload/streaming-blob-common-types.ts, packages/types/src/streaming-payload/streaming-blob-payload-input-types.ts, packages/types/src/streaming-payload/streaming-blob-payload-output-types.ts, packages/types/src/transform/client-payload-blob-type-narrow.spec.ts, packages/types/src/transform/exact.ts, packages/types/src/transform/type-transform.spec.ts
this resolves the union `ReadableStream | Blob` to `never` if those types are only stubs. 
fixes https://github.com/aws/aws-sdk-js-v3/issues/5237
=> fix: check for existence of browser types

.github/workflows/ci.yml, .github/workflows/release-npm-packages.yml, .github/workflows/release-npm-ssdk-libs.yml, package.json
Similar to how it was done in https://github.com/awslabs/aws-sdk-js-codemod/pull/151
Enable cache for yarn to save couple of minutes in CI
Before cache:
Installation step takes `1m49s`: https://github.com/awslabs/smithy-typescript/actions/runs/6330932816/job/17194434431?pr=967
<details>
<summary>Screenshot</summary>
</details>
After cache:
Installation step takes `25s`: https://github.com/awslabs/smithy-typescript/actions/runs/6331017142/job/17194690623?pr=967
Verified that dependencies are used from cache
<details>
<summary>Screenshot</summary>
</details>
---
=> Enable cache for yarn in GitHub workflows

.changeset/soft-bikes-change.md, packages/middleware-stack/src/MiddlewareStack.spec.ts, packages/middleware-stack/src/MiddlewareStack.ts, packages/types/src/middleware.ts
N/A.
Support `aliases` for `MiddlewareStack`
`aliases` is introduced to enable refactoring of the middleware stack of
existing clients.
Instead of only considering `name` of middlewares, all entries in
`alias` are also considered for actions like adding, removing.
*Testing:*
---
=> Support `aliases` for `MiddlewareStack`

.changeset/mighty-teachers-double.md, packages/experimental-identity-and-auth/src/middleware-http-signing/getHttpSigningMiddleware.ts
N/A.
Add aliases for `httpSigningMiddleware`:
- `@httpApiKeyAuth`: `apiKeyMiddleware`
- `@httpBearerAuth`: `tokenMiddleware`
- `@aws.auth#sigv4`: `awsAuthMiddleware`
---
=> feat(experimentalIdentityAndAuth): add aliases for `httpSigningMiddleware`

yarn.lock
Required for enabling Remote Caching in https://github.com/awslabs/smithy-typescript/pull/972
In local testing, I noticed turbo@1.10.3 does not send request to remote server
Bump turbo to 1.10.14
---
=> Bump turbo to 1.10.14

.changeset/five-ravens-hide.md, packages/fetch-http-handler/src/fetch-http-handler.ts
we don't intend for the fetch-http-client to be used in node, but `fetch` may become progressively more prevalent in Node.js
in browsers, initializing with a blank string does not throw, but in Node.js it does throw invalid URL. To prevent this, I want to initialize the dummy Request with a valid URL. This request is never sent, so any URL would be safe, but to avoid the appearance of preference perhaps we can use ipv6 localhost.
=> fix: use valid dummy URL for Node.js initialization of Request

.changeset/few-panthers-impress.md, packages/shared-ini-file-loader/src/parseIni.spec.ts, packages/shared-ini-file-loader/src/parseIni.ts
* Fixes: https://github.com/awslabs/smithy-typescript/issues/985
* Alternative to https://github.com/awslabs/smithy-typescript/pull/988 without breaking changes
Populates subsection using dot separator in section key when parsing INI files
---
=> Populate subsection using dot separator in section key when parsing INI files

.changeset/fast-colts-drive.md, packages/node-config-provider/src/fromSharedConfigFiles.ts
Internal JS-4281
Pass configuration file as second parameter to configSelector.
This is required if other sections from the configuration need to be read.
---
=> Pass configuration file as second parameter to configSelector

.changeset/sixty-scissors-bake.md, packages/fetch-http-handler/src/fetch-http-handler.browser.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.ts
fixes https://github.com/aws/aws-sdk-js-v3/issues/5334
sets fetch keepalive default to false.
keepalive for fetch has limitations in Chrome described in https://github.com/whatwg/fetch/issues/679
=> fix: default keepalive=false for fetch

scripts/build-generated-test-packages.js
N/A.
Add logging for `buildAndCopyToNodeModules()`.
---
=> Add logging for `buildAndCopyToNodeModules()`

scripts/build-generated-test-packages.js
N/A.
Add `-p` for `mkdir` in `build-generated-test-packages`.
---
=> Add `-p` for `mkdir` in `build-generated-test-packages`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpApiKeyAuthPlugin.java
N/A.
Fix `@httpApiKeyAuth` `scheme` property writer.
---
=> fix(experimentalIdentityAndAuth): fix `@httpApiKeyAuth` `scheme` property writer

.changeset/silent-colts-flow.md, packages/experimental-identity-and-auth/src/middleware-http-signing/httpSigningMiddleware.ts
N/A.
Add await to `signer.sign()` in `httpSigningMiddleware`).
---
=> fix(experimentalIdentityAndAuth): add await to `signer.sign()` in `httpSigningMiddleware`

.changeset/silver-comics-fetch.md, packages/experimental-identity-and-auth/src/httpApiKeyAuth.ts
N/A.
Remove extra `$` from `HttpApiKeyAuthSigner`.
---
=> fix(experimentalIdentityAndAuth): remove extra `$` from `HttpApiKeyAuthSigner`

.changeset/plenty-cycles-boil.md, packages/experimental-identity-and-auth/package.json, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/getHttpAuthSchemeEndpointRuleSetPlugin.ts, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/index.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemeMiddleware.java, yarn.lock
N/A.
*Dependent on: https://github.com/awslabs/smithy-typescript/pull/1002*
Add different `httpAuthSchemeMiddleware` plugins depending on `@endpointRuleSet`.
*Testing:*
```diff
diff --color -Nur /Users/yuasteve/development/ts-ia/smithy-typescript/smithy-typescript-codegen-test/build_old/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/WeatherClient.ts /Users/yuasteve/development/ts-ia/smithy-typescript/smithy-typescript-codegen-test/build/smithyprojections/smithy-typescript-codegen-test/client-experimental-identity-and-auth/typescript-codegen/src/WeatherClient.ts
--- /Users/yuasteve/development/ts-ia/smithy-typescript/smithy-typescript-codegen-test/build_old/smithyprojections/smi …
```
=> fix(experimentalIdentityAndAuth): add different `httpAuthSchemeMiddleware` plugins depending on `@endpointRuleSet`

.changeset/moody-eggs-kiss.md, packages/experimental-identity-and-auth/package.json
N/A.
Move `@smithy/util-test` to `devDependencies`.
---
=> fix(experimentalIdentityAndAuth): move `@smithy/util-test` to `devDependencies`

.changeset/little-doors-live.md, .changeset/tasty-fishes-explain.md, packages/experimental-identity-and-auth/src/httpApiKeyAuth.ts, packages/experimental-identity-and-auth/src/integration/httpApiKeyAuth.integ.spec.ts, scripts/build-generated-test-packages.js, smithy-typescript-codegen-test/model/identity-and-auth/httpApiKeyAuth/HttpApiKeyAuthService.smithy, smithy-typescript-codegen-test/smithy-build.json
N/A.
*Dependent on: https://github.com/awslabs/smithy-typescript/pull/1018, https://github.com/awslabs/smithy-typescript/pull/1021, https://github.com/awslabs/smithy-typescript/pull/1023*
Add `@httpApiKeyAuth` integration tests.
*Testing:*
1. Ran `yarn test:integration`
---
=> feat(experimentalIdentityAndAuth): add `@httpApiKeyAuth` integration tests

.changeset/eleven-lamps-mix.md, .changeset/great-cycles-wave.md, packages/experimental-identity-and-auth/src/httpBearerAuth.ts, packages/experimental-identity-and-auth/src/integration/httpBearerAuth.integ.spec.ts, scripts/build-generated-test-packages.js, smithy-typescript-codegen-test/model/identity-and-auth/httpBearerAuth/HttpBearerAuthService.smithy, smithy-typescript-codegen-test/smithy-build.json
N/A.
*Dependent on: https://github.com/awslabs/smithy-typescript/pull/1018, https://github.com/awslabs/smithy-typescript/pull/1021, https://github.com/awslabs/smithy-typescript/pull/1022*
Add `@httpBearerAuth` integration tests.
*Testing:*
1. Ran `yarn test:integration`
---
=> feat(experimentalIdentityAndAuth): add `@httpBearerAuth` integration tests

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServerCommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
N/A.
Fix operation index file codegen:
- For services with no operations, export an empty module and use
default service input/output types
- Move operation index writing outside of operation loop
---
=> Fix operation index file codegen

.changeset/grumpy-berries-learn.md, packages/middleware-endpoint/package.json, yarn.lock
* Fixes: https://github.com/awslabs/smithy-typescript/issues/1019
* The dependency was used in https://github.com/awslabs/smithy-typescript/pull/1014, but wasn't added in package.json
Add missing dependency of @smithy/shared-ini-file-loader
---
=> Add missing dependency of @smithy/shared-ini-file-loader

.changeset/brave-tips-protect.md, packages/shared-ini-file-loader/src/parseIni.spec.ts, packages/shared-ini-file-loader/src/parseIni.ts
Fixes: https://github.com/awslabs/smithy-typescript/issues/1015
Treat absence of prefix whitespace as section keys when reading ini files
---
=> Treat absence of prefix whitespace as section keys when reading ini files

.changeset/rude-mice-retire.md, packages/shared-ini-file-loader/src/parseIni.spec.ts, packages/shared-ini-file-loader/src/parseIni.ts
Fixes: https://github.com/awslabs/smithy-typescript/issues/1026
Add support to parse profile name with invalid '@' character from ini file
---
=> Parse profile name with invalid '@' character

.changeset/pretty-yaks-fix.md, packages/shared-ini-file-loader/src/parseIni.spec.ts, packages/shared-ini-file-loader/src/parseIni.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5373
Add support to parse profile name with invalid '+' character from ini file
---
=> Parse profile name with invalid '+' character

.changeset/polite-flies-explode.md, packages/types/src/transform/client-payload-blob-type-narrow.spec.ts, packages/types/src/transform/client-payload-blob-type-narrow.ts
there is a type helper that narrows payload types, currently only for outputs
```ts
import { S3 } from "@aws-sdk/client-s3";
import { NodeJsClient } from "@smithy/types";
const s3 = new S3({}) as NodeJsClient<S3>;
await s3.putObject({
Bucket: '',
Key: '',
Body: new Blob() // helper makes this a type error, must use Node.js http(s) payload types like Buffer/Uint8Array/string
})
const get = await s3.getObject({
Bucket: '',
Key: ''
});
const body = get.Body; // helper narrows this to SdkStream<IncomingMessage>
```
this PR adds type narrowing to inputs as well.
=> transform inputs for platform specific type helpers

.changeset/wise-monkeys-leave.md, packages/types/src/endpoints/RuleSetObject.ts
I think this fixes https://github.com/awslabs/smithy-typescript/issues/1048
This catches up the TS types with a recent Java code update.
=> fix: allow lowercase type names for endpoint parameters

.changeset/many-pillows-add.md, packages/util-endpoints/src/types/EndpointRuleObject.ts, packages/util-endpoints/src/types/ErrorRuleObject.ts, packages/util-endpoints/src/types/RuleSetObject.ts, packages/util-endpoints/src/types/TreeRuleObject.ts
Fix for CI error encountered on https://github.com/awslabs/smithy-typescript/pull/1044 due to discrepancy in endpoint types after change in https://github.com/awslabs/smithy-typescript/pull/1050.
---
=> Re-export existing endpoint types

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java
This PR updates codegen to use the util-endpoints package added in https://github.com/awslabs/smithy-typescript/pull/1043.
---
=> Codegen update for util-endpoints

.changeset/afraid-teachers-grab.md, .gitignore, packages/credential-provider-imds/src/error/InstanceMetadataV1FallbackError.ts, packages/credential-provider-imds/src/fromInstanceMetadata.spec.ts, packages/credential-provider-imds/src/fromInstanceMetadata.ts, packages/credential-provider-imds/src/remoteProvider/RemoteProviderInit.ts, packages/credential-provider-imds/src/utils/staticStabilityProvider.ts
this is an AWS-specific feature but the code package is housed here in Smithy-TS at least for the time being.
this PR adds 3 locations from which to shut off the IMDS v1 fallback behavior:
- runtime code initialization of the IMDS or upstream chained credential providers
- AWS config file profile setting
- process environment variable
=> feat(credential-provider-imds): add flag for blocking imds v1 fallback behavior

CHANGELOG.md, build.gradle.kts
Bump codegen version to 0.19.0
---
=> Bump codegen version to 0.19.0

.changeset/weak-pots-know.md, packages/experimental-identity-and-auth/src/middleware-http-auth-scheme/httpAuthSchemeMiddleware.ts
N/A.
Fix typo in `HttpAuthScheme` not enabled message in `httpAuthSchemeMiddleware`.
---
=> fix(experimentalIdentityAndAuth): fix typo in `httpAuthSchemeMiddleware`

.changeset/shiny-beans-wink.md, packages/shared-ini-file-loader/src/parseIni.spec.ts, packages/shared-ini-file-loader/src/parseIni.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5449
Fixes: https://github.com/awslabs/smithy-typescript/issues/1053
Refs: https://github.com/aws/aws-sdk-java-v2/pull/1538
Refs: https://github.com/aws/aws-sdk-java-v2/pull/1898
Allow dot, solidus, percent and colon characters in profile names
---
=> Allow dot, solidus, percent and colon characters in profile names

.changeset/five-houses-jam.md, package.json, packages/hash-blob-browser/package.json, packages/middleware-endpoint/package.json, packages/util-base64/package.json, packages/util-defaults-mode-browser/package.json, packages/util-stream/package.json, packages/util-utf8/package.json, scripts/check-dev-dependencies.js, scripts/package-json-enforcement.js, yarn.lock
This adds a pre-commit hook to audit the pkg json bundler directives.
Specifically, we don't know if a bundler is going to use the CJS or ES entrypoint, and thus the file replacement directives should account for either case.
=> add script for enforcing pkg json standards

.changeset/red-kiwis-prove.md, packages/util-utf8/package.json
Fixes: https://github.com/awslabs/smithy-typescript/issues/1069
Use Node.js implementations in react-native
---
=> fix(util-utf8): use Node.js implementations in react-native

.changeset/eight-files-battle.md, packages/core/package.json
CI is failing due to `jest` running with no tests, e.g. https://github.com/awslabs/smithy-typescript/actions/runs/6856857747/job/18645531179#step:8:69
Fix `@smithy/core` test script.
---
=> Fix `@smithy/core` test script

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java
N/A.
***Unrelated, TypeScript Test CI fails, fix is in another PR: https://github.com/awslabs/smithy-typescript/pull/1072***
Rename `IdentityProviderConfig` variable name `config` to `ipc` since `config` is already used as a top-level function parameter, e.g.
```diff
diff --color -Nur og/src/runtimeConfig.shared.ts new/src/runtimeConfig.shared.ts
--- og/src/runtimeConfig.shared.ts	2023-11-13 19:57:07
+++ new/src/runtimeConfig.shared.ts	2023-11-13 19:57:56
@@ -33,23 +33,23 @@
httpAuthSchemeProvider: config?.httpAuthSchemeProvider ?? defaultWeatherHttpAuthSchemeProvider,
httpAuthSchemes: config?.httpAuthSchemes ?? [{
schemeId: "aws.auth#sigv4",
-        identityProvider: (config: IdentityProviderConfig) =>
- …
```
=> feat(experimentalIdentityAndAuth): rename `IdentityProviderConfig` name to `ipc`

.github/workflows/ci.yml
Use 8-core runner for TypeScript Test CI.
---
=> Use 8-core runner for TypeScript Test step

.changeset/old-trees-wink.md, .changeset/rotten-islands-brake.md, packages/core/package.json, packages/core/src/getSmithyContext.ts, packages/core/src/index.ts, packages/core/src/middleware-http-signing/httpSigningMiddleware.ts, packages/core/src/normalizeProvider.spec.ts, packages/core/src/normalizeProvider.ts, packages/types/src/auth/HttpSigner.ts, scripts/build-generated-test-packages.js
N/A.
Add internal error and success handlers to `HttpSigner` for `experimentalIdentityAndAuth`.
Also add some quality of life improvements:
- Log error message per test client for build failures
- Copy `getSmithyContext()` and `normalizeProvider()` to `@smithy/core`
---
=> feat(experimentalIdentityAndAuth): add internal error and success handlers to `HttpSigner` and QOL changes

README.md
N/A.
Fix README `smithy-build.json` examples.
---
=> Fix README `smithy-build.json` examples

.changeset/shaggy-apes-call.md, packages/smithy-client/src/serde-json.spec.ts, packages/smithy-client/src/serde-json.ts
`_json` is a recursive serde function for the default JSON protocol behavior. It was missing a recursive call when walking through an array type.
=> fix: apply filtering when walking json arrays

.changeset/serious-otters-breathe.md, packages/fetch-http-handler/src/fetch-http-handler.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.ts
followup to https://github.com/smithy-lang/smithy-typescript/pull/1089
makes the signature of the static `create` function more consistent with the instance constructor, allowing an options `Provider` function.
=> align static create and ctor signatures for http handlers

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
when the number is 0, we get `0000` in codegen which is an octal and not a normal integer
=> avoid octal 0 in protocol test

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/PackageJsonGeneratorTest.java
N/A.
Breaking change: typedoc support was previously generated by default,
but this change makes typedoc support opt-in through the
`generateTypeDoc` boolean setting.
For example, you can enable typedoc support by enabling the `generateTypeDoc` flag:
```json
{
"version": "1.0",
"plugins": {
"typescript-client-codegen": {
"package": "weather",
"packageVersion": "0.0.1",
// Enabling typedoc support
"generateTypeDoc": true
}
}
}
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Add `generateTypeDoc` setting for typedoc support

.changeset/sharp-pants-hug.md, packages/shared-ini-file-loader/src/getConfigData.spec.ts, packages/shared-ini-file-loader/src/getConfigData.ts
* Fixes: https://github.com/smithy-lang/smithy-typescript/issues/1053
* Fixes: https://github.com/aws/aws-sdk-js-v3/issues/5521
Validate IniSectionType for profile names containing config prefix separator
*Testing:*
```console
$ cat test.mjs
import { loadSharedConfigFiles } from "../smithy-typescript/packages/shared-ini-file-loader/dist-cjs/index.js";
console.log(await loadSharedConfigFiles());
$ cat ~/.aws/credentials
[foo.bar]
aws_access_key_id = aws_access_key_id
aws_secret_access_key = aws_secret_access_key
[foo@bar]
aws_access_key_id = aws_access_key_id
aws_secret_access_key = aws_secret_access_key
$ cat ~/.aws/config
[profile foo.bar]
region = eu-west-2
[profile foo@bar]
region = eu-west-2
$ node test.mjs
{
configFile: {
'foo.bar': …
```
=> Process config files for profile names containing prefix separator

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/ConfigField.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java
N/A.
Update `ConfigField::configFieldWriter()` to be optional.
---
=> feat(experimentalIdentityAndAuth): update `ConfigField::configFieldWriter()`

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeConfigGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/AuthUtils.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/HttpAuthSchemeProviderGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/HttpAuthRuntimeExtensionIntegration.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddHttpApiKeyAuthPlugin.java
N/A.
Use `TopDownIndex::getContainedOperations()` for operation iterations.
---
=> fix(codegen): use `TopDownIndex::getContainedOperations()` for operation iterations

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddEventStreamDependency.java
N/A.
Add `eventStream` smithy context.
---
=> Add `eventStream` smithy context

.changeset/soft-scissors-brake.md, packages/core/package.json, yarn.lock
We will make the dependencies of core explicit and tighten them.
This will prevent errors with pnpm.
ref
https://github.com/smithy-lang/smithy-typescript/blob/main/packages/core/src/middleware-http-auth-scheme/httpAuthSchemeMiddleware.ts#L16
https://github.com/smithy-lang/smithy-typescript/blob/main/packages/core/src/middleware-http-signing/httpSigningMiddleware.ts#L13
---
=> fix(core): Strict dependency for @smithy/core

.changeset/big-kings-shop.md, packages/core/src/index.ts, packages/core/src/pagination/createPaginator.ts
Creates a paginator template function to reduce generated code of paginators.
The `type` returned by the paginator factory is identical to the pre-existing pagination functions. ✅ 
sample diff: https://github.com/aws/aws-sdk-js-v3/pull/5590
before
```js
import { ListFunctionsCommand, } from "../commands/ListFunctionsCommand";
import { LambdaClient } from "../LambdaClient";
const makePagedClientRequest = async (client, input, ...args) => {
return await client.send(new ListFunctionsCommand(input), ...args);
};
export async function* paginateListFunctions(config, input, ...additionalArguments) {
let token = config.startingToken || undefined;
let hasNext = true;
let page;
while (hasNext) {
input.Marker = token;
input["MaxItems"] = config.pageSize;
if (config.client instanceof LambdaClient) { …
```
=> feat: paginator factory

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PaginationGenerator.java
this PR requires that https://github.com/smithy-lang/smithy-typescript/pull/1115 be merged and published
=> feat: paginator factory applied to codegen

.changeset/forty-stingrays-lay.md, packages/util-config-provider/src/booleanSelector.spec.ts, packages/util-config-provider/src/booleanSelector.ts, packages/util-config-provider/src/index.ts, packages/util-config-provider/src/numberSelector.spec.ts, packages/util-config-provider/src/numberSelector.ts, packages/util-config-provider/src/types.ts
* Currently used in NODE_MAX_ATTEMPT_CONFIG_OPTIONS https://github.com/smithy-lang/smithy-typescript/blob/2df620b6882388ce4773eb4ea5a012eb44b001f8/packages/middleware-retry/src/configurations.ts#L15-L35
* Required in https://github.com/aws/aws-sdk-js-v3/pull/5618
Add numberSelector utility in util-config-selector
---
=> Add numberSelector utility

.changeset/happy-adults-complain.md, packages/middleware-endpoint/src/adaptors/createConfigValueProvider.spec.ts, packages/middleware-endpoint/src/adaptors/createConfigValueProvider.ts, packages/types/src/identity/awsCredentialIdentity.ts
- Adds the `credentialScope` field to AWS credentials type
- Modifies the endpoints ruleset resolver to pull credentialScope from config.credentials if requested
=> feat: add credential scope field

.changeset/bright-elephants-walk.md, packages/middleware-compression/package.json, packages/middleware-compression/src/compressionMiddleware.spec.ts, packages/middleware-compression/src/compressionMiddleware.ts, packages/middleware-compression/src/configurations.ts, packages/middleware-compression/src/getCompressionPlugin.spec.ts, packages/middleware-compression/src/getCompressionPlugin.ts, packages/middleware-compression/src/resolveCompressionConfig.spec.ts, packages/middleware-compression/src/resolveCompressionConfig.ts, yarn.lock
Noticed while doing E2E testing in https://github.com/aws/aws-sdk-js-v3/pull/5625
Accept Provider in CompressionInputConfig
---
=> Accept Provider in CompressionInputConfig

.changeset/nice-pumas-collect.md, packages/middleware-compression/src/configurations.ts, packages/middleware-compression/src/resolveCompressionConfig.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/5643#issuecomment-1877397637
Make CompressionInputConfig properties optional
* The properties need to be optional, as they don't need to be passed during client creation.
* The properties need to be required during resolution, since they're resolved by runtimeConfig.
---
=> Make CompressionInputConfig properties optional

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java
*Issue:*
Similar to [this issue](https://github.com/smithy-lang/smithy-typescript/pull/714), when a resource shape is the only model assigned to the last bucket, an export statement for the file is included in index.ts, yet the file is never created, as there is no codgen for resources.
```typescript
// smithy-typescript generated code
export * from "./models_0";
export * from "./models_1"; // file doesn't exist
```
- Update SymbolVisitor to always place resource shapes in initial bucket
- Add unit test
=> fix: model bucketing edge case with resource shape

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java
N/A.
Move private methods to `ClientBodyExtra`.
---
=> chore(experimentalIdentityAndAuth): move private methods to `ClientBodyExtra`

.changeset/four-steaks-sip.md, packages/core/src/pagination/createPaginator.spec.ts, packages/core/src/pagination/createPaginator.ts
fixes https://github.com/aws/aws-sdk-js-v3/issues/5766
In the conversion to the `createPaginator` function, the handling of deep paths was lost. This bug affects 9 paginator functions in CloudFront, Elasticache, Neptune, RDS, and Redshift, out of a total of 2776.
=> fix: handle multi-part token paths in paginator

.changeset/lazy-elephants-hope.md, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/types/src/http/httpHandlerInitialization.ts
Addresses https://github.com/aws/aws-sdk-js-v3/issues/3560
This PR adds a warning:
```
@smithy/node-http-handler:WARN socket usage at capacity=<X> and <Y> additional 
requests are enqueued. 
See https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-maxsockets.html
```
Where `X` is the configured maxSockets for the Node http(s) agent, and `Y` is the number of open requests. 
This warning is emitted in the following situation:
- a request is taking more than `socketAcquisitionWarningTimeout ?? connectTimeout + requestTimeout` to complete.
- indicates delay in acquiring a socket
- no similar warning has been emitted in the last 15 seconds.
- prevent log spam
- the number of active sockets is equal to `maxSockets`
- indicates socket saturation
- the number of …
=> feat: add checked socket exhaustion warning when throughput is slow

.changeset/fifty-ghosts-live.md, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/types/src/http/httpHandlerInitialization.ts
Simplify usage by allowing `http(s).Agent` constructor argument instead of an instance of such.
Before:
```ts
import https from "node:https";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
const client = new DynamoDBClient({
requestHandler: new NodeHttpHandler({
requestTimeout: 3_000,
httpsAgent: new https.Agent({
maxSockets: 25
}),
}),
});
```
After:
```ts
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
const client = new DynamoDBClient({
requestHandler: new NodeHttpHandler({
requestTimeout: 3_000,
httpsAgent: { maxSockets: 25 },
}),
});
```
End goal:
```ts
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
const client = new …
```
=> feat: allow http(s).Agent ctor arg in lieu of instance

.changeset/three-paws-add.md, packages/protocol-http/src/httpHandler.ts, packages/smithy-client/src/client.ts
This implements step 3 of the following progression mentioned earlier in https://github.com/smithy-lang/smithy-typescript/pull/1165.
Previously:
```ts
import https from "node:https";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
const client = new DynamoDBClient({
requestHandler: new NodeHttpHandler({
requestTimeout: 3_000,
httpsAgent: new https.Agent({
maxSockets: 25
}),
}),
});
```
Step 2 (implemented):
```ts
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { NodeHttpHandler } from "@smithy/node-http-handler";
const client = new DynamoDBClient({
requestHandler: new NodeHttpHandler({
requestTimeout: 3_000,
httpsAgent: { maxSockets: 25 },
}),
});
```
Step 3 (this PR):
```ts
import { DynamoDBClient } …
```
=> feat: enable ctor arg passthrough for requestHandler

.changeset/swift-cups-count.md, packages/shared-ini-file-loader/src/getSsoSessionData.spec.ts, packages/shared-ini-file-loader/src/getSsoSessionData.ts
Fixes: https://github.com/smithy-lang/smithy-typescript/issues/1163
Process sso-session names with config prefix separator
*Testing:*
```console
$ cat test.mjs
import { loadSsoSessionData } from "../smithy-typescript/packages/shared-ini-file-loader/dist-cjs/index.js";
console.log(await loadSsoSessionData());
$ cat ~/.aws/config
[profile my.big.profile]
region = us-east-1
sso_session = my.sso
sso_account_id = 123456789
sso_role_name = BigRole
[sso-session my.sso]
sso_region = us-east-1
sso_start_url = https://magic-app.awsapps.com/start
sso_registration_scopes = sso:account:access
$ node test.mjs 
{
'my.sso': {
sso_region: 'us-east-1',
sso_start_url: 'https://magic-app.awsapps.com/start',
sso_registration_scopes: 'sso:account:access'
}
} …
```
=> Process sso-session names with config prefix separator

.changeset/tough-bikes-sit.md, packages/credential-provider-imds/src/utils/getExtendedInstanceMetadataCredentials.ts
The log message is currently:
> Attempting credential expiration extension due to a credential service availability issue. A refresh of these credentials will be attempted after ${new Date(newExpiration)}.
This PR switches to using \`backticks\` so the code date is interpolated as expected.
---
=> fix: credential expiration extension log message

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
AWS SDK is already using `^9.0.1` for uuid.
=> fix: use 9.0.1 for uuid

.changeset/tough-tools-fix.md, packages/credential-provider-imds/src/index.ts
*Issue #, if available:* https://github.com/aws/aws-sdk-js-v3/issues/4004
Exporting Endpoint from `credential-provider-imds` to use in `ec2-metadata-service` in JSv3.
Related PR:
https://github.com/aws/aws-sdk-js-v3/pull/5796 
---
=> chore(credential-provider-imds): export IMDS endpoint for v3 utils #5796

.changeset/lazy-olives-film.md, packages/middleware-serde/src/deserializerMiddleware.spec.ts, packages/middleware-serde/src/deserializerMiddleware.ts
Currently, deserializer collectors read response body streams prior to attempting to deserialize them. 
If there is a parsing error, such as when a JSON service front end layer (load balancer, CDN, etc) has an error and returns non-JSON, the raw text of this error is lost since the stream collector has read the stream.
For this PR, addressing such cases, if the error contains a field called `$responseBodyText`, it will be written over the response body's (consumed and therefore empty) stream, so the user can read the body text instead of only having an empty stream.
It is up to the deserializer implementation to write the body text to this field. 
Example:
```ts
export const parseJsonBody = (streamBody: any, context: SerdeContext): any =>
collectBodyString(streamBody, …
```
=> fix: allow error deserializers to populate error response body

.changeset/fluffy-deers-doubt.md, packages/middleware-serde/src/deserializerMiddleware.spec.ts, packages/middleware-serde/src/deserializerMiddleware.ts, packages/middleware-serde/src/serdePlugin.ts, packages/middleware-serde/src/serializerMiddleware.spec.ts, packages/middleware-serde/src/serializerMiddleware.ts, packages/types/src/serde.ts, packages/types/src/util.ts, packages/util-base64/package.json, packages/util-base64/src/toBase64.browser.spec.ts, packages/util-base64/src/toBase64.browser.ts, packages/util-base64/src/toBase64.spec.ts, packages/util-base64/src/toBase64.ts, packages/util-utf8/src/toUtf8.browser.spec.ts, packages/util-utf8/src/toUtf8.browser.ts, packages/util-utf8/src/toUtf8.spec.ts, packages/util-utf8/src/toUtf8.ts, yarn.lock
Clients currently have two internal fields of type `Encoder`, currently `Uint8Array => string`.
These have been updated to be `Uint8Array | string => string`, to allow direct conversion of utf8 strings to base64, rather than requiring a `Uint8Array` input.
The `Encoder` type has been loosened, since it is public.
related issues:
https://github.com/aws/aws-sdk-js-v3/issues/5745
https://github.com/aws/aws-sdk-js-v3/issues/5240
=> feat: encoders accept strings

.changeset/many-stingrays-bow.md, packages/middleware-serde/src/deserializerMiddleware.ts, packages/middleware-serde/src/serdePlugin.ts, packages/middleware-serde/src/serializerMiddleware.ts
This fixes type compatibility of the latest version of `serdePlugin` with older code generation that isn't on the `classBuilder` syntax.
=> fix(types): use SerdeFunctions type as serde plugin input, but call serde functions as type SerdeContext

.changeset/strange-cars-itch.md, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/server.mock.ts, packages/node-http-handler/src/write-request-body.ts, packages/util-body-length-node/src/calculateBodyLength.ts
supercedes external contrib https://github.com/aws/aws-sdk-js-v3/pull/2612
=> reduce buffer copies

.changeset/old-kangaroos-rhyme.md, packages/util-base64/src/toBase64.browser.spec.ts, packages/util-base64/src/toBase64.browser.ts
There was some application code using arrays `[]` instead of `Uint8Array`, ignoring types. 
https://github.com/aws-amplify/amplify-ui/blob/bd05991f9bf0f666694c90d6445b63dcc8c795f3/packages/react-liveness/src/components/FaceLivenessDetector/service/utils/streamProvider.ts#L174-L198
We requested the client code to patch the behavior, but we can modify this to be consistent with prior runtime behavior as well.
ArrayLike values are acceptable but not preferred (for compactness) in lieu of Uint8Array because in the browser implementation, data is read from index entries of the input object.
=> fix(util-base64): allow arrays to stand in for Uint8Array (runtime only)

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/documentation/StructureExampleGeneratorTest.java
https://github.com/aws/aws-sdk-js-v3/issues/5240
The PR improves the inline documentation generated for structural hints for operation inputs and outputs.
It differentiates between input and output of the same Smithy type (BLOB). For TypeScript, the inputs are wider than a single type for convenience, and the output has mixin methods attached, again for user convenience. 
For a sample diff, see first commit in https://github.com/aws/aws-sdk-js-v3/pull/5864
STREAMING_BLOB_VALUE
```ts
* // { // GetObjectOutput
* //   Body: "STREAMING_BLOB_VALUE",
* //   DeleteMarker: true || false,
```
becomes
```ts
* // { // GetObjectOutput
* //   Body: "<SdkStream>", // see @smithy/types -> StreamingBlobPayloadOutputTypes
* //   DeleteMarker: true || false,
```
BLOB_VALUE
```ts
* //   Payload: { // …
```
=> docs: add more information about BLOB values in structures

build.gradle.kts, config/checkstyle/checkstyle.xml, gradle/wrapper/gradle-wrapper.properties, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
Upgrades the gradle version of the project to 8.2.1. This will allow us to use the new smithy gradle plugins with this project.
*Note* No changes to `packages/` 
---
=> chore: update gradle version to 8.2.1

.github/dependabot.yml
Updates the dependabot configuration to run on a specific day (wednesday) and to group updates to Gradle or github actions. Updates to NPM dependencies are not grouped.
---
=> chore: update dependabot configuration to group updates

smithy-typescript-codegen-test/model/weather/main.smithy
Applies `smithy format` to the weather service Smithy model. 
The new Smithy gradle plugins will apply formatting by default so after this PR no additional formatting-specific changes will be required.
---
=> chore: apply smithy formatter to test model

README.md, gradle.properties, settings.gradle.kts, smithy-typescript-codegen-test/build.gradle.kts, smithy-typescript-codegen-test/example-weather-customizations/build.gradle.kts, smithy-typescript-codegen-test/released-version-test/build.gradle.kts, smithy-typescript-codegen/build.gradle.kts, smithy-typescript-ssdk-codegen-test-utils/build.gradle.kts
Updates to use the newer split smithy gradle plugins. (see: https://smithy.io/2.0/guides/gradle-plugin/gradle-migration-guide.html)
*test*
Checked with js v3 by published `smithy-typescript` to maven localexecuted `./gradlew clean build` from the `codegen` dir of jsv3
---
=> chore: update to use new smithy gradle plugins

build.gradle.kts
The primary smithy package and the gradle plugins both use [jreleaser](https://jreleaser.org/) to simplify the release process for releasing a maven artifact. This PR updates the gradle build script for the project to include a jreleaser configuration.
*links* 
- Smithy gradle: https://github.com/smithy-lang/smithy-gradle-plugin/blob/main/build.gradle.kts#L33
- Main smithy package: https://github.com/smithy-lang/smithy/blob/main/build.gradle#L293
---
=> chore: update gradle build script to use jreleaser for release

.changeset/six-doors-speak.md, packages/smithy-client/src/command.spec.ts, packages/smithy-client/src/command.ts, packages/types/src/client.ts, packages/types/src/util.spec.ts, packages/types/src/util.ts, smithy-typescript-codegen-test/model/weather/main.smithy, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceAggregatedClientGenerator.java
currently:
```ts
new GetCallerIdentity({}); // empty argument required
sts.getCallerIdentity({}); // empty argument required
new PutObjectCommand({ Key: "", Bucket: "" }); // non-empty argument required
s3.putObject({ Key: "", Bucket: "" }); // non-empty argument required
```
in this PR, feature:
```ts
new GetCallerIdentity(); // argument may be omitted
sts.getCallerIdentity(); // argument may be omitted (codegen TODO)
new PutObjectCommand({ Key: "", Bucket: "" }); // non-empty argument still required
s3.putObject({ Key: "", Bucket: "" }); // non-empty argument still required
```
=> feat: allow commands to be constructed without arg if all arg fields optional

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
Missed in https://github.com/smithy-lang/smithy-typescript/pull/1209#discussion_r1526448065
Use map instead of isEmpty when writing shape docs
---
=> Use map instead of isEmpty when writing shape docs

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
Internal JS-5074
Currently the documentation is read as part of deprecation
Example: https://github.com/aws/aws-sdk-js-v3/blob/a967bfc08aac5714420bef63c55832da49492d4a/clients/client-qconnect/src/commands/QueryAssistantCommand.ts#L34-L40
This will move the documentation before release tag, so that it's read separately and not as deprecation.
TSDoc references:
* https://tsdoc.org/pages/tags/public/
* https://tsdoc.org/pages/tags/deprecated/
Move documentation before release tag and deprecation.
---
=> Move documentation before release tag and deprecation

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
Internal discussion as a follow-up to https://github.com/smithy-lang/smithy-typescript/pull/1211
Neither the jsdoc or tsdoc provide any explicit recommendation on the order of tags. However, when an interface is deprecated, it should appear at the top if developers are reading from top to down.
---
=> Move deprecation after description in docs

smithy-typescript-codegen/build.gradle.kts
I found that my dependencyVersions.properties and sdkVersions.properties files had thousands of lines in them, which is redundant.
The build process creates these files by reading the package json versions of AWS code and of Smithy packages.
These file numbers are used in our dependency enums when initializing an enum value with no particular version number:
```java
public enum TypeScriptDependency implements Dependency {
SMITHY_CORE("dependencies", "@smithy/core", false),
```
During releases to maven, the then-current versions within the workspace are stamped into the maven artifact. Since the action appends the version to the end of the file, presumably the latest versions will be written in the HashMap, regardless of what may exist already in the file. 
There was a report that 0.19.0 …
=> fix: empty the contents of the dependencyVersions.properties file when creating it

.changeset/fair-spiders-jump.md, packages/middleware-retry/package.json, yarn.lock
UUID 9 is already in use in the AWS SDK and the code generator.
=> chore: make consistent uuid version

CHANGELOG.md, README.md, build.gradle.kts, smithy-typescript-codegen-test/released-version-test/build.gradle.kts
Also had to change the codegen libraries' dependency versions in released-version-test to not use the version specified by the project.
---
=> Bump codegen version to 0.20.0

.changeset/cuddly-ties-cover.md, packages/signature-v4/package.json, packages/signature-v4/src/HeaderFormatter.spec.ts, packages/signature-v4/src/HeaderFormatter.ts, packages/signature-v4/src/SignatureV4.ts, yarn.lock
fixes https://github.com/smithy-lang/smithy-typescript/issues/1159
temporarily duplicates the header formatting functionality from evenstream-codec to signature-v4 so that sigv4 does not have to import the entire eventstream-codec package and transitively the large-ish aws-crypto packages.
when Node.js 14 support is dropped, our typescript config will support submodules (package.json:exports) and then the headerMarshaller functionality can be reunified as a single submodule of e.g. `@smithy/core`.
=> feat: give SigV4 its own header formatter to avoid import of entire eventstream-codec package

.changeset/khaki-moose-punch.md, packages/middleware-endpoint/src/service-customizations/s3.spec.ts, packages/middleware-endpoint/src/service-customizations/s3.ts
As stated in this issue https://github.com/smithy-lang/smithy-typescript/issues/1121 arn check should not check s3 arns contain nor account nor region since they are not part of s3 arns
#1121
Check S3 arn is valid by not expecting account nor region to be in the arn (fail if any of those two are present)
---
=> fix(middleware-endpoint): check for s3 arn parts

.changeset/little-otters-complain.md, packages/signature-v4/src/SignatureV4.spec.ts, packages/signature-v4/src/SignatureV4.ts
Issue #1224 
URI escape non-standard characters in the URI path according to RFC 3986. 
See #1224 for more information.
---
=> fix(signature-v4): uri escape path (#1224)

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/validation/ImportFrom.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptWriterTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/validation/ImportFromTest.java
when calling `addImport`, the TSWriter will either add the import or throw an error if it determines the import is a non-native package and has not been added via addDependency.
this is to prevent calls to `addImport` that forget to also call `addDependency`.
=> fix: check dependencies when adding imports

README.md, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/base-package.json
This changes generated artifacts (client / server) to support Node.js 16.x as the minimum Node.js version.
We announced [the end of support for Node.js 14.x in the AWS SDK for JavaScript (v3)](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-14-x-in-the-aws-sdk-for-javascript-v3/) starting May 1, 2024 back in October, 2023.
Bump engines to node >= 16.0.0
---
=> chore(package.json): bump engines to node >= 16.0.0

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/PackageJsonGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptDependencyTest.java
Noticed while working on https://github.com/smithy-lang/smithy-typescript/pull/1249
Add service client doc generator only when typedoc is selected
---
=> Add service client doc generator only when typedoc is selected

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json
The codegen part of https://github.com/aws/aws-sdk-js-v3/pull/6037
Extend tsconfig from @tsconfig/node16
This won't impact aws-sdk-js-v3 05/01 release as no new services are being released, but it requires fix.
---
=> Extend tsconfig from @tsconfig/node16

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
The codegen now supports Node.js 16.x as of https://github.com/smithy-lang/smithy-typescript/pull/1249
Bump @types/node to 16.x
---
=> Bump @types/node to 16.x

.changeset/happy-monkeys-tap.md, packages/fetch-http-handler/README.md, packages/node-http-handler/README.md, packages/node-http-handler/src/stream-collector/index.spec.ts, packages/node-http-handler/src/stream-collector/index.ts, packages/util-stream/src/sdk-stream-mixin.browser.spec.ts, packages/util-stream/src/sdk-stream-mixin.spec.ts, packages/util-stream/src/sdk-stream-mixin.ts
https://github.com/aws/aws-sdk-js-v3/issues/4619
- `streamCollector` and `sdkStreamMixin` components that are part of the client config, specifically the SerdeContext subset, have been modified to allow web streams
=> feat: improve support for fetch and web-streams in Node.js

.changeset/cold-ligers-punch.md, packages/types/src/client.ts, packages/types/src/transform/no-undefined.spec.ts, packages/types/src/transform/no-undefined.ts
https://github.com/aws/aws-sdk-js-v3/issues/6065
fix type transforms for Clients to handle the case where a method has an additional no-args signature. 
- no-args signature was a feature added after the addition of the AssertiveClient/UncheckedClient type transforms.
=> fix: type transforms account for no-args operation methods

.github/workflows/ci.yml
N/A.
Update CI to be more resilient.
For TypeScript Test, don't allow it to fail fast to prevent having to rerun failed jobs all the time, costing more billing.
This will allow contributors to rerun singular Node versions to test on.
Also, don't run any TypeScript Test until the CI for linting, formatting, and changesets have succeeded.
---
=> Update CI to be more resilient

.changeset/fluffy-crabs-watch.md, packages/fetch-http-handler/src/stream-collector.ts, packages/node-http-handler/src/stream-collector/index.ts
I noticed stream collectors were doing iffy copy operations during the stream -> Uint8Array process.
=> feat(node-http-handler): improve stream collection performance

.changeset/tiny-eyes-argue.md, packages/fetch-http-handler/src/fetch-http-handler.ts
Followup to https://github.com/aws/aws-sdk-js-v3/issues/4619 as part of `fetch` in Node.js compatibility.
- Set `duplex: "half"` on `Request` init when body is present. This is required in Node.js and ignored in the browser.
=> fix(fetch-http-handler): set duplex on request when body present

.changeset/sweet-years-compete.md, packages/smithy-client/src/ser-utils.spec.ts, packages/smithy-client/src/ser-utils.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtilsTest.java
fixes https://github.com/smithy-lang/smithy-typescript/issues/1278
=> fix: serialize milliseconds for DateTime and EpochSeconds timestamp formats

.changeset/late-glasses-jam.md, .changeset/two-weeks-provide.md, packages/credential-provider-imds/src/fromContainerMetadata.ts, packages/credential-provider-imds/src/fromInstanceMetadata.ts, packages/node-config-provider/src/fromEnv.spec.ts, packages/node-config-provider/src/fromEnv.ts, packages/node-config-provider/src/fromSharedConfigFiles.spec.ts, packages/node-config-provider/src/fromSharedConfigFiles.ts, packages/node-config-provider/src/getSelectorName.ts, packages/property-provider/src/CredentialsProviderError.spec.ts, packages/property-provider/src/CredentialsProviderError.ts, packages/property-provider/src/ProviderError.ts, packages/property-provider/src/TokenProviderError.ts, packages/shared-ini-file-loader/src/loadSharedConfigFiles.ts
Enable access to the log of instantiated `CredentialsProviderError`s.
In the AWS SDK with its many credential sources (default chain), the sequence through which you may end up with a certain provider in the chain is unclear, and seeing the history of thrown `CredentialProviderError`s helps with both maintainer and user debugging.
Example log:
```
2024-05-23T20:17:57.283Z -> Not found in ENV: UA_APP_ID_ENV_NAME
2024-05-23T20:17:57.283Z -> Not found in ENV: AWS_DEFAULTS_MODE_ENV
2024-05-23T20:17:57.289Z -> Unable to find environment variable credentials.
2024-05-23T20:17:57.289Z -> Skipping SSO provider in default chain (inputs do not include SSO fields).
2024-05-23T20:17:57.296Z -> Not found in config files w/ profile [default]: UA_APP_ID_INI_NAME
2024-05-23T20:17:57.296Z -> Not found in …
```
=> chore: add logging for CredentialsProviderError

.changeset/lucky-hats-doubt.md, packages/smithy-client/src/ser-utils.spec.ts, packages/smithy-client/src/ser-utils.ts
I thought the test cases had more control over what was asserted downstream in the test generator (aws-sdk-js-v3), but the literal test case body strings are upstream (Smithy), so to pass the tests _and_ remain compliant with the spec I'd like to truncate the timestamps when millis are `000`.
=> fix(smithy-client): truncate timestamp at 000 millis

.changeset/rare-bulldogs-battle.md, packages/core/package.json, packages/core/scripts/lint.js
Partner PR with https://github.com/aws/aws-sdk-js-v3/pull/6149
adds a module field to (conditional) exports in core. 
no other entry points in submodules in `/core` yet
---
=> fix(core): set module export fields

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java
Fixes: https://github.com/smithy-lang/smithy-typescript/issues/1298
Validates resolvedHost from httpRequestTests
Tested with MachineLearning in commit [aws/aws-sdk-js-v3@`1d6f814` (#6161)](https://github.com/aws/aws-sdk-js-v3/pull/6161/commits/1d6f814504c8540bd9a71915439b8da31010e757)
---
=> Validate resolvedHost from httpRequestTests

.changeset/strong-timers-join.md, packages/types/src/identity/awsCredentialIdentity.ts
Internal JS-4633
Adds `accountId` as optional to the `AwsCredentialIdentity` interface. This `accountId` may be used for endpoint routing. 
---
=> feat(types): add accountId to the credential identity interface

.changeset/afraid-cooks-grin.md, packages/eventstream-codec/package.json, packages/hash-blob-browser/package.json, packages/hash-blob-browser/src/index.spec.ts, packages/hash-stream-node/package.json, packages/signature-v4/package.json, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, yarn.lock
addresses https://github.com/aws/aws-sdk-js-v3/issues/5305
addresses https://github.com/aws/aws-sdk-js-v3/issues/6162
updates `@aws-crypto` package versions to 5.2.0. This was previously blocked by support for Node.js 14.
=> chore: update @aws-crypto/* to 5.2.0 series

.changeset/purple-frogs-guess.md, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/types/src/http/httpHandlerInitialization.ts
https://github.com/smithy-lang/smithy-typescript/issues/1305
- add logger option to node-http-handler
- clear socket usage check timeout on error
=> fix(node-http-handler): add logger option and clear timeout on errors

.changeset/spotty-cars-do.md, packages/abort-controller/src/AbortController.ts, packages/abort-controller/src/AbortSignal.ts, packages/fetch-http-handler/src/fetch-http-handler.ts, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.ts, packages/types/src/abort-handler.ts, packages/types/src/abort.ts, packages/types/src/http.ts, packages/types/src/waiter.ts, packages/util-waiter/src/createWaiter.ts
fixes https://github.com/aws/aws-sdk-js-v3/issues/4872
fixes https://github.com/smithy-lang/smithy-typescript/issues/974
this deprecates our own Abort types and implementation and switches to the platform types where available.
AbortController / AbortSignal are available in Node.js 16+.
=> chore: switch to platform AbortController & Signal implementations after dropping Node.js 14

.changeset/giant-swans-trade.md, packages/util-waiter/src/waiter.spec.ts, packages/util-waiter/src/waiter.ts
Internal JS-5250
Returns stringified result object in case of failure
---
=> fix(util-waiter): return stringified result object in case of failure

.changeset/polite-fans-fly.md, packages/fetch-http-handler/src/fetch-http-handler.spec.ts, packages/fetch-http-handler/src/fetch-http-handler.ts, packages/types/src/http/httpHandlerInitialization.ts
*Issue #, if available:* [1296](https://github.com/smithy-lang/smithy-typescript/issues/1296)
*Description of changes:* Adds support to set credentials in the fetch API to `include`, `same-origin`, or `omit`.
---
=> Adding support for setting the fetch API credentials mode

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
https://smithy.io/2.0/spec/behavior-traits.html#idempotencytoken-trait
> Client implementations MAY automatically provide a value for a request token member if and only if the member is not explicitly provided.
This adds the automatic default token for headers. Previously added for query params in https://github.com/aws/aws-sdk-js-v3/pull/4272.
```ts
const headers: any = map({}, isSerializableHeaderValue, {
"content-type": "application/json",
[_xact]: input[_CT]!,
});
```
```ts
import { v4 as generateIdempotencyToken } from "uuid";
const headers: any = map({}, isSerializableHeaderValue, {
"content-type": "application/json",
[_xact]: input[_CT] ?? generateIdempotencyToken(),
});
```
=> feat: automatic idempotency tokens for header values

.changeset/four-carrots-tap.md, packages/fetch-http-handler/src/fetch-http-handler.ts, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/node-http2-handler.ts
*Issue #1318, if available:*
Currently if an `AbortSignal` is re-used across multiple requests, more and more listeners will accumulate, leading to memory leaks. In order to mitigate this, we should remove any event listeners we add to the `AbortSignal` when the request completes.
- Should we be more defensive and check that `removeEventListener` is a function before using it?
- I don't really like the code changes in the `fetch-http-handler` so if anyone has any suggestions, please do chime in. It's somewhat tricky because `fetch` doesn't provide an event-driven API (that I know of).
---
=> Remove AbortSignal event listeners when requests complete

.changeset/eight-beans-visit.md, packages/shared-ini-file-loader/src/loadSharedConfigFiles.spec.ts, packages/shared-ini-file-loader/src/loadSharedConfigFiles.ts
https://github.com/aws/aws-sdk-js-v3/issues/5876
If a config path relative to *homedir* is provided, `shared-ini-file-loader` now expands `~` to its absolute path and reads the config file successfully.
---
=> fix(shared-ini-file-loader): read config files from paths relative to homedir

.changeset/khaki-seahorses-cough.md, packages/protocol-http/src/httpRequest.spec.ts, packages/protocol-http/src/httpRequest.ts
This moves `HttpRequest#clone()` (instance method) to `HttpRequest.clone(IHttpRequest)` (static method) and deprecates the original instance method.
`HttpRequest#clone()` cannot safely be called, because the type-guard `HttpRequest.isInstance(unknown)` is not correctly implemented, but cannot safely be changed since it is widely used as-is. 
`HttpRequest.isInstance(unknown) -> boolean is HttpRequest` is actually 
`HttpRequest.isInstance(unknown) -> boolean is IHttpRequest`. 
It returns true when the input satisfies the data/structural interface, but the structural interface does not necessarily include the `.clone()` method.
=> chore(protocol-http): guidance for HttpRequest cloning

.changeset/real-teachers-sort.md, packages/signature-v4/src/SignatureV4.ts
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/3590
The SignatureV4 implementation was originally added in https://github.com/aws/aws-sdk-js-v3/pull/36 seven years ago, where `sha256` was not optional. It was incorrectly made optional in https://github.com/aws/aws-sdk-js-v3/pull/58.
This issue was not noticed during development of AWS SDK for JavaScript packages, since we always passed `sha256` as linked in https://github.com/aws/aws-sdk-js-v3/issues/3590#issuecomment-2223511779. However, it was an issue for some customers who called it directly. As described in the issue, those customers provided `sha256` implementation as a workaround.
This PR makes `sha256` a required parameter, as required by the implementation.
---
By submitting …
=> Make sha256 required parameter for SigV4 constructor

.changeset/metal-snakes-remember.md, packages/util-stream/package.json, packages/util-stream/src/headStream.browser.ts, packages/util-stream/src/headStream.spec.ts, packages/util-stream/src/headStream.ts, packages/util-stream/src/index.ts, packages/util-stream/src/isReadableStream.ts, packages/util-stream/src/sdk-stream-mixin.browser.ts, packages/util-stream/src/splitStream.browser.ts, packages/util-stream/src/splitStream.spec.ts, packages/util-stream/src/splitStream.ts, packages/util-stream/src/stream-type-check.ts
- `splitStream` splits a stream into two streams using `pipe(PassThrough)` or `tee()` depending on Stream type.
- `headStream` collects the first N bytes of a stream.
Use case: peek the head of a stream's copy while leaving the 2nd copy of that original stream intact
Use case: obtain a parallel stream for checksumming
=> feat(util-stream): splitStream and headStream utilities

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/AddBuiltinPlugins.java
followup fix for https://github.com/smithy-lang/smithy-typescript/pull/1321.
The `CustomEndpoints` plugin is only needed for non-endpoints-ruleset services.
=> fix: exclude CustomEndpoints plugin from Endpoints 2.0 services

smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/protocol-test-stub.ts
Due to creating a set of default plugins in https://github.com/smithy-lang/smithy-typescript/pull/1321, an endpoint must be provided for non-Endpoints-RuleSet service models' clients. 
Providing a default endpoint in protocol tests is required for the non-Endpoints-RuleSet case, and also non-breaking otherwise.
=> add default endpoint to protocol test stub

.changeset/forty-candles-taste.md, packages/eventstream-serde-browser/src/EventStreamMarshaller.ts, packages/util-stream/src/stream-type-check.ts
https://github.com/smithy-lang/smithy-typescript/issues/1341
If we export an interface involving a reference to the global `ReadableStream`, when compiled with the DOM lib present this becomes `ReadableStream<any>`. 
This is not compatible with `@types/node`, which declares a generic ReadableStream only in the stream/web module, and for some reason a different one globally.
=> fix(util-stream): avoid compilation of type parameter in global ReadableStream

.changeset/stale-ladybugs-reflect.md, packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.spec.ts, packages/credential-provider-imds/src/remoteProvider/ImdsCredentials.ts
Internal JS-4633
Part 1
Sources accountId from IMDS credential provider.
PR to update `AwsCredentialIdentity` interface: #1240 
*Testing*
Verify unit tests pass after above PR to update `AwsCredentialIdentity` interface is merged:
Done in https://github.com/aws/aws-sdk-js-v3/pull/6019
---
=> feat(credential-provider-imds): source accountId from IMDS

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/OmitEndpointParams.java
Internal JS-4633 
Part 2
Omits (a collection of) Endpoint params from being generated into the `ClientInputEndpointParameters` interface. This collection can be used for omission from other interfaces as well accordingly. 
Partner PR in JSv3:  https://github.com/aws/aws-sdk-js-v3/pull/6035
---
=> feat: omit endpoint params from generation in the client interface

.changeset/brown-bags-leave.md, packages/middleware-endpoint/src/adaptors/createConfigValueProvider.spec.ts, packages/middleware-endpoint/src/adaptors/createConfigValueProvider.ts
Internal JS-4633
Part 3
adds support for accountId in `configValueProvider` (sourced from credentials)
*Testing*
```console
PASS  src/adaptors/createConfigValueProvider.spec.ts (14.921 s)
createConfigValueProvider
✓ should create a normalized provider for any config value (10 ms)
✓ should look up both the canonical Endpoint ruleset param name and any localized override (1 ms)
✓ uses a special lookup for CredentialScope (1 ms)
✓ uses a special lookup for accountId (1 ms)
✓ should normalize endpoint objects into URLs (1 ms)
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        15.411 s
```
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> feat: add support for accountId in configValueProvider

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java
When serializing the headers for an event stream event, the `:event-type` should take on the member name and not the member target id.
```ts
const headers: __MessageHeaders = {
":event-type": { type: "string", value: "textEvent" }, // <-- here, for example
":message-type": { type: "string", value: "event" },
":content-type": { type: "string", value: "application/json" },
};
```
This had not manifested until a recent AWS service in which the two values were not identical for apparently the first time.
=> fix(event-streams): use member name as :event-type header value

.changeset/unlucky-glasses-nail.md, packages/fetch-http-handler/src/fetch-http-handler.ts
* Fixes: https://github.com/aws/aws-sdk-js-v3/issues/6269
* A cleaner alternative to https://github.com/smithy-lang/smithy-typescript/pull/1350
Initialize removeSignalEventListener as an empty function
Testing done in https://github.com/aws/aws-sdk-js-v3/issues/6269#issuecomment-2253018138
---
=> Initialize removeSignalEventListener as an empty function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java
switches back to using string join because templating escapes the string which may include smithy syntax
=> fix: use string join instead of templates

.changeset/hip-cycles-buy.md, packages/smithy-client/src/command.ts
related to `experimentalIdentityAndAuth` (no longer experimental), 
this PR adds a reference to the calling command within the smithy-context, a data object that exists for the lifecycle of a request and is naturally subordinated to the command. 
having this reference will allow the middleware using the smithy-context object to fetch the command's static contextual endpoint parameters.
=> chore(id-auth-sra): set command instance ref on smithy context

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java
Noticed while working on JS-5234
Removes redundant `getStaticContextParams` function from RuleSetParameterFinder
It was originally added to get static context params, but later was replaced by fetching the values directly in `getStaticContextParamValues`
---
=> Remove redundant getStaticContextParams function

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java
Fixes failing endpoint tests in https://github.com/aws/aws-sdk-js-v3/pull/6373#issuecomment-2278753422
Populates memberName as contextParams value, so that it can be consumed correctly when populating endpoints.
---
=> Populate memberName as contextParams value

.changeset/good-cheetahs-press.md, packages/util-endpoints/src/__mocks__/test-cases/parse-url.json, packages/util-endpoints/src/resolveEndpoint.ts
Refs: https://github.com/aws/aws-sdk-js-v3/pull/6410#issuecomment-2311320293
Skips taking protocol and port from custom Endpoint.
The old tests added in https://github.com/aws/aws-sdk-js-v3/pull/4031 were likely incorrect.
Noticed while incorporating the endpoint tests at top-level in https://github.com/aws/aws-sdk-js-v3/pull/6410#issuecomment-2311320293
---
=> Do not take protocol and port from custom Endpoint

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/ParameterGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java
Internal JS-5234
Process String Array parameters in Endpoints
---
=> Process String Array parameters in Endpoints

smithy-typescript-ssdk-libs/server-apigateway/package.json, smithy-typescript-ssdk-libs/server-common/package.json, smithy-typescript-ssdk-libs/server-node/package.json
N/a
The ssdk packages have `"module": "./dist/es/index.js",` in package.json, but did not include `./dist/es` in their published files to npm. I noticed this when using vite's bundler, which was looking for the ESM entrypoint via the `module` field, but it was unable to find the file because it was not included in the files published to npm. This PR addes the files inside of `./dist/es` to the list of files published to npm to fix this issue.
---
=> Include ./dist/es in published ssdk package files to fix ESM entrypoint

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/endpointsV2/endpoints-operation-context-params.smithy
Internal JS-5234
Processes Operation Context Params in Endpoints
---
=> Process Operation Context Params in Endpoints

.changeset/hot-items-sing.md, packages/middleware-endpoint/src/adaptors/getEndpointFromConfig.ts, packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts, packages/middleware-endpoint/src/resolveEndpointConfig.ts
https://github.com/aws/aws-sdk-js-v3/issues/6423
- resolve service specific endpoint once per config (client instance)
- this avoids the ENV and file system read from `loadConfig`
=> fix(endpoints): resolve service-specific endpoint once per client

smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPluginTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2GeneratorTest.java
The deprecation messages were noticed when writing tests in https://github.com/smithy-lang/smithy-typescript/pull/1379
Uses TypeScriptClientCodegenPlugin in tests, as per changes done in https://github.com/smithy-lang/smithy-typescript/pull/1057
---
=> Use TypeScriptClientCodegenPlugin in tests

.changeset/wise-fans-fold.md, packages/types/README.md, packages/types/src/command.ts, packages/types/src/transform/client-method-transforms.ts, packages/types/src/transform/client-payload-blob-type-narrow.spec.ts, packages/types/src/transform/client-payload-blob-type-narrow.ts, packages/types/src/transform/no-undefined.spec.ts, packages/types/src/transform/no-undefined.ts, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPluginTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2GeneratorTest.java
https://github.com/aws/aws-sdk-js-v3/issues/4720
This PR fixes typechecking for aggregated client usage in the optional type transforms from changes to the Command shapes using Command.classBuilder. 
preview of the integration test I'll add to AWS SDK:
```ts
import { GetObjectCommand, S3, S3Client } from "@aws-sdk/client-s3";
import type { AssertiveClient, BrowserClient, NodeJsClient, UncheckedClient } from "@smithy/types";
{
// default, no validation for undefined values
const s3 = new S3({});
await s3.listBuckets();
await s3.listBuckets({});
// @ts-expect-error (missing Bucket)
s3.getObject({
Key: undefined,
});
s3.getObject({
// @ts-expect-error (unrecognized field)
UnknownProperty: undefined,
});
const get = await s3.getObject({
Bucket: undefined,
Key: undefined,
});
// …
```
=> fix(types): fix client type transforms

.changeset/empty-feet-shop.md, packages/node-http-handler/src/node-http-handler.ts, packages/node-http-handler/src/set-connection-timeout.ts, packages/node-http-handler/src/set-socket-keep-alive.spec.ts, packages/node-http-handler/src/set-socket-keep-alive.ts, packages/node-http-handler/src/set-socket-timeout.spec.ts, packages/node-http-handler/src/set-socket-timeout.ts
https://github.com/aws/aws-sdk-js-v3/issues/6423
This PR defers the registration of `socket` event listeners on individual requests outgoing from `node:http(s)` requests.
Attaching events creates a small performance overhead (0-2ms) and I believe they are unnecessary for requests that resolve in under 3 seconds for timeouts of greater than 6 seconds.
Here is a comparison of the use-case of a request before and after this PR:
- request is created
- socket event listeners are attached
- request is submitted
- socket event triggers event listeners 
- some don't do anything because the timeouts involved are far higher than the request duration
- sending a keepalive probe is useless if the request completes in e.g. under a second
- request completes, event listeners are cleaned up
- request is …
=> feat(node-http-handler): defer socket event listener attachment

.changeset/moody-fishes-buy.md, packages/util-endpoints/src/cache/EndpointCache.spec.ts, packages/util-endpoints/src/cache/EndpointCache.ts, packages/util-endpoints/src/index.ts, scripts/build-generated-test-packages.js, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinderTest.java
https://github.com/aws/aws-sdk-js-v3/issues/6423
This PR creates a cache for endpoint ruleset resolution.
As one would expect, the input and cache key are the endpoint params and the output and cache value is the endpoint.
Some services declare endpoint parameters in excess of what is actually evaluated in the ruleset, so codegen provides the explicit pared param list to the cache instance.
=> feat(util-endpoint): add endpoint ruleset cache

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptCodegenPlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSSDKCodegenPlugin.java
The deprecation messages were noticed in https://github.com/smithy-lang/smithy-typescript/pull/1387, but I'd to dig into the history/parent class to find out which class to use.
Add docs to use updated TypeScript Codegen Plugins
---
=> Add docs to use updated TypeScript Codegen Plugins

.changeset/fresh-hairs-work.md, packages/node-http-handler/src/set-connection-timeout.spec.ts, packages/node-http-handler/src/set-connection-timeout.ts, packages/node-http-handler/src/set-socket-keep-alive.spec.ts, packages/node-http-handler/src/set-socket-keep-alive.ts
followup to https://github.com/smithy-lang/smithy-typescript/pull/1384
if socket event listeners are deferred past the socket event (i.e. socket exists), call the socket methods directly.
=> fix(node-http-handler): call socket methods if socket is defined

.changeset/tall-cameras-reply.md, packages/middleware-stack/src/MiddlewareStack.ts, packages/smithy-client/src/client.spec.ts, packages/smithy-client/src/client.ts
https://github.com/aws/aws-sdk-js-v3/issues/6423
This adds a cache for the handler functions resolved from calls to 
```ts
command.resolveMiddleware(client.middlewareStack, client.config, (request) options)
```
when options is undefined. This occurs in the request path and can take 1-2ms, but is redundant for any client/command pair in most cases. 
Despite being cached, the handler functions has a reference to the client config, so any changes there will still be visible to the middleware within the resolved handler. ~Modifying a client's middlewareStack invalidates the cache.~
The cache is opt-in and also unique per client, so users retain control that way.
=> feat(smithy-client): add handler cache

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java
closes https://github.com/smithy-lang/smithy-typescript/issues/1366
This PR creates `declare protected static` fields on classes pointing to commonly sought after associated type declarations.
This is needed because the type declaration position of commands can be distant from the type declaration of the operation's input and output.
In the future, the list of modeled Exception classes could also be listed here. 
- `declare` this allows the field to have a type annotation without assigning any runtime value. In the runtime JavaScript code, these types do not appear at all. This avoids wasting runtime artifact size on what is essentially documentation.
- `static` avoids autocomplete proposing this field on instances of the Command class.
- `protected` avoids autocomplete proposing this …
=> feat: IDE type navigation assistance for command classes

.changeset/forty-cooks-deny.md, packages/types/src/http/httpHandlerInitialization.ts
- adds interface stub for `RequestInit` global
`RequestInit` was already used in the fetch-http-handler, but that is only conditionally compiled if the user imports it or bundles web-based code that imports the browser runtimeConfig files. 
The usage of `RequestInit` in the types package, which is not conditionally loaded, must be accompanied by the interface merging stub.
=> fix(types): add interface stub for RequestInit

.changeset/gold-bugs-sneeze.md, packages/node-http-handler/src/node-http-handler.spec.ts, packages/node-http-handler/src/node-http-handler.ts
*[issue](https://github.com/aws/aws-sdk-js-v3/issues/6495)*
Nodejs `URL` is not fully compatible with `http.RequestOptions` see https://github.com/nodejs/node/issues/39738
---
=> fix(node-http-handler): fix invalid usage of parsed url

.changeset/good-cheetahs-wait.md, packages/fetch-http-handler/src/fetch-http-handler.ts
Fixes #1407 
Omit setting cache setting on request init when using default value
=> fix(node-http-handler): omit setting cache setting on request init when using default value

private/smithy-rpcv2-cbor/src/commands/EmptyInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/Float16Command.ts, private/smithy-rpcv2-cbor/src/commands/FractionalSecondsCommand.ts, private/smithy-rpcv2-cbor/src/commands/GreetingWithErrorsCommand.ts, private/smithy-rpcv2-cbor/src/commands/NoInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/OperationWithDefaultsCommand.ts, private/smithy-rpcv2-cbor/src/commands/OptionalInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/RecursiveShapesCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborDenseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborListsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborSparseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/SimpleScalarPropertiesCommand.ts, private/smithy-rpcv2-cbor/src/commands/SparseNullsOperationCommand.ts
updates the codegen output of the protocol tests
=> chore: update protocol test codegen output

.changeset/ninety-hairs-obey.md, packages/signature-v4/src/getCanonicalQuery.spec.ts, packages/signature-v4/src/getCanonicalQuery.ts
When signing an HTTP request with SigV4, an incorrect signature will be generated if the query parameter key contains characters that need to be encoded.
The following query parameter reproduces it: `?params[page]=1&params[pageSize]=20`
According to the [AWS documentation][canonical-query-params], it seems that query parameters need to be sorted after encoding.
> `CanonicalQueryString` – The URI-encoded query string parameters. You URI-encode each name and value individually. You must also sort the parameters in the canonical query string alphabetically by key name. The sorting occurs after encoding.
[canonical-query-params]: https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html#create-canonical-request
* Sort query parameter keys after URI …
=> fix(signature-v4): sort query parameter keys after encoding

.changeset/modern-pumpkins-yell.md, packages/core/.gitignore, packages/core/cbor.d.ts, packages/core/package.json, packages/core/scripts/lint.js
https://github.com/aws/aws-sdk-js-v3/issues/6502
Adds a `.d.ts` file in the core root so that an import like `@smithy/core/submodule` not only maps via package.json exports, but also via traditional package relative pathing when contexts do not understand the exports metadata.
created new linting rules for core submodules
=> fix(core): add compatibility redirect for submodule types

.changeset/eighty-queens-yawn.md, packages/middleware-compression/src/compressionMiddleware.spec.ts, packages/middleware-compression/src/compressionMiddleware.ts
headers are case insensitive, but this matches the protocol tests better
=> chore: use lowercase headers in middleware-compression

.changeset/happy-emus-crash.md, packages/signature-v4/src/SignatureV4.ts, packages/signature-v4/src/moveHeadersToQuery.spec.ts, packages/signature-v4/src/moveHeadersToQuery.ts, packages/types/src/signature.ts
allows additive configuration over header hoisting with `hoistableHeaders`, where previously users could only configure the `unhoistableHeaders`.
For example, with S3, it was either incorrectly deduced or limited by S3 feature availability at the time that SSE headers were considered unhoistable. For backwards compatibility we will still default them to unhoisted, but as of today my testing shows this not to be true.
This change enables the following use case:
```ts
const params = {
Key: "...",
Bucket: "...",
ServerSideEncryption: "aws:kms",
SSEKMSKeyId: "arn:aws:kms:us-west-2:0000:key/abcd-1234-abcd",
};
const s3Client = new S3Client();
const command = new PutObjectCommand(params);
const preSignedUrl =
(await getSignedUrl(s3Client, command, {
hoistableHeaders: new …
```
=> fix(signature-v4): add hoistable headers config

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
fix conditional branching for union readPayload codegen
=> fix: skip streaming data for union check in readPayload

.changeset/sharp-horses-fry.md, packages/core/src/setFeature.spec.ts, packages/core/src/setFeature.ts, packages/types/src/feature-ids.ts, packages/types/src/index.ts, packages/types/src/middleware.ts
Adds a typed `features` map as a subsection of the Smithy Context, which is an object that has a lifecycle corresponding to an SDK request. 
This map is not written to or read from in this PR, but integrations will be added to identify certain features being used. It will be read downstream in the SDK user agent middleware.
This functionality is not strictly relevant to the standalone Smithy runtime, but I am suggesting this is the least obtrusive way to implement it.
downstream: https://github.com/aws/aws-sdk-js-v3/pull/6536
=> feat: allow feature identification on the smithy context

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/protocols/cbor/CborShapeSerVisitor.java
uuid doesn't import its own types package and is under an older system of having types in the `@types/` organization. 
This imports those types when importing `uuid`.
=> fix: add uuid types when adding uuid

gradle.properties, smithy-typescript-codegen-test/model/weather/main.smithy
=> chore: upgrade smithyVersion=1.51.0

private/smithy-rpcv2-cbor/src/protocols/Rpcv2cbor.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/protocols/cbor/SmithyRpcV2Cbor.java
adds a default `accept: application/cbor` request header for the rpcv2cbor protocol.
=> chore: add default accepts header for rpcv2Cbor

.changeset/red-cameras-repair.md, packages/util-stream/karma.conf.js, packages/util-stream/package.json, packages/util-stream/src/checksum/ChecksumStream.browser.ts, packages/util-stream/src/checksum/ChecksumStream.ts, packages/util-stream/src/checksum/createChecksumStream.browser.spec.ts, packages/util-stream/src/checksum/createChecksumStream.browser.ts, packages/util-stream/src/checksum/createChecksumStream.spec.ts, packages/util-stream/src/checksum/createChecksumStream.ts, packages/util-stream/src/index.ts
creates the `createChecksumStream` function to wrap streams with a checksum verification that throws when the stream is read to completion if the checksum verification fails.
Related to flexible checksums in AWS SDKs, but implementation is generic here. 
API reference:
- https://developer.mozilla.org/en-US/docs/Web/API/TransformStream
- https://nodejs.org/api/stream.html#duplex-and-transform-streams
=> feat(util-stream): create checksum stream adapters

.changeset/breezy-cobras-repair.md, .changeset/fluffy-planes-grow.md, packages/chunked-blob-reader-native/src/index.ts, packages/chunked-blob-reader/src/index.spec.ts, packages/chunked-blob-reader/src/index.ts, packages/fetch-http-handler/src/stream-collector.spec.ts, packages/fetch-http-handler/src/stream-collector.ts
Improve performance of collecting blob body by using` arrayBuffer() `method.
---
=> feat(fetch-http-handler): improve performance, replace FileReader with Blob.arrayBuffer()

.changeset/rotten-fans-rest.md, packages/util-stream/src/splitStream.spec.ts, packages/util-stream/src/splitStream.ts, packages/util-stream/src/stream-type-check.ts
Allow blobs through the splitStream function in Node.js. 
This is not for a reported issue but I encountered this in testing.
=> fix: allow blobs in Node.js splitStream fn

.github/CODEOWNERS
see also: https://github.com/aws/aws-sdk-js-v3/pull/6616
The AWS SDK for JavaScript team will take over codeowner responsibilities with the Smithy team participating ad hoc.
=> removes smithy-team from codeowners

private/smithy-rpcv2-cbor/src/models/models_0.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructuredMemberWriter.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptSettings.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/StructureGeneratorTest.java
If a member is `optional?:`, it should allow `undefined`. The generated clients do not consider absence vs value-undefined to have a meaningful distinction.
sample diff: https://github.com/aws/aws-sdk-js-v3/pull/6653
completes https://github.com/aws/aws-sdk-js-v3/issues/4017
=> feat: allow undefined when property optional for exactOptionalPropertyTypes

.changeset/sweet-horses-impress.md, packages/core/scripts/lint.js, packages/core/src/submodules/protocols/requestBuilder.ts
In one of the submodules there is a fully qualified import pointed to itself. 
This works in Node.js, but I believe some build transforms may have trouble with it as reported in https://github.com/aws/aws-sdk-js-v3/issues/6626.
This PR moves the import and adds a custom linter to prevent this pattern.
=> fix: avoid self referencing import for external build transforms

.changeset/three-trainers-know.md, packages/types/src/transform/no-undefined.spec.ts, packages/types/src/transform/no-undefined.ts
When trying to use `AssertiveClient` or `UncheckedClient` for a request that contains a field of type `DocumentType` results in the following TypeScript error:
```
error TS2589: Type instantiation is excessively deep and possibly infinite.
```
Inside the `AssertiveClient` type definition, the `NoUndefined` type:
```
export type NoUndefined<T> = T extends Function ? T : [T] extends [object] ? {
[key in keyof T]: NoUndefined<T[key]>;
} : Exclude<T, undefined>;
```
recursively iterates excluding `undefined`. The issue stems from the type `DocumentType` since it is self-referential which results in an infinite loop.
```
export type DocumentType = null | boolean | number | string | DocumentType[] | {
[prop: string]: DocumentType;
};
```
Update …
=> fix: prevent infinite recursion with NoUndefined and RecursiveRequired re: DocumentType

.changeset/sweet-planets-give.md, packages/core/src/submodules/cbor/cbor-decode.ts, packages/core/src/submodules/cbor/cbor-encode.ts, packages/core/src/submodules/cbor/cbor-types.ts, packages/core/src/submodules/cbor/cbor.spec.ts, packages/core/src/submodules/cbor/cbor.ts, packages/core/src/submodules/cbor/index.ts, packages/core/src/submodules/cbor/parseCborBody.ts
This PR fixes tag serialization for CBOR. 
There was no previous way to distinguish an actual tag as opposed to a map that structurally resembled a tag like
`{ tag: 1, value: 100 }`.
=> fix(core): use unique symbol to indicate tags for cbor serialization

.changeset/hungry-eels-accept.md, packages/node-http-handler/src/write-request-body.spec.ts, packages/node-http-handler/src/write-request-body.ts
Currently, S3 in AWS-SDK uses "expect: 100-continue" header.
In case of errors, for example "403 Forbidden", the request fails only on timeout. This happens because while sendRequestBody is waiting for "continue" event, a "response" event is fired and "continue" is not fired at all.
---
=> fix(node-http-handler): skip sending body without waiting for a timeout on response, if "expect" request header with "100-continue" is provided

.changeset/large-squids-rush.md, packages/node-http-handler/src/timing.ts
Fixes #1465 
Added context binding
---
=> fix: binding the methods to the context

.changeset/plenty-parents-accept.md, packages/util-waiter/src/createWaiter.spec.ts, packages/util-waiter/src/poller.spec.ts, packages/util-waiter/src/poller.ts, packages/util-waiter/src/waiter.ts
Addresses: https://github.com/aws/aws-sdk-js-v3/issues/6699
Collects a count of observed responses during the polling of a waiter.
code:
```js
import { IAM, waitUntilUserExists } from "@aws-sdk/client-iam";
const iam = new IAM({ region: "us-west-2" });
await waitUntilUserExists(
{
client: iam,
maxWaitTime: 15.001,
},
{
UserName: "echo2",
}
);
```
old:
```
Error [TimeoutError]: {"state":"TIMEOUT","reason":"Waiter has timed out"}
```
new (when failed):
```
Error [TimeoutError]: {
"state":"TIMEOUT",
"observedResponses":{"404: The user with name echo2 cannot be found.":5},
"reason":"Waiter has timed out"
}
```
new (when unauthorized):
```
Error [TimeoutError]: {
"state":"TIMEOUT",
"observedResponses":
{"403: User: arn:aws:sts::... is not authorized to perform: iam:GetUser on resource: user …
```
=> feat(util-waiter): aggregate observed responses in waiter response

.changeset/warm-dragons-wash.md, packages/smithy-client/src/lazy-json.spec.ts, packages/smithy-client/src/lazy-json.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/SymbolVisitor.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpProtocolGeneratorUtils.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/SymbolProviderTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberDeserVisitorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/DocumentMemberSerVisitorTest.java
https://github.com/aws/aws-sdk-js-v3/issues/6182
removes String extension, which causes global string de-optimization. Refactors LazyJsonString to use a boxed String with mixins rather than extending String.
=> remove String extension in LazyJsonString

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptJmesPathVisitor.java
Internal JS-5495
completing a TODO: resolves JMESPath object and array types as JS literals
---
=> chore(codegen): resolve obj and array JS literals from JMESPath types for waiters

.changeset/thick-socks-cross.md, build.gradle.kts, packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts, packages/middleware-endpoint/src/types.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java
Internal JS-5629
This PR fixes codegen for operationContextParam by changing the path expression result into a mapping function based on the command's input. The getter functions are made non-throwing so as not to perform unintentional client side validation.
=> fix for operationContextParam codegen

.changeset/khaki-clouds-tease.md, packages/smithy-client/src/lazy-json.ts
enable the `new` operator call type for LazyJsonString
=> type-fix for LazyJsonString call interface

.changeset/warm-pans-cross.md, packages/smithy-client/src/exceptions.spec.ts, packages/smithy-client/src/exceptions.ts
Internal JS-5478
Adds an `isInstance` type check helper method for generic `ServiceException` class in `smithy-client`.
`ServiceException.isInstance(e)`/ `e instanceof ServiceException` should now tell if something is an instance of the generic `ServiceException` class
---
=> feat(smithy-client): add isInstance method for ServiceException class

.changeset/metal-emus-chew.md, packages/fetch-http-handler/src/stream-collector.ts
* https://github.com/aws-samples/aws-sdk-js-tests/issues/223
* https://github.com/aws/aws-sdk-js-v3/issues/6733
* https://github.com/aws/aws-sdk-js-v3/issues/6636
* https://github.com/aws/aws-sdk-js-v3/issues/6626#issuecomment-2506443781
Adds polyfill to collect Blob in react-native environment where arrayBuffer API is not available.
This re-introduces the code removed in https://github.com/smithy-lang/smithy-typescript/pull/1179, but only when `Blob.prototype.arrayBuffer` implementation is not available.
Tested by copying fetch-http-handler artifacts to https://github.com/aws-samples/aws-sdk-js-tests/issues/223, and verifying that API call is successful.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> fix(fetch-http-handler): add polyfill to collect Blob in react-native

.changeset/curvy-cups-fly.md, packages/smithy-client/src/exceptions.spec.ts, packages/smithy-client/src/exceptions.ts
Internal JS-5642
remove support for `instanceof` operator (at least temporarily) owing to https://github.com/aws/aws-sdk-js-v3/issues/6771 
---
=> fix(smithy-client): remove support for instanceof operator in ServiceException

.changeset/eleven-poems-bake.md, packages/util-waiter/src/utils/validate.spec.ts, packages/util-waiter/src/utils/validate.ts
https://github.com/aws/aws-sdk-js-v3/issues/6767
The waitUntilObjectExists function was incorrectly throwing an error:
Error: WaiterConfiguration.minDelay must be greater than 0
When minDelay was set to 0.5.
Changes Made:
Updated validateWaiterOptions to only throw an error if minDelay, maxDelay, or maxWaitTime are less than or equal to 0 instead of < 1.
Added a test case to verify that small values like 0.01 do not throw an error.
This ensures that fractional values (e.g., 0.5, 0.01) work correctly while keeping 0 invalid. 
*Testing*
for util-waiter:
✓ src/waiter.spec.ts (5)
✓ src/utils/validate.spec.ts (7)
✓ src/poller.spec.ts (5)
✓ src/index.spec.ts (1)
✓ src/createWaiter.spec.ts (3)
Test Files  5 passed (5)
Tests  21 passed (21)
Start …
=> fix(util-waiter): fix waiter validation

.changeset/olive-lies-bake.md, .github/workflows/release-npm-packages.yml
switches the data source for NPM publishing token
=> chore: switch NPM publishing token source

.changeset/yellow-hats-live.md, packages/smithy-client/src/exceptions.spec.ts, packages/smithy-client/src/exceptions.ts
Internal JS-5478, Internal JS-5642
adds proper support for the `instanceof` operator to ServiceException while ensuring subclasses maintain strict prototype checking.
1. adds `[Symbol.hasInstance]` to ServiceException that supports `instanceof` checks according to the assertion table noted below (in the comments).
2. fixes prototype chain setup in ServiceException constructor to properly support inheritance.
```typescript
Object.setPrototypeOf(this, Object.getPrototypeOf(this).constructor.prototype);
```
this resolves an issue where duck-typed objects were incorrectly matching subclass `instanceof` checks (e.g. `dummyServiceException instanceof NoSuchKey` would return true even when it wasn't actually a NoSuchKey instance). 
*Testing*
for …
=> fix(smithy-client): instanceof support for ServiceException class

.changeset/rich-emus-cry.md, packages/smithy-client/src/exceptions.spec.ts, packages/smithy-client/src/exceptions.ts
adds prototype chain check for the `isInstance` method for `ServiceException`
*Testing*
```console
✓ src/client.spec.ts (7)
✓ src/command.spec.ts (2)
✓ src/create-aggregated-client.spec.ts (4)
✓ src/date-utils.spec.ts (155)
↓ src/emitWarningIfUnsupportedVersion.spec.ts (7) [skipped]
✓ src/exceptions.spec.ts (16)
✓ src/get-value-from-text-node.spec.ts (3)
✓ src/is-serializable-header-value.spec.ts (4)
✓ src/lazy-json.spec.ts (7)
✓ src/object-mapping.spec.ts (8)
✓ src/parse-utils.spec.ts (430)
✓ src/quote-header.spec.ts (4)
✓ src/ser-utils.spec.ts (4)
✓ src/serde-json.spec.ts (3)
✓ src/split-every.spec.ts (5)
✓ src/split-header.spec.ts (2)
Test Files  15 passed | 1 skipped (16)
Tests  654 passed | 7 skipped (661)
Start at  18:40:22
Duration  1.39s (transform 836ms, …
```
=> fix(smithy-client): add prototype chain fallback for service exception

.changeset/good-buttons-relax.md, packages/node-http-handler/src/write-request-body.spec.ts, packages/node-http-handler/src/write-request-body.ts
Fixes the issue reported here: https://github.com/aws/aws-sdk-js-v3/issues/6805
When the client makes a request with the `Expect: 100-continue` header, it will wait for 1000ms to get either a `100 Continue` response or an error. If it does not receive any response within the 1000ms, the intention seems to be that the client should write the body anyway. This behavior broke in #1459 because in the timeout case `resolve` is called with no arguments, which means that `sendBody` becomes undefined and the body is never sent. Even if the server returns a 100 Continue after 1001ms, the client is no longer waiting for that response and instead just idles until eventually the server returns an error.
This change restores the previous behavior, where the client will send …
=> fix(node-http-handler): Write request body if 100 Continue response takes more than 1 second

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-5673
Bump codegen version to 0.26.0
---
=> Bump codegen version to 0.26.0

.changeset/brave-trees-fry.md, packages/middleware-serde/src/deserializerMiddleware.spec.ts, packages/middleware-serde/src/deserializerMiddleware.ts
https://github.com/aws/aws-sdk-js-v3/issues/6783
handle unwritable error.message field
=> fix(middleware-serde): handle unwritable error message

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
- https://github.com/aws/aws-sdk-js-v3/issues/6672
- P187212400
- Currently the description for parameter is missing when param has deprecated tag. By moving deprecated tag after block, description should render correctly.
Resource: https://tsdoc.org/pages/tags/deprecated/
---
=> chore(docs): move description block before deprecated tag

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/util/StringStore.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/util/StringStoreTest.java
fixes allocation of strings starting with underscore and other cases
=> fix(codegen): variable allocation in StringStore

.changeset/popular-dolls-allow.md, packages/node-http-handler/src/node-http-handler.ts
*Issue:* https://github.com/smithy-lang/smithy-typescript/issues/1528
[NodeHttpHandler](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-node-http-handler/Interface/NodeHttpHandlerOptions/) “socketAcquisitionWarningTimeout” option does not work correctly.
Fix it
=> fix(node-http-handler): fix constructor socketAcquisitionWarningTimeout does not work

.changeset/twenty-peaches-notice.md, packages/node-http-handler/src/set-socket-timeout.spec.ts, packages/node-http-handler/src/set-socket-timeout.ts
*Issue #1530*
This PR adds cleaning the socket timeout listener from the underlying socket upon requests `close`, to avoid leaking the listeners throughout a keepAlive socket's lifetime.
---
=> fix(node-http-handler): clear obsolete socket timeout listeners

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/RuleSetParameterFinder.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/endpointsV2/endpoints-operation-context-params.smithy
* Internal JS-5749
* JMESPath docs: https://jmespath.org/specification.html#flatten-operator
* Array.prototype.flat() https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
Support JMESPath flatten in OperationContextParams
---
=> Support JMESPath flatten in OperationContextParams

gradle.properties, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/CommandGeneratorTest.java, smithy-typescript-codegen/src/test/resources/software/amazon/smithy/typescript/codegen/endpointsV2/endpoints-operation-context-params.smithy
Internal JS-5755
Updates smithy to 1.54.0
=> Upgrade smithy version to 1.54.0

.changeset/neat-queens-peel.md, packages/core/package.json, packages/core/serde.d.ts, packages/core/serde.js, packages/core/src/submodules/serde/index.ts, packages/core/src/submodules/serde/value/NumericValue.spec.ts, packages/core/src/submodules/serde/value/NumericValue.ts, packages/core/tsconfig.cjs.json, packages/core/tsconfig.es.json, packages/core/tsconfig.types.json
- creates the core/serde submodule, which will later be expanded when much of serde moves from codegen to JS runtime
- adds a NumericValue container (unused so far) for holding BigDecimal data without deciding on a numeric library on behalf of the user
This is not currently in use, but will facilitate future work on serde. It will also unify behavior related to too-large numerics. Currently there is inconsistent behavior among protocols when handling large numbers. Some make best-effort attempts to fit into Number and some throw errors disallowing large numbers. Both of those are not desirable for customers. 
We should aim to preserve numeric precision in all cases without coupling to any specific numeric library. A simple string container with a type differentiator field accomplishes …
=> feat(core/serde): add NumericValue container

private/smithy-rpcv2-cbor/src/RpcV2ProtocolClient.ts, private/smithy-rpcv2-cbor/src/auth/httpAuthSchemeProvider.ts, private/smithy-rpcv2-cbor/src/runtimeExtensions.ts, private/smithy-rpcv2-cbor/test/functional/rpcv2cbor.spec.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/RuntimeExtensionsGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/ServiceBareBonesClientGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2Generator.java, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/resolveRuntimeExtensions1.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/resolveRuntimeExtensions2.template, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/runtimeExtensions2.template, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/endpointsV2/EndpointsV2GeneratorTest.java
part 2 of https://github.com/smithy-lang/smithy-typescript/pull/1552
=> chore(codegen): generate client.initConfig reference for tracking config object custody

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/documentation/DocumentationExampleGenerator.java
in example generation, use backtick to wrap strings containing double quotes
diff can be seen in https://github.com/aws/aws-sdk-js-v3/pull/6981
=> fix: use backticks for example strings containing doublequotes

CHANGELOG.md, README.md, build.gradle.kts
JS-5804
Bumps the codegen version from 0.27 to 0.28
=> Bump codegen version to 0.28.0

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-5832
Bumps the codegen version from 0.28.0 to 0.29.0
---
=> Bump codegen version to 0.29.0

.changeset/tall-pens-yell.md, packages/experimental-identity-and-auth/CHANGELOG.md, packages/experimental-identity-and-auth/package.json, packages/signature-v4/CHANGELOG.md, packages/signature-v4/package.json, packages/signature-v4a/CHANGELOG.md, packages/signature-v4a/package.json
reverting [this commit by the action workflow](https://github.com/smithy-lang/smithy-typescript/commit/bec513c7beea38a3f5af4747b7056821fa077017) since it didn't finish releasing. will re-run this action
---
=> chore(packages): revert action version updates

.github/workflows/release-npm-packages.yml
updating token to use an org-level token since the `PUSH_TOKEN` seems to have expired, and the js automation token won't work
---
=> chore(workflow): update action token for npm release

README.md
N/A
Fix broken links for ts-ssdk related content due to previous content reorganization in smithy repo.
---
=> Fix broken links for ts-ssdk related content.

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-5859
Bumps the codegen version from 0.29.0 to 0.29.1
---
=> Bump codegen version to 0.29.1

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/auth/http/integration/AddHttpAuthSchemePlugin.java
Internal JS-5811
Adds `authSchemePreference` client config
---
=> Add authSchemePreference client config

gradle.properties, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpBindingProtocolGenerator.java
https://github.com/aws/aws-sdk-js-v3/pull/7045
Description
Upgrades the smithy cli to 1.56.0 and fix the order of precedence for the prefix headers
---
=> Update SmithyVersion to 1.56.0

.changeset/large-donkeys-notice.md, packages/service-error-classification/src/index.ts
Internal JS-5890
fetch API surfaces connectivity errors as TypeErrors, example: `TypeError: Failed to fetch` in Chrome. 
For browsers, we should retry for connectivity issues (offline), this is a fix to retry on TypeErrors then. Since we don't want to retry for `TypeErrors` that *aren't* network errors, I've paired this check with the actual error messages that different browsers surface (not an exhaustive list, but covers some major ones). 
Fetch has an open issue about this: https://github.com/whatwg/fetch/issues/526
additional resources
- https://stackoverflow.com/questions/61113344/fetch-api-how-to-determine-if-an-error-is-a-network-error
---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
=> fix(service-error-classification): add TypeError as transient error

private/smithy-rpcv2-cbor/src/auth/httpAuthSchemeProvider.ts, private/smithy-rpcv2-cbor/src/commands/EmptyInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/Float16Command.ts, private/smithy-rpcv2-cbor/src/commands/FractionalSecondsCommand.ts, private/smithy-rpcv2-cbor/src/commands/GreetingWithErrorsCommand.ts, private/smithy-rpcv2-cbor/src/commands/NoInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/OperationWithDefaultsCommand.ts, private/smithy-rpcv2-cbor/src/commands/OptionalInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/RecursiveShapesCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborDenseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborListsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborSparseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/SimpleScalarPropertiesCommand.ts, private/smithy-rpcv2-cbor/src/commands/SparseNullsOperationCommand.ts
`make generate-protocol-tests`
Updates codegen of protocol tests for feature from https://github.com/smithy-lang/smithy-typescript/pull/1571
=> chore: update codegen for protocol tests

.changeset/friendly-parents-compare.md, packages/core/src/submodules/cbor/parseCborBody.spec.ts, packages/core/src/submodules/cbor/parseCborBody.ts
Copy headers when building RPCv2 CBOR request. This is because some requests use the shared headers object and sigv4 signing mutates the request instead of returning a new one.
Rather than changing sigv4 behavior, which is more likely to have accidental reliance on the mutation, I am changing the request creation in the affected protocol.
=> fix(cbor): copy headers when building request

private/smithy-rpcv2-cbor/tsconfig.cjs.json, private/smithy-rpcv2-cbor/tsconfig.es.json, private/smithy-rpcv2-cbor/tsconfig.types.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.cjs.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.es.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.types.json, tsconfig.cjs.json, tsconfig.es.json
Type checking is not necessary for the CJS and ES build configurations.
This is because the dist-types build checks all types, including code inside functions that do not appear in the API type declarations. I have verified this.
Skipping type checks will improve build times and avoid redundant compilation errors printed to the console. Because all 3 dist builds run concurrently in the "build" scripts of packages, any existing type error is printed to the console 3 times in interleaved lines, resulting in a hard to read output.
savings in CI:
build packages step ~6m40s -> ~4m42s
=> chore(builds): skip typecheck for cjs/es artifacts

.changeset/rotten-chairs-float.md, packages/node-config-provider/src/configLoader.spec.ts, packages/node-config-provider/src/configLoader.ts, packages/node-config-provider/src/fromEnv.spec.ts, packages/node-config-provider/src/fromEnv.ts
Internal JS-5860
Gets configuration with optional signingName in loadConfig, and passes it to environment variable selector
---
=> chore(node-config-provider): pass options with signing name to environment variable selector

.changeset/calm-socks-end.md, packages/node-config-provider/src/configLoader.spec.ts, packages/node-config-provider/src/configLoader.ts, packages/node-config-provider/src/fromEnv.ts
https://github.com/smithy-lang/smithy-typescript/pull/1583/files#r2076091590
Passes logger to environment variable selector
---
=> fix(node-config-provider): pass logger to environment variable selector

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java
Allow the later addition of a protocol with the same ShapeId as an existing protocol to change its order in the priority list.
=> fix: allow overwriting a protocol's priority when selecting protocol

.changeset/tiny-otters-talk.md, packages/middleware-serde/package.json, packages/middleware-serde/src/deserializerMiddleware.spec.ts, packages/middleware-serde/src/deserializerMiddleware.ts, yarn.lock
This adds the `error.$metadata` field to deserialization errors, so that the (earlier in order) retry middleware can decide to retry the error if the response code is retryable, regardless of the format of the error.
This scenario can happen when a server origin response is supposed to be e.g. JSON but its load balancer is XML or does not reach the point of checking the correct response format. If the LB sheds a request with a retryable error code but unparsable body, the parsing error should be treated as non-terminal, retryable.
=> fix(middleware-serde): add response metadata to deserialization errors

.changeset/smooth-masks-think.md, packages/core/src/submodules/cbor/parseCborBody.spec.ts, packages/core/src/submodules/cbor/parseCborBody.ts
Changes `loadSmithyRpcV2CborErrorCode` to read any field matching `code` case-insensitively instead of just `code` (lowercase).
=> fix(core/cbor): read error code case-insensitively

.changeset/fair-news-beg.md, packages/types/src/command.ts
This loosens the typing of the schema object on Commands to be compatible with existing client type transformation adaptors. 
This also will publish a new version of `@smithy/types` which should address #1604
=> fix: type compatibility between command schema and type transforms

.changeset/big-hounds-jog.md, packages/core/src/submodules/protocols/HttpBindingProtocol.ts, packages/core/src/submodules/protocols/HttpProtocol.spec.ts, packages/core/src/submodules/protocols/HttpProtocol.ts
Previously, when deserializing http bindings, a prefix header and header could not be created from the same actual header. This fixes that to satisfy a specific protocol test.
=> fix(core/protocols): allow http prefix header and http header to read same value

.changeset/funny-pigs-kiss.md, packages/core/src/submodules/schema/TypeRegistry.spec.ts, packages/core/src/submodules/schema/TypeRegistry.ts
Followup to https://github.com/smithy-lang/smithy-typescript/pull/1611/, for the JS runtime code.
=> chore: use smithy synthetic namespace for service base exceptions

gradle.properties, private/smithy-rpcv2-cbor-schema/src/schemas/schemas.ts
smithy 1.58.0, regenerate protocol test clients
=> chore: upgrade to smithy 1.58.0

private/smithy-rpcv2-cbor-schema/src/schemas/schemas.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaReferenceIndex.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitFilterIndex.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/util/StringStore.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/schema/SchemaReferenceIndexTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitExtensionTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitFilterIndexTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitGeneratorTest.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitWriterTest.java
- augment the hard-coded list of included traits with meta-trait annotated authDefinition and protocolDefinition traits (aligns with spec but no change in codegen output)
- avoid allocation of unused strings in schema codegen
- adds unit tests for schema trait codegen
=> chore(schema): seed schema trait filter with auth and protocol definition traits

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGeneratorTest.java
https://github.com/smithy-lang/smithy-typescript/issues/1051
- adds validation defensive checking during the selection of the event stream member so the wrong member isn't selected
- tested codegen against sample given in https://github.com/smithy-lang/smithy-typescript/issues/1051
- tested codgen against multiple event stream AWS SDK clients
- added unit tests
=> fix: locate event stream member more carefully

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/test/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGeneratorTest.java
corrects the criteria from https://github.com/smithy-lang/smithy-typescript/pull/1623
http payload trait is not required and the member itself will not have the streaming trait.
=> fix: criteria for event stream member detection

.changeset/wicked-squids-pretend.md, packages/middleware-endpoint/src/index.ts, packages/middleware-endpoint/src/resolveEndpointRequiredConfig.spec.ts, packages/middleware-endpoint/src/resolveEndpointRequiredConfig.ts, private/smithy-rpcv2-cbor-schema/src/RpcV2ProtocolClient.ts, private/smithy-rpcv2-cbor/src/RpcV2ProtocolClient.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/endpointsV2/AddDefaultEndpointRuleSet.java
in https://github.com/smithy-lang/smithy-typescript/pull/1589, I added a "default endpoint ruleset" for all clients. This aligned all codegen for consistency and removed edge cases not covered by AWS SDK testing (AWS SDKs all have endpoint rulesets). 
In EP2.0, the endpoint input is not required. This makes client calls to `await client.config.endpoint()` fail a typecheck, because prior to #1589, a resolver layer called "CustomEndpoint" marked the endpoint input as required when not in the endpoints-ruleset code generation mode.
This PR adds backwards compatibility with the `CustomEndpoint` resolver layer without bringing it back. Here, I add a `EndpointRequired` config resolver layer when using the default endpoint ruleset.
=> fix: add EndpointRequired config resolver to replace CustomEndpoint

build.gradle.kts
Internal JS-5954
v3 codegen PR: https://github.com/aws/aws-sdk-js-v3/pull/7150
This change migrates from Nexus2 to Central Portal Deployer due to Nexus2 deprecation and upcoming sunset.
---
=> migrate from nexus2 to maven central

.changeset/famous-bulldogs-heal.md, packages/core/src/submodules/protocols/HttpBindingProtocol.ts, packages/core/src/submodules/schema/schemas/ErrorSchema.ts, packages/core/src/submodules/schema/schemas/ListSchema.ts, packages/core/src/submodules/schema/schemas/MapSchema.ts, packages/core/src/submodules/schema/schemas/NormalizedSchema.ts, packages/core/src/submodules/schema/schemas/SimpleSchema.ts, packages/core/src/submodules/schema/schemas/StructureSchema.ts, packages/core/src/submodules/schema/schemas/schemas.spec.ts
Adds class symbols and instanceof overrides for schema classes to avoid prototype mismatches.
=> chore: add instanceof overrides for schema classes

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptDependency.java
upgrades to fast-xml-parser 5.2.5 https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CHANGELOG.md
downstream: https://github.com/aws/aws-sdk-js-v3/pull/7176
=> chore: upgrade fast-xml-parser to 5.2.5

.changeset/sharp-ducks-happen.md, packages/middleware-endpoint/src/adaptors/createConfigValueProvider.ts, packages/middleware-endpoint/src/adaptors/getEndpointFromInstructions.ts, packages/middleware-endpoint/src/endpointMiddleware.ts, packages/middleware-endpoint/src/resolveEndpointConfig.ts
during endpoint resolution, client.config values are mapped into the endpoint resolver function.
In the case of `config.endpoint`, there will be a new case where this function is populated but is not considered a custom endpoint. This is for backwards compatibility with the pre-endpointRuleSet era AWS clients, where you could instantiate a client with no custom endpoint, and still retrieve `await client.config.endpoint()` without a null-check for `config.endpoint`. This was due to endpoints.json providing a sort of default regional endpoint for the given service.
=> fix(middleware-endpoint): return undefined for endpointParam=endpoint when isCustomEndpoint is false

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-6058
Bumps codegen version to 0.33.0
---
=> Bump codegen version to 0.33.0

.changeset/yellow-frogs-run.md, packages/core/package.json, packages/signature-v4a/package.json
set the bundler metadata flag `sideEffects` to false in core and true in signature-v4a.
- core is set to false to be explicit, since it has many submodules that should be tree-shaken as much as possible
- sigv4a is set to true because it has module level code that injects an implementation into a container checked by signature-v4-multi-region
=> fix(core): set sideEffects metadata

.changeset/lemon-wasps-itch.md, packages/smithy-client/src/command.ts, packages/smithy-client/src/schemaLogFilter.spec.ts, packages/smithy-client/src/schemaLogFilter.ts, private/smithy-rpcv2-cbor-schema/src/commands/EmptyInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/Float16Command.ts, private/smithy-rpcv2-cbor-schema/src/commands/FractionalSecondsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/GreetingWithErrorsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/NoInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/OperationWithDefaultsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/OptionalInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RecursiveShapesCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborDenseMapsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborListsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborSparseMapsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/SimpleScalarPropertiesCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/SparseNullsOperationCommand.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/DirectedTypeScriptCodegen.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/StructureGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/UnionGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaTraitFilterIndex.java
part of https://github.com/smithy-lang/smithy-typescript/issues/1600
- Use the operation schema to create the sensitive log i/o filter instead of generating functions for every sensitive shape, *WHEN* schema serde mode is on.
=> chore(core/schema): use schema log filter when available

private/my-local-model/tsconfig.json, private/my-local-model/tsconfig.types.json, private/smithy-rpcv2-cbor-schema/tsconfig.json, private/smithy-rpcv2-cbor-schema/tsconfig.types.json, private/smithy-rpcv2-cbor/tsconfig.json, private/smithy-rpcv2-cbor/tsconfig.types.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.json, smithy-typescript-codegen/src/main/resources/software/amazon/smithy/typescript/codegen/tsconfig.types.json
* Noticed while attempting to bump vitest in https://github.com/smithy-lang/smithy-typescript/pull/1663
* Alternative to https://github.com/smithy-lang/smithy-typescript/pull/1667
The exclude was historically added to ensure `build:types` is able to run again.
However, is any additional `*.ts` file is added outside of `src` folder (like `vitest.config.ts`), it needs to be excluded.
A better solution it to include `src` as it's done in this PR
---
=> chore: use 'include' in tsconfig.json

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/EventStreamGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/integration/HttpRpcProtocolGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/protocols/cbor/SmithyRpcV2Cbor.java
internal P291987404
Fixes event stream serialization when the `@eventStreamPayload` member is a string. 
This case is not present in current AWS models.
=> fix: event stream serialization

.changeset/swift-garlics-notice.md, packages/core/src/submodules/cbor/cbor-types.ts
Issue https://github.com/smithy-lang/smithy-typescript/issues/1675
Sets an explicit return type for the internal `alloc` cbor function so that the type compilation does not produce a generic parameter for `Uint8Array`. 
Though our target language level includes TypeScript built-in declarations of Uint8Array having a type parameter, for greater compatibility we should avoid using it.
=> fix(core/cbor): set explicit return type to de-genericize alloc fn

smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaGenerator.java
adds a context parameter to some private functions in schema generator class. 
this context allows the generator to know when to make a cross-file import of certain string variables.
=> fix: set context in schema codegen

.changeset/pink-items-shake.md, packages/core/src/submodules/cbor/SmithyRpcV2CborProtocol.spec.ts, packages/core/src/submodules/cbor/SmithyRpcV2CborProtocol.ts, packages/core/src/submodules/protocols/HttpBindingProtocol.spec.ts, packages/core/src/submodules/protocols/HttpBindingProtocol.ts, packages/core/src/submodules/protocols/serde/FromStringShapeDeserializer.ts, packages/core/src/submodules/protocols/serde/determineTimestampFormat.ts, packages/core/src/submodules/schema/schemas/ErrorSchema.ts, packages/core/src/submodules/schema/schemas/ListSchema.ts, packages/core/src/submodules/schema/schemas/MapSchema.ts, packages/core/src/submodules/schema/schemas/NormalizedSchema.spec.ts, packages/core/src/submodules/schema/schemas/NormalizedSchema.ts, packages/core/src/submodules/schema/schemas/OperationSchema.ts, packages/core/src/submodules/schema/schemas/Schema.ts, packages/core/src/submodules/schema/schemas/SimpleSchema.ts, packages/core/src/submodules/schema/schemas/StructureSchema.ts, packages/core/src/submodules/schema/schemas/schemas.spec.ts, packages/types/src/schema/schema.ts, testbed/bundlers/source.ts
- Reduce the bundled code size of the runtime for schema serde, from about 2k to 1k lines of code (non-minified)
=> chore: schema code size optimization

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-6204
Bump codegen version to 0.34.1
---
=> Bump codegen version to 0.34.1

.changeset/light-kiwis-teach.md, packages/shared-ini-file-loader/src/externalDataInterceptor.spec.ts, packages/shared-ini-file-loader/src/externalDataInterceptor.ts, packages/shared-ini-file-loader/src/getSSOTokenFromFile.ts, packages/shared-ini-file-loader/src/index.ts, packages/shared-ini-file-loader/src/slurpFile.ts
I tried vitest's mocking instructions, and the memfs & fs-mock NPM packages. Nothing works by default in combination with our file system reads to retrieve the AWS configuration. 
I concluded that the easiest solution would be to offer an internal API from our own package for ourselves.
=> test(shared-ini-file-loader): add external file cache mock controls

private/my-local-model/src/commands/GetNumbersCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/EmptyInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/Float16Command.ts, private/smithy-rpcv2-cbor-schema/src/commands/FractionalSecondsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/GreetingWithErrorsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/NoInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/OperationWithDefaultsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/OptionalInputOutputCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RecursiveShapesCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborDenseMapsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborListsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/RpcV2CborSparseMapsCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/SimpleScalarPropertiesCommand.ts, private/smithy-rpcv2-cbor-schema/src/commands/SparseNullsOperationCommand.ts, private/smithy-rpcv2-cbor/src/commands/EmptyInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/Float16Command.ts, private/smithy-rpcv2-cbor/src/commands/FractionalSecondsCommand.ts, private/smithy-rpcv2-cbor/src/commands/GreetingWithErrorsCommand.ts, private/smithy-rpcv2-cbor/src/commands/NoInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/OperationWithDefaultsCommand.ts, private/smithy-rpcv2-cbor/src/commands/OptionalInputOutputCommand.ts, private/smithy-rpcv2-cbor/src/commands/RecursiveShapesCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborDenseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborListsCommand.ts, private/smithy-rpcv2-cbor/src/commands/RpcV2CborSparseMapsCommand.ts, private/smithy-rpcv2-cbor/src/commands/SimpleScalarPropertiesCommand.ts, private/smithy-rpcv2-cbor/src/commands/SparseNullsOperationCommand.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/CommandGenerator.java, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/TypeScriptWriter.java
- https://github.com/aws/aws-sdk-js-v3/issues/6858
Previously asked by users:
- https://github.com/aws/aws-sdk-js-v3/issues/6083
- https://github.com/aws/aws-sdk-js-v3/issues/6097
- https://github.com/aws/aws-sdk-js-v3/issues/6624
- https://github.com/aws/aws-sdk-js-v3/issues/6854
- https://github.com/aws/aws-sdk-js-v3/issues/6070
- https://github.com/aws/aws-sdk-js-v3/issues/5944
- https://github.com/aws/aws-sdk-js-v3/issues/5603
- https://github.com/aws/aws-sdk-js-v3/issues/5417
- https://github.com/aws/aws-sdk-js-v3/issues/5326
- https://github.com/aws/aws-sdk-js-v3/issues/5260
- https://github.com/aws/aws-sdk-js-v3/issues/5019
- https://github.com/aws/aws-sdk-js-v3/issues/4452
Fixing it by adding explicit clientConfig import type and …
=> docs: add type information for client config to Command examples

.changeset/mean-paws-check.md, packages/middleware-apply-body-checksum/src/middleware-apply-body-checksum.integ.spec.ts, packages/middleware-content-length/src/middleware-content-length.integ.spec.ts, packages/middleware-retry/src/middleware-retry.integ.spec.ts, packages/middleware-serde/src/middleware-serde.integ.spec.ts, packages/service-error-classification/src/index.ts, packages/util-retry/package.json, packages/util-retry/src/retries.integ.spec.ts, packages/util-retry/vitest.config.integ.mts, packages/util-stream/src/util-stream.integ.spec.ts, private/my-local-model/src/commands/GetNumbersCommand.ts, private/my-local-model/src/models/models_0.ts, private/my-local-model/src/protocols/Rpcv2cbor.ts, private/util-test/src/test-http-handler.ts, smithy-typescript-protocol-test-codegen/model/my-local-model/main.smithy
https://github.com/aws/aws-sdk-js-v3/issues/7222
Error shapes can be modeled with the [`retryable`](https://smithy.io/2.0/spec/behavior-traits.html#retryable-trait) trait. Codegen turns this into a `$retryable` property on the Error class instances. 
This PR changes service error classification to consider such errors automatically retryable by making them transient. This is consistent with our internal specification, and more consistent with pre-SRA retries.
=> fix(service-error-classification): consider $retryable trait errors to be transient

scripts/compilation/Inliner.js
A re-export stub is a redirect of a deep `dist-cjs` path to the dist-cjs prebundled index.
Now that we have been officially discouraging deep imports for a while, and have provided no API guarantees or examples of importing deep paths in dist-cjs, we can stop shipping these stub files.
=> chore: stop generating re-export stubs for dist-cjs

.changeset/short-dodos-cover.md, packages/core/src/submodules/cbor/SmithyRpcV2CborProtocol.spec.ts, packages/core/src/submodules/cbor/SmithyRpcV2CborProtocol.ts, packages/core/src/submodules/schema/TypeRegistry.ts, packages/core/src/submodules/schema/schemas/ErrorSchema.ts, packages/core/src/submodules/schema/schemas/schemas.spec.ts, private/smithy-rpcv2-cbor-schema/src/schemas/schemas_0.ts, private/smithy-rpcv2-cbor-schema/src/schemas/schemas_1_Rpc.ts, smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/schema/SchemaGenerator.java
This is a minor update to adhere to the letter of the specification.
The schema object should not have information on how to construct the target data type, for various reasons that are laid out in the internal specification document. 
This PR severs the reference from the error schema to the error ctor. Instead, the TypeRegistry is used to link the two objects.
=> chore(core/schema): separate error schema and error ctor

gradle.properties, smithy-typescript-codegen/build.gradle.kts
* Doc https://docs.gradle.org/current/userguide/configuration_cache.html
* User Guide https://docs.gradle.org/9.0.0/userguide/configuration_cache_enabling.html
Enables Gradle configuration cache for improved build performance
```console
$ smithy-typescript> ./gradlew clean build -Plog-tests
Reusing configuration cache.
...
BUILD SUCCESSFUL in 14s
33 actionable tasks: 31 executed, 2 up-to-date
Configuration cache entry reused
```
---
=> Enable Gradle configuration cache

smithy-typescript-codegen/build.gradle.kts
* Missed in https://github.com/smithy-lang/smithy-typescript/pull/1722
* Noticed while attempting to use it in https://github.com/aws/aws-sdk-js-v3/pull/7396
Adds explicit dependency on 'set-dependency-versions' in 'sourcesJar'
---
=> Add explicit dependency on 'set-dependency-versions'

.github/workflows/ci.yml, gradle.properties
The first party `gradle/actions/setup-gradle` is better, as it does configuration caching
Details in https://github.com/actions/setup-java/issues/588
Replaces `cache: gradle` in `actions/setup-java` with `gradle/actions/setup-gradle`
---
=> Use gradle/actions/setup-gradle for setting up gradle

CHANGELOG.md, README.md, build.gradle.kts
Internal JS-6274
Bumps codegen version to 0.36.1
---
=> Bump codegen version to 0.36.1
